P=[
(14,40,"There was, in her cupboard, a Golden Cap, with a circle of diamonds",
"The Witch has a Golden Cap that lets her call the Winged Monkeys three times. She has used it twice, so only one use is left, and she keeps it for her last chance to destroy Dorothy.",
"In her cupboard there was a Golden Cap, with a circle of diamonds and rubies running round it. This Golden Cap had a charm. Whoever owned it could call three times on the Winged Monkeys, who would obey any order they were given. But no person could command these strange creatures more than three times. The Wicked Witch had already used the charm of the Cap twice. The first time was when she made the Winkies her slaves and set herself to rule over their country. The Winged Monkeys had helped her do this. The second time was when she had fought against the Great Oz himself and driven him out of the land of the West. The Winged Monkeys had also helped her in doing this. She could use this Golden Cap only once more, and for this reason she did not like to do so until all her other powers were used up. But now her fierce wolves and her wild crows and her stinging bees were gone, and her slaves had been scared away by the Cowardly Lion. She saw that there was only one way left to destroy Dorothy and her friends.",
["charm","commanded","exhausted","stinging"]),
(14,71,"But the wicked creature was very cunning",
"The Witch puts an invisible iron bar on the floor. Dorothy falls over it, and the Witch takes one of the Silver Shoes.",
"But the wicked creature was very clever in a bad way, and at last she thought of a trick that would give her what she wanted. She put a bar of iron in the middle of the kitchen floor, and then by her magic made the iron so that human eyes could not see it. So when Dorothy walked across the floor, she fell over the bar, because she could not see it, and fell flat on the floor. She was not much hurt, but in her fall one of the Silver Shoes came off. Before she could reach it, the Witch took it quickly and put it on her own thin foot.",
["cunning","invisible","stumbled","snatched","skinny"]),
(15,12,"The tinsmiths looked the Woodman over carefully",
"The tinsmiths mend the Tin Woodman in three days and four nights. He has some patches, but he does not mind, because he is not a vain man.",
"The tinsmiths looked the Woodman over carefully and then said that they thought they could mend him so that he would be as good as ever. So they began work in one of the big yellow rooms of the castle. They worked for three days and four nights, hammering and twisting and bending and soldering and polishing and pounding at the legs and body and head of the Tin Woodman. At last he was straightened out into his old form, and his joints worked as well as ever. It is true that there were several patches on him, but the tinsmiths did a good job. The Woodman was not a vain man, so he did not mind the patches at all.",
["tinsmiths","soldering","polishing","pounding","patches","vain"]),
(16,35,"There lived here then, away at the North, a beautiful princess",
"A Winged Monkey tells a story about a powerful, good sorceress named Gayelette. She wanted to marry a wise boy named Quelala, and she used all her magic to make him strong and good.",
"The Winged Monkey says, \"A beautiful princess, who was also a powerful sorceress, lived here then, away in the North. All her magic was used to help the people, and she was never known to hurt anyone who was good. Her name was Gayelette, and she lived in a handsome palace built from great blocks of ruby. Everyone loved her, but her greatest sorrow was that she could find no one to love in return, because all the men were much too stupid and ugly to marry one so beautiful and wise. At last, however, she found a boy who was handsome and manly and wise beyond his years. Gayelette decided that when he grew to be a man she would make him her husband. So she took him to her ruby palace and used all her magic powers to make him as strong and good and lovely as any woman could wish. When he grew to manhood, Quelala, as he was called, was said to be the best and wisest man in all the land. His manly beauty was so great that Gayelette loved him dearly, and went fast to make everything ready for the wedding.\"",
["sorceress","palace","ruby","handsome","manly","manhood","hastened"]),
(16,36,"My grandfather was at that time the King of the Winged Monkeys",
"The monkey's grandfather, the King of the Winged Monkeys, loved jokes. Just before the wedding, he and his band dropped Quelala into the river.",
"The Winged Monkey says, \"My grandfather was at that time the King of the Winged Monkeys who lived in the forest near Gayelette's palace. The old fellow loved a joke better than a good dinner. One day, just before the wedding, my grandfather was flying out with his band. He saw Quelala walking beside the river. Quelala was dressed in a rich costume of pink silk and purple velvet, and my grandfather thought he would see what he could do. At his word the band flew down and took hold of Quelala. They carried him in their arms until they were over the middle of the river, and then dropped him into the water.\"",
["fellow","band","costume","velvet","seized"]),
(17,59,"Oh, I am a ventriloquist,” said the little man.",
"The little man says that he is a ventriloquist, so he could make his voice come from the Head. He shows the things he used to trick them: a dress, a mask, skins sewn together, and a ball of cotton.",
"\"Oh, I am a ventriloquist,\" said the little man. \"I can throw the sound of my voice wherever I wish, so that you thought it was coming out of the Head. Here are the other things I used to trick you.\" He showed the Scarecrow the dress and the mask that he had worn when he seemed to be the lovely Lady. The Tin Woodman saw that his terrible Beast was only a lot of skins, sewn together, with slats to keep their sides out. As for the Ball of Fire, the false Wizard had hung that also from the ceiling. It was really a ball of cotton, but when oil was poured on it, the ball burned fiercely.",
["ventriloquist","deceive","slats","cotton"]),
(17,71,"Just to amuse myself, and keep the good people busy",
"Oz says that he had the people build the City just for fun. He called it the Emerald City and gave them green spectacles so that everything they saw was green.",
"The Wizard says, \"Just to have some fun, and to keep the good people busy, I told them to build this City and my Palace. They did it all willingly and well. Then I thought that the country was so green and beautiful that I would call it the Emerald City. To make the name fit better, I put green spectacles on all the people, so that everything they saw was green.\"",
["amuse","spectacles"]),
(18,11,"So the Wizard unfastened his head and emptied out the straw.",
"The Wizard takes out the straw from the Scarecrow's head and puts in bran mixed with many pins and needles. Then he fills the rest of the space with straw.",
"So the Wizard took off the Scarecrow's head and emptied out the straw. Then he went into the back room and took a measure of bran, which he mixed with a great many pins and needles. He shook them together well, and filled the top of the Scarecrow's head with the mixture. He stuffed the rest of the space with straw, to keep it in place.",
["unfastened","bran","needles","thoroughly","mixture"]),
(18,23,"So Oz brought a pair of tinsmith’s shears and cut a small",
"Oz cuts a small, square hole in the left side of the Tin Woodman's chest. He takes a pretty heart, made all of silk and stuffed with sawdust, out of a chest of drawers.",
"So Oz brought a pair of tinsmith's shears and cut a small, square hole in the left side of the Tin Woodman's breast. Then he went to a chest of drawers and took out a pretty heart. It was made all of silk and stuffed with sawdust.",
["shears","tinsmith","breast","sawdust"]),
(19,22,"Oz ordered the balloon carried out in front of the Palace",
"Oz has the balloon carried out in front of the Palace. The Tin Woodman makes a fire, and Oz holds the bottom of the balloon over it, so that hot air fills the silk bag and the balloon rises.",
"Oz told them to carry the balloon out in front of the Palace, and the people looked at it with great interest. The Tin Woodman had chopped a big pile of wood, and now he made a fire of it. Oz held the bottom of the balloon over the fire so that the hot air that came up from it would be caught in the silk bag. Slowly the balloon swelled out and rose into the air, until at last the basket just touched the ground.",
["balloon","curiosity","gradually","swelled"]),
(20,6,"The Scarecrow was now the ruler of the Emerald City",
"The Scarecrow is now the ruler of the Emerald City. The people are proud of him, because no other city in the world is ruled by a stuffed man.",
"The Scarecrow was now the ruler of the Emerald City, and although he was not a Wizard, the people were proud of him. \"For,\" they said, \"there is not another city in all the world that is ruled by a stuffed man.\" And as far as they knew, they were quite right.",
["ruler","stuffed"]),
(21,17,"The Scarecrow, who was in the lead, finally discovered a big tree",
"The Scarecrow walks under a big tree with wide branches. The branches bend down, hold him and throw him among the other travelers.",
"The Scarecrow, who was in the lead, at last found a big tree with such wide-spreading branches that there was room for the party to pass under it. So he walked forward to the tree, but just as he came under the first branches, they bent down and turned around him. The next minute he was lifted from the ground and thrown head first among his fellow travelers.",
["twined","headlong","flung"]),
]
