PH={
"get over":("To go across or past something, such as a hill. It can also mean to stop feeling bad about something.","phrasal verb",["gets over","got over","getting over"],"we must get over the hill"),
"set to work":("To begin to work.","idiom",["sets to work","setting to work"],"the Tin Woodman set to work with his axe"),
"make up one's mind":("To decide.","idiom",["made up my mind","made up her mind","makes up his mind"],"I made up my mind that instead of living alone"),
"in spite of":("Even though something is true; not stopped by something.","phrase",[],"in spite of the many years she has lived"),
"keep away":("To stay far from someone or something.","phrasal verb",["keeps away","kept away","keeping away"],"It is better for people to keep away from Oz"),
"look after":("To take care of someone or something.","phrasal verb",["looks after","looked after","looking after"],"I’ll go look after the stock"),
"pass the night":("To spend the night in a place.","idiom",["passes the night","passed the night","passing the night"],"where she should pass the night"),
"take care of":("To look after someone; to make sure someone is safe.","idiom",["takes care of","took care of","taking care of"],"how to take care of ourselves"),
"take care to":("To be careful to do something.","idiom",["took care to","takes care to"],"took care to oil myself whenever I needed it"),
"no matter":("It does not change anything; it is not important.","idiom",[],"no matter whether one is a crow or a man"),
"by and by":("After a short time; soon.","idiom",[],"by and by they were drawn out of the current"),
"on and on":("Without stopping; for a very long time.","idiom",[],"he sleeps on and on forever"),
"turn back":("To go back the way you came.","phrasal verb",["turned back","turns back","turning back"],"she bravely resolved not to turn back"),
"put on":("To place clothes or other things on your body.","phrasal verb",["puts on","put on","putting on"],"you must put on the spectacles"),
"fall asleep":("To start sleeping.","idiom",["falls asleep","fell asleep","falling asleep"],"if you should fall asleep you are too big to be carried"),
"fast asleep":("Sleeping very deeply.","phrase",[],"fell among the poppies, fast asleep"),
"come along":("To come to a place; to happen to be there.","phrasal verb",["comes along","came along","coming along"],"the tinsmith happened to come along"),
"set off":("To start to go somewhere.","phrasal verb",["sets off","setting off"],"the little company set off upon the journey"),
"set free":("To let someone go; to make someone free.","phrasal verb",["sets free","setting free"],"they are all set free"),
"all the same":("Even so; it makes no difference.","idiom",[],"All the same,” said the Scarecrow"),
"take pains":("To be very careful or to work hard to do something.","idiom",["took pains","takes pains"],"they took pains not to light on his head"),
"in the midst of":("In the middle of something.","phrase",[],"in the midst of the great Kansas prairies"),
"get out of":("To leave a place; to get away from something.","phrasal verb",["gets out of","got out of","getting out of"],"to get out of the forest"),
"lie down":("To put your body flat on a bed or the ground.","phrasal verb",["lies down","lay down","lying down"],"lie down beside me"),
"used to":("Having done something many times so that it is easy for you (used with 'be').","phrase",[],"once I was used to it"),
"get along":("To move forward; to do well enough.","phrasal verb",["gets along","got along","getting along"],"managed to get along fairly well"),
"find out":("To learn a fact that you did not know.","phrasal verb",["finds out","found out","finding out"],"find out whether he kept his promises"),
"look for":("To try to find something.","phrasal verb",["looks for","looked for","looking for"],"they looked for the place where it would be easiest"),
"go on":("To keep doing something; to continue.","phrasal verb",["goes on","went on","going on"],"went on eating her bread"),
"keep on":("To continue to go or to do something.","phrasal verb",["keeps on","kept on","keeping on"],"we can keep on to the Emerald City"),
"to be sure":("It is true that; certainly (used before a 'but' idea).","idiom",[],"To be sure, neither the Woodman nor the Scarecrow ever ate anything"),
"one after the other":("First one, and then the next one.","idiom",[],"cut off my arms, one after the other"),
"once in a while":("Sometimes, but not often.","idiom",[],"Once in a while she would pass a house"),
"run away":("To leave a place fast, often because of fear.","phrasal verb",["runs away","ran away","running away"],"he has always run away as fast as he could go"),
"a great deal":("A large amount.","phrase",[],"with a great deal of curiosity"),
"after all":("Even if what was said or thought before was different.","idiom",[],"not such a good Scarecrow after all"),
"so as to":("In order to; for the purpose of.","phrase",[],"so as to draw a crowd of people together"),
"instead of":("In the place of something else.","phrase",[],"instead of living alone I would marry"),
"in front of":("Before something; at the front of something.","phrase",[],"in front of the Palace"),
"for fear of":("Because you are afraid that something bad may happen.","phrase",[],"for fear of getting lost"),
"by means of":("By using something; with the help of something.","phrase",[],"by means of joints"),
"do away with":("To stop or kill someone or something.","phrasal verb",["does away with","did away with","doing away with"],"do away with the other Witch"),
"tired out":("Very tired.","phrase",[],"They were all tired out when they reached the shore"),
"look out":("To look from inside a place to the outside.","phrasal verb",["looks out","looked out","looking out"],"just far enough to look out"),
"come back":("To return to a place.","phrasal verb",["comes back","came back","coming back"],"I can’t come back, my dear"),
"go back":("To return to a place.","phrasal verb",["goes back","went back","going back"],"go back to the dry, gray place"),
"pick up":("To take something up from the ground or from a table.","phrasal verb",["picks up","picked up","picking up"],"as he watched her pick up the Scarecrow"),
"turn out":("To end in a certain way.","phrasal verb",["turns out","turned out","turning out"],"my new brain is going to turn out"),
"as fast as":("At the same speed as; as quickly as it is possible.","phrase",[],"as fast as he could go"),
"as soon as":("At the very time that; right after.","phrase",[],"as soon as it was finished I found myself"),
"run after":("To follow someone fast, in order to catch up with them.","phrase",["run after","runs after","running after"],"so she ran after her"),
"wait for":("To stay in a place until something happens.","phrasal verb",["waits for","waited for","waiting for"],"waited for the fresh breeze to waken her"),
"ask for":("To say that you want something.","phrasal verb",["asks for","asked for","asking for"],"I shall ask for brains instead of a heart"),
"fall off":("To drop down from something.","phrasal verb",["falls off","fell off","falling off"],"the Scarecrow fell off the wall"),
"get up":("To stand after sitting or lying down.","phrasal verb",["gets up","got up","getting up"],"Dorothy and the Lion got up"),
}
