S=[
(3,"Not a tree nor a house broke the broad sweep of flat country",
"Not one tree and not one house broke the wide, flat land.",
"'Not a tree nor a house' starts the sentence, so the verb 'broke' comes right after it. 'Not ... nor ...' means 'neither ... nor ...': not one thing, and not the other."),
(4,"nor was it dark, for the bright sunshine came in at the window",
"It was not dark either, because the bright sunshine came in at the window.",
"'Nor' at the start of a clause turns the verb and subject round ('nor was it' not 'nor it was'). It adds one more thing that was not true: the house was not moving, and it was not dark."),
(4,"they were, so far as looks go, many years older",
"As far as how they looked, they were many years older than Dorothy.",
"'So far as looks go' is a short phrase that means 'if you judge by how they look'. It is put between commas in the middle of the sentence."),
(4,"I am not as powerful as the Wicked Witch was who ruled here",
"She says she is not as strong as the Wicked Witch who ruled here. If she were, she would have set the people free herself.",
"'Not as ... as ...' compares two things that are not equal. 'Or' here means 'if that were not true'. 'I should have set' means 'I would have set' and tells what she would have done."),
(4,"Whether he is a man or not I cannot tell",
"I cannot say if he is a man or not.",
"'Whether ... or not' is a noun clause that is the object of 'cannot tell'. It is put first in the sentence for strong effect; the usual order is 'I cannot tell whether he is a man or not'."),
(5,"began to wonder where she should pass the night",
"She started to ask herself where she could spend the night.",
"'Where she should pass the night' is an indirect question after 'wonder'. It uses the order 'subject + verb' (where she should pass), not a question order. 'Should' here asks what is the best thing to do."),
(5,"such as every man wore in this country",
"They were the kind of boots that every man in this country wore.",
"'Such as' brings in an example of a kind: 'boots such as every man wore' means 'the kind of boots that every man wore'. 'Wore' is the past simple of 'wear'."),
(6,"the farther they went the more dismal and lonesome the country became",
"The more they went on, the sadder and lonelier the country was.",
"'The + comparative ..., the + comparative ...' shows that two things change together: 'the farther ..., the more dismal ...'. When one grows, the other grows too."),
(6,"in any other country, be it ever so beautiful",
"Even if another country is very beautiful, people like Dorothy would still choose home.",
"'Be it ever so beautiful' is an old way to say 'even if it is very beautiful'. The verb 'be' comes first, with no 'if', to make a condition. We now say 'however beautiful it is'."),
(6,"If it required brains to figure it out, I never should have said it",
"If you needed brains to work it out, I would never have said it.",
"This is a mixed conditional: 'If it required' uses the past form, and 'I never should have said' looks at what was done. 'Should have said' here means 'would have said'."),
(6,"having in this world, no matter whether one is a crow or a man",
"Brains are the only things worth having in this world, whether you are a crow or a man.",
"'No matter whether ... or ...' means 'it makes no difference if it is this or that'. 'Worth having' is 'worth' + the -ing form: a thing that is good to have."),
(7,"But no one can love who has not a heart",
"Only a person who has a heart can love.",
"'Who has not a heart' is an old way to say 'who does not have a heart'; there is no 'do' with 'not'. The 'who' clause tells us which person cannot love: one who has no heart."),
(7,"if I should get caught in the rain, and rust again, I would need",
"If I get caught in the rain and rust again, I will need the oilcan very much.",
"'If I should get caught' is a polite, less sure way to say 'if I get caught'. 'Should' after 'if' shows that this may happen, but he thinks it is not likely. 'Get caught' uses 'get' with a past participle to mean 'become'."),
(7,"I little knew how cruel my enemy could be",
"I did not know at all how cruel my enemy could be.",
"'Little' put before the verb means 'not at all' or 'hardly', in an old-fashioned way. 'I little knew' is the same as 'I did not know'. 'How cruel my enemy could be' is a noun clause."),
(7,"but, nothing daunted, I had them replaced with tin ones",
"But I was not afraid, and I had new arms made of tin put on in their place.",
"'Nothing daunted' is a short phrase that means 'not made afraid at all'. 'I had them replaced' is 'have + object + past participle': someone else did the work for me."),
(8,"If the elephants and the tigers and the bears had ever tried to fight",
"If the elephants, the tigers or the bears had ever tried to fight me, I would have run away.",
"This is a third conditional sentence: 'If + had + past participle' ..., 'I should have run' (in the next part). It is about the past and about something that did not happen."),
(8,"if I had no heart I should not be a coward",
"If I had no heart, I would not be a coward.",
"This is a second conditional sentence: 'If + past simple, should/would + verb'. It is about something that is not true now. 'Should' with 'I' is an old-fashioned way to say 'would'."),
(9,"so sharp was his axe that the tree was soon chopped nearly through",
"His axe was so sharp that the tree was soon cut nearly through.",
"The words 'so sharp' come first, so the verb 'was' comes before the subject 'his axe'. The usual order is 'his axe was so sharp that ...'. 'So ... that ...' shows a result."),
(9,"he gave so loud and terrible a roar that Dorothy screamed",
"He gave such a loud and terrible roar that Dorothy screamed.",
"'So + adjective + a + noun + that ...' is another way to say 'such a + adjective + noun + that ...'. The 'a' comes after the adjectives. It shows the result."),
(9,"“I haven’t the faintest idea,” said the Tin Woodman",
"I have no idea at all.",
"'Haven't the faintest idea' uses 'have' without 'do', which is an old British way to say 'I do not have'. 'The faintest' is a superlative that means 'the least'. So it means 'no idea at all'."),
(10,"had they not felt so sorry for the poor Scarecrow, they could have been",
"If they had not felt so sorry for the poor Scarecrow, they could have been very happy.",
"'Had they not felt' starts with 'had' instead of 'if', and so it means 'if they had not felt'. This is the third conditional: it is about the past. The result is 'could have been'."),
(11,"would have bitten him had he not known very well",
"Toto would have bitten him if he had not known very well that the Woodman was made of tin.",
"'Had he not known' means 'if he had not known'. The 'if' is left out and 'had' is put before the subject. The result part is 'would have bitten', a third conditional."),
(11,"many though they were, could hardly stir the heavily loaded truck",
"Even though there were many mice, they could hardly move the truck full of heavy things.",
"'Many though they were' means 'although they were many'. 'Though' comes after the adjective, and the adjective goes first. 'Could hardly' means 'could only just'."),
(11,"lest he should run after her and frighten her",
"Dorothy held Toto so that he would not run after the Queen and frighten her.",
"'Lest' means 'so that ... not' or 'for fear that'. It is a formal, old word. The verb after it is 'should + verb': 'lest he should run'. It gives a reason for the action in the first part."),
(12,"When they were on, Dorothy could not take them off had she wished",
"When the spectacles were on, Dorothy could not take them off, even if she had wanted to.",
"'Had she wished' means 'if she had wished'. The word 'if' is left out and 'had' goes before 'she'. It is a third conditional that is put at the end of the sentence."),
(13,"It was fortunate the Tin Woodman had no heart at that moment",
"It was lucky that the Tin Woodman had no heart at that moment, because it would have beat loud and fast from fear.",
"The sentence is 'It was fortunate (that) the Tin Woodman had no heart ...'. The word 'that' is left out. 'It' is an empty subject, and the real idea is in the clause after 'fortunate'."),
(13,"But being only tin, the Woodman was not at all afraid",
"But the Woodman was made only of tin, so he was not afraid at all.",
"'Being only tin' is a participle phrase at the start. It gives a reason and means 'because he was only tin'. The subject of 'being' is the same as the subject of the main clause: the Woodman."),
(13,"If he is a Beast when I go to see him, I shall roar",
"If he is a Beast when I go to see him, I will roar as loud as I can.",
"This is a first conditional sentence: 'If + present simple, shall + verb'. 'Shall' with 'I' is an old-fashioned way to say 'will'. 'My loudest' means 'as loud as I can'."),
(14,"neither the Winged Monkeys nor she, herself, dare hurt the girl in any way",
"The Witch knew well that neither the Winged Monkeys nor she herself dared to hurt the girl.",
"'Neither ... nor ...' links two subjects, and the verb is 'dare', with no -s. 'Dare' here is used like a modal verb, followed by 'hurt' with no 'to'. 'Herself' makes 'she' stronger."),
(14,"he lay so battered and dented that he could neither move nor groan",
"He lay so hurt and bent out of shape that he could not move and could not make a sound.",
"'So ... that ...' shows a result. 'Could neither move nor groan' uses 'neither ... nor ...' with two verbs, and it means he could not do either one."),
(16,"owner of the Golden Cap, whosoever he may be",
"Whoever the owner of the Golden Cap is, the Monkeys are his slaves three times.",
"'Whosoever' is an old, formal word for 'whoever'. 'May be' here shows that we do not know who it is. The clause says it does not matter who it is."),
(17,"had they not thought I was more powerful than they themselves",
"If the two Witches had not thought I was stronger than they were, they would have destroyed me.",
"'Had they not thought' means 'if they had not thought'. 'More powerful than they themselves' is a comparison, and 'themselves' makes 'they' stronger. The result part is 'they would surely have destroyed me'."),
(17,"the longer you are on earth the more experience you are sure to get",
"The longer you live, the more experience you will get.",
"'The + comparative ..., the + comparative ...' shows that two things grow together: 'the longer you are ..., the more experience ...'. 'Are sure to get' means you will certainly get."),
(17,"I should never be found out",
"I thought that I would never be found out.",
"'I thought I should never be found out' is reported thought in the past. 'Should' is used like 'would' for 'I'. 'Be found out' is a passive verb that means 'be discovered'."),
(20,"If it wasn’t for Dorothy I should never have had brains",
"If Dorothy had not helped me, I would never have had brains.",
"'If it wasn't for Dorothy' means 'without Dorothy'. 'I should never have had' means 'I would never have had', and it is about the past."),
(22,"I cannot think why this wall is here, nor what it is made of",
"I cannot think why this wall is here, and I cannot think what it is made of.",
"'Why this wall is here' and 'what it is made of' are noun clauses after 'think'. 'Nor' adds a second thing that is also not known. 'Made of' tells us what stuff it is."),
(24,"It is useless to fight people with shooting heads; no one can withstand them",
"It is no use to fight people with shooting heads. No one can stand against them.",
"'It is useless to fight' uses an empty 'it' as the subject; the real subject is 'to fight people'. 'Withstand' is a verb that means 'stand against'. The two parts are joined with a semicolon."),
]
