from lib import *
W('plucked','past-tense verb','Pulled a flower off its plant with the fingers.',[])
W('delightful','adjective','Very pleasing and lovely. It makes you happy.')
W('henceforth','adverb','From that time on.')
W('conspicuous','adjective','Easy to see. It stands out clearly.',why='This is a rare word in a higher level.')
W('simultaneously','adverb','At the same time.')
W('propose','verb','To ask someone to marry you.')
W('boast','verb','To talk about yourself or your things with too much pride.')
W('stock','plural noun','Small parts of a company that people buy and sell to make money. "Stocks and shares" are both of this kind.',['stocks'])
W('share','plural noun','Small parts of a company that people buy and sell to make money.',['shares'])
W('gleefully','adverb','In a very happy way, as if enjoying something.')
W('imploringly','adverb','In a way that begs for something very strongly.')
W('honourable','adjective','Good and honest. Doing what is right.')
W('prejudiced','adjective','On one side before you know all the facts. Not fair.')
W('daresay','verb','To think that something is probably true. "I daresay" means "I think it is likely".')
W('shilling','noun','An old British coin of small value.',['shillings'])
W('guinea','noun','An old British amount of money, a little more than a pound.')
W('naught','noun','Nothing. Zero.',why='This is an old word.')
W('chequebook','noun','A book of paper forms for paying money from a bank.')
W('mumps','uncountable noun','An illness that children often get.')
W('measles','uncountable noun','An illness that children often get. It gives red spots on the skin.')
W('kindergarten','noun','A school for very small children.')
W('prim','adjective','Very neat and proper. Too serious about good manners.')
W('perambulators','plural noun','An old word for prams. A pram is a small bed on wheels for a baby.',['perambulator'],why='This is an old-fashioned word.')
W('nursemaid','noun','A young woman who is paid to look after children.',['nursemaids'])
W('mistress','noun','A woman who is the head of a home. Servants work for her.',['mistresses'])
W('thorough','adjective','Careful and complete. Nothing is missed.')
W('propriety','noun','Polite and correct behaviour.')
W('sedately','adverb','In a calm, slow and serious way.')
W('footer','noun','An old slang word for football.',why='This is an old slang word.')
W('forms','plural noun','Long wooden seats for several people to sit on.')
W('pinafore','noun','A piece of clothing worn over other clothes to keep them clean.')
W('affected','past-tense verb','Pretended to be or to feel something.',['affect'])
W('inferior','adjective','Lower in rank. Less good than others.')
W('midget','noun','A very small person. It is an old word, and some people find it rude today.',why='This is an old word.')
W('pirouette','verb','To spin round and round fast on one foot, like a dancer.')
W('rummage','verb','To search through things by moving them about.')
W('perplexing','adjective','Hard to understand. It makes you confused.')
W('cocky','adjective','Too sure of yourself. A little too proud.')
W('romp','noun','A noisy, lively game.',['romps','romped'])
W('revelation','noun','Something new that you suddenly learn.')
W('tolerant','adjective','Patient and kind about something that you do not agree with.')
W('skeleton','noun','In "skeleton leaves", dry leaves that have only their thin lines left.')
W('entrancing','adjective','So lovely that you cannot stop looking at it.')
W('gnashed','past-tense verb','Ground the teeth together or showed them in anger.',['gnash'])
W('rent','past-tense verb','Tore.')
W('coracle','noun','A small round boat.',['coracles'])
W('lair','noun','A wild animal\'s hiding place.',['lairs'])
W('delectable','adjective','Very pleasing and nice.')
W('snug','superlative adjective','Small, warm and comfortable. "Snuggest" means the most snug.',['snuggest'])
W('tedious','adjective','Long and boring.')
W('flamingo','noun','A large pink bird with long legs and a long neck.',['flamingoes'])
W('wigwam','noun','A round tent that some Native American people lived in.')
W('deftly','adverb','Quickly and with skill.')
W('forsaken','past participle','Left alone by someone. Given up.')
W('surf','uncountable noun','The white waves that break on the shore.')
W('scrawled','past participle','Written in an untidy way.')
W('trifle','noun','Something small that is not important.')
W('clad','past participle','Dressed.')
W('ooze','verb','To flow out slowly.')
W('savages','plural noun','An old word that the author uses for wild people who live far from towns. Today it is thought to be rude.',['savage'],why='This is an old word that can hurt people today.')
W('gnomes','plural noun','In stories, small old men who live under the ground.',['gnome'])
W('peeping','present participle','Looking quietly at something through a small space.',['peep','peeped'])
W('lingering','present participle','Staying somewhere a long time.',['linger'])
W('stowing','present participle','Putting something away in a place.',['stow'])
W('tranquilly','adverb','In a calm and quiet way.')
W('expenses','plural noun','Money that you spend on things.',['expense'])

Ph('tot up','To add numbers together.','phrasal verb','when she should have been totting up',['totting up','totted up'])
Ph('narrow squeak','A very close escape from trouble.','idiom','Michael had even a narrower squeak',['narrower squeak'])
Ph('keep the books','To write down money that comes in and goes out.','idiom','she kept the books perfectly',['kept the books'])
Ph('owing to','Because of.','phrase','owing to the amount of milk')
Ph('nip in','To go in quickly in front of others.','phrasal verb','took a cab and nipped in first',['nipped in'])
Ph('whip off','To take something off very quickly.','phrasal verb','she first whipped off Michael\u2019s pinafore',['whipped off'])
Ph('come what might','No matter what happens.','idiom','to risk it, come what might')
Ph('in the offing','At sea, far from the shore but still in sight.','idiom','rakish-looking craft in the offing')
Ph('break through','To force a way through something.','phrasal verb','a strange boy had broken through from it',['broken through'])
Ph('grow up','To become an adult.','phrasal verb','All children, except one, grow up.')
Ph('blow over','To pass and be forgotten.','phrasal verb','Leave it alone, and it will blow over.')
Ph('by and by','After a short time.','idiom','by and by whole cauliflowers dropped out')
Ph('on the other hand','Used to give a different point of view.','idiom','But, on the other hand, there were the leaves.')
Ph('give up','To stop trying.','phrasal verb','he gave up trying for the kiss',['gave up'])

P(2,"All children, except one, grow up. They soon know that they will grow up",
 "Wendy learns when she is two that she must grow up. Her mother wishes she could stay small forever.",
 "All children grow up, except one. Children soon know that they will grow up. Wendy learned it in this way. One day, when she was two years old, she was playing in a garden. She pulled off another flower and ran with it to her mother. I think she must have looked very lovely, because Mrs. Darling put her hand to her heart and cried, \"Oh, why can't you stay like this forever!\" That was all they said about it. But from then on Wendy knew that she must grow up. You always know after you are two. Two is the beginning of the end.",
 ['plucked','delightful','henceforth','remain'])
P(2,"Mrs. Darling first heard of Peter when she was tidying up her children’s minds",
 "Mrs. Darling hears of Peter when she tidies her children's minds. The writer says every good mother does this at night.",
 "Mrs. Darling first heard of Peter when she was tidying up her children's minds. Every good mother does this each night after her children are asleep. She looks through their minds and puts things straight for the next morning. She puts back in the right places the many things that moved about during the day. If you could stay awake (but of course you can't), you would see your own mother doing this. It is very interesting to watch. It is like tidying drawers. You would see her on her knees, staying a while in a playful way over some of your things, and wondering where you found this thing. Some things she finds are sweet and some are not so sweet. She presses this one to her cheek as if it were as nice as a kitten, and quickly puts that one out of sight. When you wake in the morning, the naughty things and bad feelings that you took to bed have been folded up small and put at the bottom of your mind. On top, nicely aired, are your prettier thoughts, ready for you to put on.",
 ['rummage','lingering','stowing','naughtinesses'])
S(2,"If you could keep awake (but of course you can’t) you would see your own mother doing this",
 "If you could stay awake, you would see your own mother doing this. But of course you cannot stay awake.",
 "'If you could ... you would ...' talks about something that is not real, and the writer says in brackets that you cannot do it.")
S(2,"the many gentlemen who had been boys when she was a girl",
 "This is how Mr. Darling won her. Many men had been boys when she was a girl. They all found out at the same time that they loved her. They all ran to her house to ask her to marry them, except Mr. Darling, who took a cab and got there first. So he got her.",
 "'The way ... was this:' uses a colon to start the story; 'had been boys' is the past perfect for a time before she was a girl.")
S(2,"On these magic shores children at play are forever beaching their coracles",
 "On these magic shores, children who are playing are always pulling their little boats onto the beach.",
 "'are forever + -ing' (present continuous with 'forever') shows something that happens again and again.")
S(2,"she had believed in him at the time, but now that she was married",
 "She had believed in him at that time, but now she was married and full of sense, and she quite doubted that there was any such person.",
 "'had believed' (past perfect) is an earlier time than 'now'; 'now that' means 'because now'.")
