from lib import *
W('ruthless','adjective','Cruel, with no pity.')
W('ironical','adjective','Saying one thing but meaning the opposite.')
W('escorted','past-tense verb','Went with someone to guide or guard them.',['escort'])
W('gagged','past participle','Having cloth put over the mouth so that you cannot speak.',['gag'])
W('divulge','verb','To tell a secret.')
W('haughtily','adverb','In a proud way that looks down on others.')
W('trussing','noun','Tying up tightly.',['truss'])
W('malicious','adjective','Wanting to hurt others.')
W('probing','present participle','Searching deeply to find out something.',['probe'])
W('addicted','adjective','Having a strong habit that you cannot stop.')
W('girth','noun','The distance round something, such as a fat body.')
W('whittled','past-tense verb','Cut small pieces off wood to make it smaller.',['whittle'])
W('subterranean','adjective','Under the ground.')
W('morass','noun','Wet, soft ground that is hard to walk through.')
W('surmounted','past-tense verb','Got over a problem.',['surmount'])
W('infuriated','adjective','Made very angry.')
W('brooding','present participle','Thinking for a long time about something sad or angry.',['brood'])
W('omen','noun','A sign that something good or bad will happen.')
W('nether','adjective','Lower. Lying below. It is an old word.',why='This is an old word.')
W('tenement','noun','A room or building to live in.')
W('void','noun','A large empty space.')
W('unmolested','adjective','Not stopped or harmed.')
W('shaft','noun','A long, narrow passage going up or down.')
W('coverlet','noun','A cover for a bed.')
W('vex','verb','To make someone annoyed.')
W('piteously','adverb','In a way that makes people feel pity.')
W('riddle','noun','Something that is hard to understand. A puzzle.')
W('indignity','noun','Something that makes you feel shamed.')
W('stranded','past participle','Left in a place and not able to move.',['strand'])
W('compassion','noun','A feeling of pity and a wish to help.')
W('sombre','adjective','Dark and sad.')
W('harpsichord','noun','An old musical instrument like a piano, with strings that are plucked.')
W('idyllic','adjective','Peaceful and beautiful.')
W('impertinent','adjective','Rude and not showing respect.')
W('personification','noun','A perfect example of a quality.')
W('steeled','past-tense verb','Made hard and strong, ready for what was to come.',['steel'])
W('aperture','noun','A small opening.')
W('fathomed','past-tense verb','Worked out what something was.',['fathom'])
W('virulent','adjective','Very strong and harmful.')
W('gloating','noun','Looking at someone\'s trouble with mean joy.',['gloat'])
W('donning','present participle','Putting on clothes.',['don'])
W('guttered','past-tense verb','Burned weakly and then went out.',['gutter'])
W('conjurers','plural noun','People who do magic tricks.',['conjurer'])
W('dregs','plural noun','The last drops left at the bottom of a cup.')
W('tottering','present participle','Walking in an unsteady way.',['totter'])
W('affirmative','noun','The answer "yes". "In the affirmative" means saying yes.')
W('perilous','adjective','Very dangerous.')
W('quest','noun','A long search for something.')
W('fitful','adjective','Stopping and starting. Not steady.')
W('astir','adjective','Awake and moving about.')
W('adept','adjective','Very good at something.')
W('obliterated','past-tense verb','Rubbed out completely.',['obliterate'])
W('pervaded','past-tense verb','Spread through every part of a place.',['pervade'])
W('lore','noun','Knowledge about a subject that people pass on.')
W('oath','noun','A serious promise.')
W('belay','verb','A sailor\'s word that means "stop".',why='This is a sailor\'s word.')
Ph('dispose of','To get rid of something or deal with it.','phrasal verb','this horror is disposed of',['disposed of'])
Ph('make out','To see or understand something that is hard to see or hear.','phrasal verb','could not make out what she said',['made out'])
Ph('out with it','Used to tell someone to say what they know at once.','idiom','Out with it!')
Ph('set out','To start a journey.','phrasal verb','set out upon his perilous quest',['sets out'])
Ph('at one\'s mercy','In the power of someone else, who can do what they like with you.','idiom','lay at his mercy',['at his mercy'])
Ph('dry up','To become dry and go away.','phrasal verb','It dried up any trickle of pity',['dried up'])
Ph('tell on','To give away someone\'s secret.','phrasal verb','we tell on her')
Ph('steal away','To leave quietly so that no one sees you.','phrasal verb','stole away through the trees',['stole away'])
P(14,"Unaware of the tragedy being enacted above, Peter had continued",
 "Peter tries to show that he does not care that Wendy has gone. He plays his pipes and then falls asleep in the middle of a laugh.",
 "Peter did not know about the sad things that were happening above. For a little time after the children left, he had gone on playing happily on his pipes. This was no doubt a rather sad try to show himself that he did not care. Then he decided not to take his medicine, to make Wendy sad. Then he lay down on the bed outside the cover, to annoy her even more, because she had always tucked them inside it, since you never know that you may not grow cold at the turn of the night. Then he nearly cried. But it came to him how angry she would be if he laughed instead, so he laughed a proud laugh and fell asleep in the middle of it.",
 ['forlorn','coverlet','vex','haughty'])
P(14,"The clapping stopped suddenly; as if countless mothers had rushed to their nurseries",
 "The children's clapping saves Tink. She is soon well and lively again.",
 "The clapping stopped suddenly, as if countless mothers had rushed to their nurseries to see what on earth was happening. But already Tink was saved. First her voice grew strong. Then she popped out of bed. Then she was flashing through the room, more merry and rude than ever. She never thought of thanking those who believed, but she would have liked to get at the ones who had hissed.",
 ['impudent'])
S(14,"had he not been at the tying he would not have discovered",
 "If he had not been at the tying of the children, he would not have found out Slightly's secret. Without the secret he could not have made his foul try on Peter's life.",
 "'Had he not been' means 'If he had not been'; the word order is turned round to talk about something that did not happen.")
S(14,"Dark as were his thoughts his blue eyes were as soft as the periwinkle",
 "Although his thoughts were dark, his blue eyes were as soft as the periwinkle.",
 "'Dark as were his thoughts' means 'Although his thoughts were dark'; 'adjective + as + verb + subject' is a formal way to say 'although'.")
S(14,"Lest he should be taken alive, Hook always carried about his person",
 "Hook always carried a terrible drug on his body, in case he was taken alive.",
 "'Lest he should be taken alive' means 'in case he was taken alive'; 'lest' is a formal word for something you want to avoid.")
