from lib import *
W('deprived','past participle','Had something taken away.',['deprive'])
W('catastrophe','noun','A sudden, very bad event.')
W('unforeseen','adjective','Not expected.')
W('mishap','noun','A small piece of bad luck.')
W('ingenious','adjective','Clever and full of new ideas.')
W('cowering','present participle','Bending down and shrinking back in fear.',['cower'])
W('abject','adjective','In a miserable and frightened state.')
W('carrion','noun','A dead body. Here, it is the author\'s word for the dead pirate.')
W('brazenly','adverb','Openly and without shame.')
W('ditty','noun','A short, simple song.')
W('frisky','adjective','Lively and playful.')
W('grimacing','present participle','Making ugly faces.',['grimace'])
W('blithely','adverb','In a cheerful way, without a care.')
W('haggard','adjective','Looking tired, thin and afraid.')
W('gibbering','present participle','Talking fast in a way that makes no sense, because of fear.',['gibber'])
W('steely','adjective','Hard and cold, like steel.')
W('mutiny','noun','When the crew of a ship take power away from the captain.')
W('mutinous','adjective','Ready to rise up against the captain.')
W('ringleader','noun','The person who leads others in doing something wrong.')
W('proffering','present participle','Holding out something for someone to take.',['proffer'])
W('precipitated','past-tense verb','Threw down suddenly.',['precipitate'])
W('accurst','adjective','Cursed. It is an old spelling.',why='This is an old spelling.')
W('jeering','adjective','Making fun of someone in a loud, unkind way.',['jeeringly','jeer'])
W('manacles','plural noun','Metal rings that hold the hands or feet together.',['manacle'])
W('hearten','verb','To give someone courage.')
W('cajole','verb','To get someone to do something by being nice to them.')
W('quailing','present participle','Shrinking back in fear.',['quail'])
W('avenger','noun','A person who pays back a wrong by hurting the one who did it.')
W('cleave','verb','To cut right through something.')
W('unstrung','adjective','Made weak and nervous.')
W('quarry','noun','A person or animal that is hunted.')
W('buckler','noun','A small round shield.')
W('parried','past-tense verb','Stopped a sword blow by moving his own sword.',['parry'])
W('feint','noun','A move that pretends to go one way, to trick an enemy.')
W('lunge','noun','A sudden step forward with a weapon.',['lunging'])
W('nimble','adjective','Quick and light in movement.')
W('thrust','noun','A sudden push forward with a sword.')
W('quietus','noun','A final end. Here, death.',why='This is an old word.')
W('assailed','past-tense verb','Attacked. Here, thoughts came upon him strongly.',['assail'])
W('pinnacle','noun','The highest point.')
W('flail','noun','A tool for beating grain, made of a stick that swings.')
W('severed','past participle','Cut off.',['sever'])
W('boon','noun','Something good that you ask for.')
W('flouting','present participle','Openly showing no respect.',['flout'])
W('misguided','adjective','Wrong because of bad advice or poor thinking.')
W('grudge','verb','To be unwilling to give something to someone.')
W('precarious','adjective','Not safe or steady.')
W('strutted','past-tense verb','Walked in a proud way, with the chest out.',['strut'])
W('reeking','adjective','Giving off a strong smell.')
W('stifle','verb','To stop a sound from coming out.')
W('superstitious','adjective','Believing in luck, magic or signs.')
W('cat','noun','A whip with nine tails, used to hit people.')
Ph('of a sudden','Suddenly.','idiom','of a sudden')
Ph('at bay','Kept at a distance and not able to come closer.','idiom','at bay in that circle of fire')
Ph('fall to','To begin fighting or eating eagerly.','phrasal verb','Without more words they fell to',['fell to'])
Ph('take one\'s place','To go and stand where someone else was.','idiom','took her place by the mast',['took her place'])
Ph('put up','To put something away.','phrasal verb','Put up your swords, boys')
Ph('pass for','To be accepted as someone or something.','phrasal verb','so that he should pass for her')
Ph('stand by','To watch and not help.','phrasal verb','had stood by taking no part',['stood by'])
Ph('die away','To grow weaker and then stop.','phrasal verb','and died away',['died away'])
Ph('fling off','To throw something off quickly.','phrasal verb','Peter flung off his cloak',['flung off'])
Ph('sing out','To call out loudly.','phrasal verb','Slightly sang out',['sang out'])
Ph('ring out','To sound loudly.','phrasal verb','Peter\u2019s voice rang out',['rang out'])
P(16,"Odd things happen to all of us on our way through life without our noticing",
 "Peter sees that the crocodile is no longer ticking. He decides that the clock has run down.",
 "Odd things happen to all of us on our way through life, and for a time we do not notice that they have happened. For example, we suddenly find that we have been deaf in one ear for we don't know how long, but say half an hour. Now such a thing had happened that night to Peter. When we last saw him, he was creeping across the island with one finger on his lips and his dagger ready. He had seen the crocodile go past without noticing anything strange about it. But after a while he remembered that it had not been ticking. At first he thought this was strange and frightening, but soon he rightly decided that the clock had run down.",
 ['eerie','by and by'])
P(16,"He had one last triumph, which I think we need not grudge him",
 "Hook wins one last thing. Peter kicks him instead of stabbing him,.",
 "He had one last win, which I think we need not refuse him. He stood on the bulwark and looked back over his shoulder at Peter flying through the air. With a movement, he asked Peter to use his foot. It made Peter kick instead of stab.",
 ['triumph','grudge','bulwark','gliding'])
S(16,"No sooner did Peter remember it than he heard the ticking",
 "As soon as Peter remembered it, he heard the ticking.",
 "'No sooner did ... than ...' means 'as soon as'; the helper verb 'did' comes before the subject because 'No sooner' is at the front.")
S(16,"Had the pirates kept together it is certain that they would have won",
 "If the pirates had kept together, they would certainly have won.",
 "'Had the pirates kept together' means 'If the pirates had kept together'; it talks about something that did not happen.")
S(16,"Misguided man though he was, we may be glad, without sympathising with him",
 "Although he was a misguided man, we may be glad, without feeling sorry for him, that in the end he was true to the ways of his people.",
 "'Misguided man though he was' means 'Although he was a misguided man'; 'though' comes after the noun.")
S(16,"we purposely stopped the clock that this knowledge might be spared him",
 "We stopped the clock on purpose so that he would not have this knowledge.",
 "'that ... might be spared him' means 'so that ... would be kept from him'; 'might be spared' is passive.")
