MEAN2 = {
'prim':"Very proper. Too serious about what is polite.",
'perambulators':"An old word for small beds that a baby lies in, which an adult pushes along.",
'rent':"Pulled apart so that there is a hole.",
'surf':"The white water that comes up when the sea hits the land.",
'brute':"A rough and unkind animal or person. Here, the father uses it for the thing he wears at his neck.",
'shudder':"A sudden movement of the body, from fear or a bad feeling.",
'thimble':"A small hard cover that you wear on your hand when you work with cloth.",
'eaves':"The edges of the top of a house that come out past the walls.",
'cunning':"Clever, in a way that makes others believe things that are not true.",
'artfully':"In a clever way that is not quite honest.",
'artful':"Clever in a way that is not honest.",
'darn':"To fix a hole in clothes by working across it by hand.",
'mantelpiece':"The flat place above a fire in a room, where things can be put.",
'rasping':"Rough and hard to listen to.",
'staggering':"Walking in a weak way that may end in a fall.",
'lurches':"Moves suddenly to one side, in a way that is not smooth.",
'tottering':"Walking with weak steps, as if about to fall.",
'tattooed':"With pictures on the skin that stay there.",
'petulantly':"Like a child who does not get what he wants.",
'pettishly':"In a way like a child who is upset.",
'succulence':"The soft, nice taste of food with much liquid in it.",
'lubber':"A big person who does things badly. Here, a man on a ship who does his work badly.",
'timidly':"In a way that shows you are afraid.",
'cozening':"Getting what you want from someone by lies. It is an old word.",
'scaled':"Went up to the top of something high.",
'barque':"A kind of ship. Here, it is the author's joking word for Peter's little boat.",
'recriminations':"Angry words that people say to each other about who did wrong.",
'insinuated':"Said something without saying it openly.",
'wiliness':"Cleverness that is not honest.",
'intimation':"A small sign of something.",
'diabolical':"Very evil.",
'frenzy':"A time of wild feeling that you cannot control.",
'trussing':"Putting ropes round someone so that they cannot move.",
'brig':"A ship with two tall posts that hold the cloth for the wind.",
'doublet':"A coat for a man that fits close to the body, worn long ago.",
'accurst':"Having a bad wish put on it, so that bad things happen. The way it is written is old.",
'feint':"A move that looks like it is going one way but is not, to make an enemy look the wrong way.",
'quixotic':"Wanting to do great and good things in a way that is not clever.",
'halfpennyworth':"A very small amount, as much as half of a small British piece of money can buy.",
}
