PM = {
'narrow squeak':"A time when you nearly had trouble but just got away.",
'in the offing':"Far out on the sea, but you can still see it.",
'mea culpa':"A Latin saying. It means that you say you are to blame.",
'break down':"To lose control and let tears come.",
'in the dead of night':"In the middle of the night, when nothing moves.",
'pick one\'s way':"To walk with care, choosing where to put your feet.",
'rap out':"To say something in a quick, hard way.",
'tuck in':"To fold the covers of a bed close round someone.",
'tuck up':"To fold the covers of a bed close round someone.",
'give someone a hiding':"To hit someone hard because they did wrong.",
'stick on':"To join something to a place with glue.",
'shut up':"To close someone in a place. It can also mean \"stop talking\", which is not polite.",
'show off':"To try to make people look at you and like you.",
'set off':"To start to go somewhere.",
'set out':"To start to go somewhere.",
'pop off':"To go to sleep suddenly.",
'at one\'s ease':"Comfortable and not worried.",
'eyes peeled':"Looking with great care and watching for things.",
'on the prowl':"Moving about without noise, looking for something to catch.",
'get one\'s word in':"To be able to speak when others are talking.",
'keep watch':"To watch so that nothing bad happens.",
'toss for it':"To throw a small piece of money in the air to decide something.",
'on the contrary':"Used to say that the other thing is true.",
'hang up':"To put something up so that it hangs.",
'clear away':"To take away the things you used to eat from.",
'hold up':"To put something up high.",
'beat about the bush':"To talk round a subject and not say clearly what you mean.",
'get on one\'s nerves':"To make someone feel upset and angry, a little at a time.",
'bear down on':"To move toward someone in a way that makes them afraid.",
'dispose of':"To throw away or deal with something so that it is gone.",
'steal away':"To leave without noise so that no one sees you.",
'fall to':"To begin fighting or eating with great want.",
'die away':"To get less loud and then stop.",
'sing out':"To call out in a big voice.",
'ring out':"To sound in a big, clear way.",
'taken aback':"Surprised in a way that stops you for a moment.",
'keep an eye on':"To watch someone or something with care.",
'serve them right':"To be what they should get for what they did.",
'burst into tears':"To suddenly start to let tears fall.",
'turn up':"To make a light stronger or a sound bigger.",
'come and go':"To come to a place and leave it, again and again.",
}
