MEAN = {
'propose':"To ask someone to be your wife or husband.",
'boast':"To talk too proudly about yourself or what you have.",
'shilling':"A piece of old British money that was not worth much.",
'guinea':"An old amount of British money.",
'naught':"Nothing.",
'prim':"Very careful to be neat and proper. Too serious about what is polite.",
'perambulators':"An old word for small beds on wheels that a baby lies in and an adult pushes.",
'mistress':"The woman who is in charge of a home.",
'propriety':"Polite and correct ways of acting.",
'footer':"An old word that boys used for football.",
'forms':"Long seats for several people to sit on.",
'affected':"Acted as if you were or felt something, but not really.",
'inferior':"Lower than others. Not as good.",
'pirouette':"To turn round and round fast on one foot, like a dancer.",
'perplexing':"Hard to understand. It makes you not know what to think.",
'romp':"A lively, loud game.",
'lair':"A wild animal's home.",
'tedious':"Long and not interesting.",
'flamingo':"A big bird with long thin legs and a long neck.",
'wigwam':"A small round home that some Native American people made.",
'deftly':"Quickly and well, in a clever way.",
'surf':"The white water that comes up when the sea waves hit the land.",
'coinage':"Money made of metal.",
'upbraided':"Told someone angrily that they did wrong.",
'tornado':"A very strong wind that goes round and round.",
'crumpled':"Pressed into lines and not smooth.",
'brute':"A rough and unkind animal or person. Here, Mr. Darling uses it for the thing he wears at his neck.",
'sarcastic':"Saying something that is not what you mean, to hurt or laugh at someone.",
'placid':"Quiet and not easy to upset.",
'murmur':"A soft, low sound. \"Without a murmur\" means without saying anything against it.",
'doggedly':"Not giving up, even when it is hard.",
'cowardy':"A word that children say to laugh at someone who is afraid.",
'entreated':"Asked for something in a strong, sad way, wanting it very much.",
'breadwinner':"The person in a family who works to get the money for it.",
'beseechingly':"In a way that asks very strongly for help.",
'commotion':"A sudden loud, excited movement of many things.",
'mischievous':"Liking to do small bad things for fun.",
'appalled':"Very surprised and upset.",
'shudder':"A sudden shake of the body, from fear or a bad feeling.",
'draggled':"Wet and not clean, as if it was pulled along the ground.",
'conceit':"Too good an opinion of yourself.",
'aghast':"Very surprised and afraid.",
'thimble':"A small cover for the end of a finger, which you use when you make clothes with a needle.",
'primness':"A very proper and serious way of acting.",
'relenting':"Becoming less angry and less hard.",
'eaves':"The edges of a roof that come out past the walls.",
'cunning':"Clever in a way that fools other people.",
'darn':"To fix a hole in clothes with a needle and thread.",
'artfully':"In a clever way that fools other people.",
'topping':"An old word that people used for \"very good\".",
'ripping':"An old British word for \"very good\".",
'mantelpiece':"The shelf over the place where a fire burns in a room.",
'spires':"The tall pointed tops of church buildings.",
'tiffs':"Small fights with words.",
'rollicking':"Loud, happy and full of fun.",
'tingle':"A light feeling on the skin, as if small sharp points touched it.",
'disrespectful':"Not polite to someone who should get respect.",
'eerie':"Strange and making you a little afraid.",
'halo':"A ring of light round something.",
'topper':"A tall thing that a man wears on his head.",
'rasping':"Rough and hard on the ear.",
'ford':"A place where you can walk across a river because the water is not deep.",
'tremulously':"With a voice or body that moves a little from fear.",
'bewildered':"Not understanding and not sure what to do.",
'staggering':"Walking in a way that is not steady, as if about to fall.",
'seething':"Full of strong, busy movement, like water that is very hot.",
'debonair':"Happy, with a fine style, and sure of himself.",
'tattooed':"Marked on the skin with pictures that stay there.",
'genial':"Friendly and nice.",
'ruffian':"A rough man who may hurt people.",
'cadaverous':"Very thin, with a face that has lost its colour, like a dead body.",
'demeanour':"The way a person looks and acts.",
'lurches':"Moves suddenly to one side, not steadily.",
'baying':"The long, deep sound of big dogs or wolves.",
'plaintive':"Sad, and sounding like someone who is unhappy.",
'avast':"A word that men on ships use. It means \"stop\".",
'hempen':"Made from a strong plant that people use to make rope.",
'saluted':"Showed respect by raising a hand to the head, as soldiers do.",
'dastard':"A mean person who is afraid. It is an old word.",
'hack':"To cut roughly with hard hits.",
'fender':"A low metal wall in front of a fire.",
'sap':"The sweet liquid inside a tree or plant.",
'carousing':"Drinking and singing loudly with others and having a good time.",
'tweaked':"Gave a quick small pull and turn with the fingers.",
'mischiefed':"Hurt someone or made trouble for them. The author makes a verb from the word \"mischief\".",
'chandelier':"A light with many arms, which is put up high in a room.",
'rampagious':"Wild and loud.",
'stalking':"Following slowly and quietly, to catch something.",
'ahoy':"A call that men on ships use to get the attention of a boat or ship.",
'lubber':"A big, clumsy person. Here, a clumsy man on a ship.",
'hoist':"To pull something up high with effort.",
'puckered':"Pulled into small lines.",
'timidly':"In a way that shows you are afraid and not bold.",
'affrighted':"Made afraid. It is an old word.",
'bully':"An old friendly word for a good man. Captain Hook uses it for his men.",
'cozening':"Cheating or fooling someone. It is an old word.",
'blanch':"To turn white in the face.",
'henchmen':"Men who follow a bad leader and do what he says.",
'scaled':"Climbed up to the top of something high.",
'dazed':"Not able to think clearly, because something has hit you hard or surprised you.",
'pestilent':"Very bad and likely to hurt. It is an old word.",
'scouring':"Looking for something with great care in every part of a place.",
'fanciful':"Made up in the mind. Not real.",
'stave':"A long, strong stick.",
'buccaneers':"Men who attack ships at sea, especially long ago.",
'moidores':"Old gold money from Portugal.",
'brim':"The wide edge that sticks out round the bottom or top of something.",
'barque':"A ship that has sails. Here, it is the author's joking word for Peter's little boat.",
'rejoicings':"Showing great happiness together.",
'dodgy':"Not quite honest.",
'scandalised':"Very surprised and upset because something seems very wrong.",
'mast':"A tall post on a ship that holds up the cloth that the wind pushes.",
'grovelled':"Lay or moved on the ground in front of someone, to show you are lower than them.",
'cringe':"To bend down or move back from fear, or to be too ready to please.",
'titbits':"Small nice pieces of food.",
'guzzling':"Eating or drinking too much, and too fast.",
'recriminations':"Angry words that people say to each other, blaming each other.",
'diffidently':"In a way that is not sure of yourself.",
'homely':"Simple and comfortable, like home.",
'insinuated':"Said something in a hidden way, without saying it openly.",
'gratified':"Pleased and happy.",
'uproariously':"In a very loud and laughing way.",
'braves':"In this book, the fighting men of the Native American group.",
'descendants':"Children and their children, and all who come after a person in a family.",
'sublime':"Very great and fine.",
'stricken':"Hit hard by a strong feeling, such as fear.",
'insubordination':"Not doing what someone in charge tells you.",
'negligee':"A thin, light dress that a woman wears in bed.",
'noodles':"Silly people. It is an old British word.",
'blubbering':"Crying loudly.",
'cynicism':"A bitter feeling that people are not good or kind.",
'beseeching':"Asking very strongly.",
'coaxed':"Tried in a soft, kind way to make someone do something.",
'wiliness':"Cleverness in fooling other people.",
'stockade':"A strong wall of tall posts, used to keep out an enemy.",
'undulating':"Going up and down in a smooth way, like land with many low hills.",
'intimation':"A small sign or a hint of something.",
'stealthily':"Quietly and with great care, so that no one notices.",
'diabolical':"Very evil and cruel.",
'phlegmatic':"Quiet and not easily excited.",
'squatted':"Sat low, with the legs bent, close to the ground.",
'perfidious':"Not faithful. Not keeping the trust of others.",
'phalanx':"A close group of men who stand together to fight.",
'acquitted':"Acted. \"Acquit yourself\" means to act in a certain way.",
'beset':"With something all round you on every side.",
'pertinacity':"Not giving up. Holding on to a plan.",
'malignant':"Wanting to hurt others. Evil.",
'frenzy':"A time of wild anger or excitement that you cannot control.",
'pandemonium':"Wild noise and mix-up.",
'avidly':"In a way that shows you want it very much.",
'base':"Low and bad.",
'ironical':"Saying one thing but meaning the other way round.",
'trussing':"Tying up very hard.",
'addicted':"Doing something again and again, and not able to stop.",
'unmolested':"Not stopped or hurt.",
'vex':"To make someone upset or angry in a small way.",
'piteously':"In a way that makes people feel sorry.",
'indignity':"Something that makes you feel low and badly treated.",
'harpsichord':"An old thing that makes music when you press its keys.",
'virulent':"Very strong and bad. It can hurt you.",
'guttered':"Gave a small, weak light and then went out.",
'conjurers':"People who do clever magic for others to watch.",
'tottering':"Walking in a way that is not steady.",
'astir':"Up and moving about.",
'obliterated':"Taken away completely so that it cannot be seen.",
'belay':"A word that men on ships use. It means \"stop\".",
'brig':"A ship with two tall posts for sails.",
'mangled':"Badly hurt and broken up.",
'immune':"Safe from something. It cannot hurt you.",
'bulwarks':"The sides of a ship above the floor, like a wall.",
'miasma':"Bad air that is not good for you.",
'slouch':"A way of walking or standing with the shoulders bent forward and little effort.",
'portals':"Large doors.",
'tallow':"A hard fat from animals, used to make lights.",
'doublet':"A tight coat that men wore long ago.",
'sleuthhound':"A dog that finds people by following where they went.",
'bacchanalian':"Wild and loud, with much drinking.",
'buffer':"Something or someone that comes between two sides and takes the hit.",
'intrinsic':"Being part of what something truly is.",
'abject':"In a sad, weak and afraid state.",
'carrion':"A dead body. Here, the author uses it for a dead man.",
'brazenly':"Openly, and not caring what others think.",
'hearten':"To make someone feel braver and stronger.",
'quailing':"Moving back in fear.",
'unstrung':"Made weak and afraid.",
'quarry':"A person or animal that someone is trying to catch.",
'parried':"Stopped a hit from a sword by moving his own sword.",
'feint':"A move that looks like it is going one way but is not, to fool an enemy.",
'nautical':"To do with ships and the sea.",
'bluff':"Rough and open in the way of speaking.",
'strident':"Loud and unpleasant to hear.",
'pettishly':"In a childish way, because you are upset.",
'jaggy':"Sharp and rough to touch. It is a Scottish word.",
'quixotic':"Wanting to do great and good things in a way that is not wise.",
'brats':"Children who act badly. The author uses it in a playful way.",
'cipher':"A person who does not count at all.",
'mauve':"A soft light colour, between blue and red.",
'halfpennyworth':"A very small amount, as much as half of a small British coin can buy.",
'diversions':"Things that make people happy and pass the time. Games.",
'receding':"Going away from you.",
'artful':"Clever in a way that fools other people.",
'banns':"A public notice in church that two people will be married.",
'hew':"To cut wood with a heavy tool.",
'tomahawks':"Small weapons with a sharp edge, used by some Native American people.",
'fibre':"A thin part of a plant, used to make string.",
'succulence':"The soft, tasty quality of food that has much juice.",
'petulantly':"In a childish way, like a child who does not get what he wants.",
'quacking':"Talking in a loud, silly way.",
'rent':"Pulled apart so that there is a gap.",
'cat':"A tool for hitting people, with nine tails.",
'accurst':"Having a bad wish put on it, so that bad things happen. It is an old spelling.",
'saluted':"Showed respect by raising a hand to the head, as soldiers do.",
}
