words = [
("hearthrug","noun","A small carpet in front of a fireplace."),
("cinders","plural noun","Small pieces of burnt coal or wood left after a fire."),
("tapestry","noun","A heavy cloth with a picture woven into it, hung on a wall."),
("embroidered","adjective","Decorated with a picture made with needle and thread."),
("fantastically","adverb","In a very strange or surprising way."),
("turret","noun","A small tower on the corner of a castle."),
("grate","noun","The metal frame that holds the fire in a fireplace."),
("obsequious","adjective","Too eager to please a person who has power over you."),
("servile","adjective","Acting like a servant who does whatever he is told, without any pride."),
("salaam","noun","In India, a low bow with the hand at the head, to show respect."),
("sturdy","adjective","Strong and solid."),
("haughtily","adverb","In a proud way that shows you think you are better than others."),
("scullery","noun","A small room next to a kitchen where pots and plates are washed. A scullery-maid is the lowest kitchen servant."),
("imperious","adjective","Giving orders in a proud way, as if you were a queen."),
("stoutly","adverb","In a firm and brave way."),
("indignantly","adverb","In an angry way, because something seems unfair."),
("disdainfully","adverb","In a way that shows you think something is not good enough for you."),
("vexed","adjective","Annoyed."),
("tracts","plural noun","Short religious papers that people give out to teach about religion."),
("humiliation","noun","The feeling of shame when you have been made to look foolish."),
("unrestrainedly","adverb","Without trying to stop yourself."),
("subservient","adjective","Too ready to obey other people."),
("rustic","noun","A person from the country who has simple ways."),
("totter","verb","To walk with weak, unsteady steps."),
("homely","adjective","Simple and plain, like an ordinary home. Here it means friendly and without pride."),
("sentiment","noun","A feeling."),
("substantial","adjective","Large in amount; filling."),
("incredulously","adverb","In a way that shows you cannot believe something."),
("treacle","noun","A thick, sweet, dark liquid used on food."),
("victuals","plural noun","Food. This is an old word."),
("pinafore","noun","A piece of clothing worn over a dress to keep it clean."),
("marmalade","noun","A sweet food made from oranges, put on bread."),
("coax","verb","To get someone to do something by being gentle and kind."),
("shrubbery","noun","A place where many bushes are planted."),
("ivy","noun","A climbing plant with dark green leaves that grows up walls."),
("surly","adjective","Bad-tempered and rude."),
("crustily","adverb","In a bad-tempered and rude way."),
("fledgling","noun","A young bird that has just learned to fly."),
("brood","noun","A group of young birds that were born together."),
("conceited","adjective","Too proud of yourself."),
("meddlin","noun","Taking part in things that are not your business. The book writes it as meddlin'."),
("wench","noun","An old word for a girl or young woman."),
("mester","noun","A Yorkshire way to say 'master' or 'mister'."),
("nowt","pronoun","A Yorkshire way to say 'nothing'."),
("forrad","adjective","A Yorkshire way to say 'forward'. Here it means too early."),
("blunt","adjective","Saying what you think in a plain way, without trying to be polite."),
("warrant","verb","To say you are sure of something. 'I warrant' means 'I am sure'."),
("uncompanionable","adjective","Not wanting to be friendly or talk."),
("meddlesome","adjective","Putting yourself into things that are not your business."),
]
paras = [
(5,12,"The native servants she had been used to in India",
 "Mary is surprised that Martha talks to her in such a free way. In India servants did not do that.",
 "Mary listened to Martha with a serious, puzzled look. The servants from India that she had been used to were not at all like this. They were too eager to please, and always did what they were told. They did not dare to talk to their masters as if they were equals. They made salaams and called them 'protector of the poor' and names like that. Indian servants were ordered to do things, and not asked. It was not the custom to say 'please' and 'thank you', and Mary had always slapped her Ayah in the face when she was angry. She wondered a little what this girl would do if someone slapped her in the face. Martha was a round, rosy girl who looked good-natured. But she had a strong way about her. It made Mistress Mary wonder if she might even slap back, if the person who hit her was only a little girl.",
 ["native servants","obsequious","servile","salaams","slapped","sturdy"]),
(5,49,"It had not been the custom that Mistress Mary should do anything but stand",
 "Mary begins to see that life at Misselthwaite will teach her new things. Martha is not a trained servant.",
 "It had not been the custom for Mistress Mary to do anything but stand and let herself be dressed like a doll. But before she was ready for breakfast, she began to think that her life at Misselthwaite Manor would end by teaching her a number of new things. These were things like putting on her own shoes and stockings, and picking up things that she dropped. If Martha had been a well-trained maid for a fine young lady, she would have been more ready to obey and be respectful. She would have known that it was her job to brush hair, and button boots, and pick things up and put them away. But Martha was only an untrained country girl from Yorkshire. She had grown up in a cottage on the moor, with a crowd of little brothers and sisters. They had never dreamed of doing anything but looking after themselves and the younger ones, who were babies in arms or just learning to walk.",
 ["subservient","rustic","moorland","swarm","totter"]),
(5,113,"I’ve knowed him ever since he was a fledgling",
 "Ben Weatherstaff says he has known the robin since it was a baby bird. They became friends when the bird was weak.",
 "'Yes, he will. I have known him ever since he was a young bird. He came out of the nest in the other garden. When he first flew over the wall, he was too weak to fly back for a few days, and we became friendly. When he went over the wall again, the rest of the young birds had gone. He was lonely, and he came back to me.'",
 ["knowed","fledgling","brood"]),
]
sents = [
("If there was a grand Missus at Misselthwaite I should never have been",
 "If there were a fine lady at Misselthwaite, I would never have been even a low housemaid.",
 "'If there was ... I should never have been' mixes a present case with a past result: it says that because there is no lady, Martha got the job."),
("it’s time tha’ should learn. Tha’ cannot begin younger",
 "It is time that you learned. You cannot begin at a younger age.",
 "'It's time (that) + subject + should + verb' means it is the right time to do something now; 'tha'' is Yorkshire for 'you'."),
("If Mary Lennox had been a child who was ready to be amused",
 "If Mary Lennox had been a child who wanted to be amused, she might have laughed at Martha's readiness to talk.",
 "'If + had been, would perhaps have + past participle' is a past case that did not happen: Mary was not ready to be amused, so she did not laugh."),
("I can’t abide to see good victuals go to waste",
 "I cannot stand to see good food wasted.",
 "'can't abide' means 'cannot bear'; 'see + noun + go to waste' is a pattern: see something happen. Martha uses 'victuals', an old word for food."),
("Dang me if he hasn’t took a fancy to thee",
 "I am sure that he has begun to like you.",
 "'Dang me if he hasn't' is a Yorkshire way to say 'I am sure he has'; 'took' is used for 'taken' and 'thee' means 'you'."),
]
phrases = [
("pick up","phrasal verb","To lift something from the ground or a table.",["picking up","picked up"],"picking up things she let fall"),
("wait on","phrasal verb","To serve someone, doing things for them.",["waiting on","wait on"],"wait on you a bit"),
("go to waste","idiom","To be thrown away and not used.",None,"I can’t abide to see good victuals go to waste"),
("put on","phrasal verb","To dress yourself in clothes.",["putting on"],"putting on her own shoes and stockings"),
("get on with","phrasal verb","To have a good friendly way with someone.",["get on with"],"if you know how to get on with ’em"),
("burst out","phrasal verb","To suddenly make a sound or begin to do something.",["burst out into","burst into"],"burst out into a scrap of a song"),
("make friends with","phrase","To start to be a friend of someone.",["make friends with","made friends with"],"He’s made up his mind to make friends with thee"),
("take a fancy to","idiom","To begin to like someone or something.",["took a fancy to"],"he hasn’t took a fancy to thee"),
("make up one's mind","idiom","To decide.",["made up his mind","made up her mind","make up his mind"],"He’s made up his mind to make friends with thee"),
("walk off","phrasal verb","To leave and walk away.",["walked off"],"walked off, without even glancing at her"),
("burst into","phrase","To begin suddenly to cry or laugh.",["burst into"],"burst into passionate sobbing"),
]
