words = [
("clergyman","noun","A man whose job is to lead worship in a church."),
("shabby","adjective","Old and worn, not looking good."),
("quarreling","present participle","Having angry talks with other people."),
("snatching","present participle","Taking something quickly and roughly."),
("untidy","adjective","Not neat; in a mess."),
("impudent","adjective","Rude and not showing respect."),
("tease","verb","To say funny or unkind things to someone to make them angry."),
("rockery","noun","A garden bed made with piles of stones and small plants."),
("contrary","adjective","Doing the opposite of what other people want."),
("scorn","noun","A strong feeling that someone is bad or not worth anything."),
("desolate","adjective","Empty and sad; with nobody there."),
("hunchback","noun","A person with a back that is bent and has a lump on it."),
("stony","adjective","Showing no feeling on the face."),
("pityingly","adverb","In a way that shows you feel sorry for someone."),
("voyage","noun","A long trip by ship."),
("absorbed","adjective","Giving all your attention to something."),
("housekeeper","noun","A person whose job is to run a big house and manage the other servants."),
("stout","adjective","Fat and strong."),
("mantle","noun","A loose coat without sleeves, worn over other clothes."),
("fringe","noun","An edge made of many small threads or strings that hang down."),
("bonnet","noun","A hat for women that is tied under the chin."),
("sallow","adjective","Having a pale yellow colour, not healthy."),
("pettish","adjective","Easily made angry about small things."),
("marred","adjective","Spoiled. In this book a Yorkshire word for a child who is spoiled and bad-tempered."),
("discomfited","adjective","Feeling uncomfortable and not sure what to do."),
("gloomy","adjective","Dark and sad."),
("moor","noun","A large area of high, open land with rough grass and no trees."),
("crooked","adjective","Not straight; bent."),
("dreary","adjective","Dull and sad."),
("frock","noun","A girl's or woman's dress."),
("poking","present participle","Pushing into places to look at things that are not your business."),
("involuntary","adjective","Done without thinking or wanting to."),
]
paras = [
(3,3,"The English clergyman was poor and he had five children",
 "Mary stays with a poor clergyman and his children. She is rude to them and they give her a nickname that makes her angry.",
 "Mary knew she was not going to stay at the English clergyman's house, where she was taken at first. She did not want to stay. The English clergyman was poor and had five children, nearly all the same age. They wore old clothes and were always quarreling and taking toys from each other. Mary hated their untidy bungalow. She was so unpleasant to them that after the first day or two nobody would play with her. By the second day they had given her a nickname that made her very angry.",
 ["clergyman","shabby","quarreling","snatching","untidy","nickname"]),
(3,20,"She was a stout woman, with very red cheeks and sharp black eyes",
 "Mary goes to England with an officer's wife. Mr Craven's housekeeper, Mrs Medlock, meets her in London.",
 "Mary made the long trip to England by ship, with an officer's wife. The woman was taking her own children to leave them at a boarding-school. She thought only about her own little boy and girl. She was rather glad to give Mary to the woman that Mr. Archibald Craven sent to meet her in London. This woman was his housekeeper at Misselthwaite Manor, and her name was Mrs. Medlock. She was a fat woman, with very red cheeks and sharp black eyes. She wore a very purple dress, a black silk coat with a hanging black fringe on it, and a black bonnet with purple velvet flowers that stuck up and shook when she moved her head. Mary did not like her at all. But Mary very seldom liked people, so there was nothing special in that. Also, it was very clear that Mrs. Medlock did not think much of Mary.",
 ["voyage","absorbed","housekeeper","stout","mantle","fringe","bonnet","remarkable"]),
(3,39,"it’s a grand big place in a gloomy way",
 "Mrs Medlock tells Mary about Misselthwaite Manor. It is a very big old house at the edge of the moor, with many rooms shut up.",
 "'It is a big, fine place in a sad and dark way,' Mrs. Medlock said, 'and Mr. Craven is proud of it in his way. And that is sad enough, too. The house is six hundred years old and it is at the edge of the moor. There are nearly a hundred rooms in it, though most of them are shut up and locked. There are pictures and fine old furniture and things that have been there for ages. There is a big park round it, and gardens, and trees with branches hanging down to the ground, some of them.' She stopped and took another breath. 'But there is nothing else,' she ended suddenly.",
 ["grand","gloomy","moor","trailing"]),
]
sents = [
("If she were not so sallow and had a nicer expression",
 "If she were not so pale and yellow, and if she looked nicer, her face would be quite good.",
 "'If she were not ...' is an imagined case, so 'were' is used; the second part says her face is quite good in the real world."),
("What you’re to be kept at Misselthwaite Manor for I don’t know",
 "I do not know why they are keeping you at Misselthwaite Manor.",
 "The word order is not the usual one: 'what ... for' means 'why', and the sentence means 'I don't know why you are to be kept at Misselthwaite Manor'; 'are to be kept' tells what is planned."),
("it seemed quite natural that the rain should have begun to pour down",
 "It seemed natural to Mary that the rain had begun to pour down.",
 "'seemed natural that ... should have begun' uses 'should have + past participle' after a word of feeling, to say that something happened and was not strange."),
("If the pretty wife had been alive she might have made things cheerful",
 "If the pretty wife had been alive, she could perhaps have made things happier.",
 "'If + had been, might have + past participle' is about the past: the wife was not alive, so it did not happen."),
]
phrases = [
("stand no nonsense","idiom","To not allow silly or bad behaviour.",["stand no nonsense"],"stand no nonsense from young ones"),
("shut oneself up","phrasal verb","To go into a room or a place and stay there alone.",["shuts himself up","shut himself up"],"he shuts himself up in the West Wing"),
("set out","phrasal verb","To start a trip.",["set out"],"they set out on their journey to Yorkshire"),
("in spite of","phrase","Although something is true; when something does not stop you.",["in spite of herself"],"Mary had begun to listen in spite of herself"),
("go on","phrasal verb","To keep talking or doing something.",["went on"],"after taking a breath, she went on"),
("hand down","phrasal verb","To pass something to a younger person in the family.",["handed down"],"She hasn't handed much of it down"),
("make faces","idiom","To show a funny or unkind look by moving your face.",["made faces"],"made faces and sang and laughed"),
]
