words = [
("disagreeable","adjective","Not pleasant. Unkind and not nice to be with."),
("sour","adjective","Unhappy and bad-tempered. Here it describes a look on the face."),
("amuse","verb","To have fun, or to make time pass in a happy way."),
("gay","adjective","Happy and full of fun. This is an old use of the word."),
("ayah","noun","In India, a woman servant who takes care of a child."),
("sahib","noun","In India, a word of respect. 'Mem Sahib' is what servants call a European woman. 'Missie Sahib' is used for a girl."),
("sickly","adjective","Often ill, and not strong."),
("fretful","adjective","Unhappy, and crying or complaining a lot."),
("toddling","present participle","Walking with short, unsteady steps, as a very small child does."),
("tyrannical","adjective","Using power over other people in a hard and unkind way."),
("governess","noun","A woman who is paid to teach children at their home."),
("stammered","past-tense verb","Spoke with many stops and repeated sounds, because of fear."),
("passion","noun","A sudden, wild anger."),
("slunk","past-tense verb","Moved quietly and secretly, because of fear or shame."),
("ashy","adjective","Pale grey, like ash. Here it describes faces of frightened people."),
("veranda","noun","A covered place with a floor along the side of a house, open to the air."),
("hibiscus","noun","A plant with big, bright flowers that grows in hot countries."),
("scarlet","adjective","Bright red."),
("blossom","noun","A flower on a plant or a tree."),
("disdaining","present participle","Showing that you think something is not good enough for you."),
("imploringly","adverb","In a way that begs for help."),
("wailing","noun","A long, loud cry because of pain or sadness."),
("quarters","plural noun","The rooms or buildings where a group of people live."),
("wrung","past-tense verb","Twisted and pressed together. 'Wrung her hands' shows great worry or sadness."),
("cholera","noun","A very bad illness that spreads fast and can kill people."),
("bungalow","noun","A house with only one floor, often in a hot country."),
("panic","noun","A sudden, strong fear that makes people act without thinking."),
("bewilderment","noun","The state of being very confused."),
("drowsy","adjective","Sleepy."),
("hastily","adverb","Very quickly, in a hurry."),
("rustling","present participle","Making soft sounds like dry leaves moving."),
("matting","noun","A floor covering woven from plants."),
("gliding","present participle","Moving smoothly and quietly."),
("compound","noun","The land with a fence or wall around a group of buildings."),
("desolation","noun","A sad, empty place where everyone has gone."),
("neglected","adjective","Not looked after."),
]
paras = [
(2,1,"everybody said she was the most disagreeable-looking child ever seen",
 "Mary was an unpleasant-looking, selfish child. Her mother did not want her, and the servants did what she said.",
 "When Mary Lennox was sent to Misselthwaite Manor to live with her uncle, everybody said that she was the child with the most unpleasant look they had ever seen. It was true, too. She had a little thin face and a little thin body, thin light hair and a sour look. Her hair was yellow, and her face was yellow, because she had been born in India and had always been ill in one way or another. Her father had had a job under the English Government. He had always been busy and ill himself. Her mother had been a great beauty who cared only to go to parties and have fun with happy people. She had not wanted a little girl at all. When Mary was born, she gave her to an Ayah to look after. The Ayah was made to understand that if she wanted to please the Mem Sahib, she must keep the child out of sight as much as possible. So when Mary was a sick, crying, ugly baby, she was kept out of the way. When she was a sick, crying child just learning to walk, she was kept out of the way too. She never remembered knowing any faces well except the dark faces of her Ayah and the other servants from India. They always did what she said and gave her her own way in everything, because the Mem Sahib would be angry if Mary's crying disturbed her. So by the time she was six years old, she was as selfish and bossy a little pig as ever lived. The young English governess who came to teach her to read and write did not like her, and left after three months. When other governesses came to try to take the job, they always went away in a shorter time than the first one. So if Mary had not chosen to really want to learn to read books, she would never have learned her letters at all.",
 ["disagreeable-looking","sour expression","beauty","amuse","gay","Ayah","Mem Sahib","sickly","fretful","toddling","tyrannical","governess"]),
(2,17,"Mary alternately cried and slept through the hours",
 "Mary is alone in the house during the second day of the sickness. She drinks some wine and falls asleep.",
 "During the confusion of the second day, Mary hid in the nursery, and everyone forgot her. Nobody thought of her and nobody wanted her. Strange things happened that she knew nothing about. Mary cried and then slept, and cried and then slept again, through the hours. She only knew that people were ill and that she heard strange and frightening sounds. Once she went quietly into the dining-room and found it empty. But a meal that was only half finished was on the table. The chairs and plates looked as if the people had pushed them back in a hurry when they got up suddenly for some reason. The child ate some fruit and biscuits. She was thirsty, so she drank a glass of wine that stood nearly full. It was sweet, and she did not know how strong it was. Very soon it made her very sleepy. She went back to her nursery and shut herself in again. She was afraid because of the cries she heard in the huts and the sound of feet hurrying. The wine made her so sleepy that she could hardly keep her eyes open. She lay down on her bed and knew nothing more for a long time.",
 ["alternately","hastily","diners","intensely","drowsy","scarcely"]),
]
sents = [
("too panic-stricken to think of a little girl no one was fond of",
 "Everyone was so afraid that they could not think of a little girl whom nobody loved.",
 "'too + adjective + to + verb' means 'so ... that they could not'; 'no one was fond of' is a relative clause with 'whom' or 'that' left out."),
("You ought to have gone to the hills two weeks ago",
 "You should have gone to the hills two weeks ago, but you did not.",
 "'ought to have + past participle' says what was the right thing to do in the past, but it was not done."),
("who was made to understand that if she wished to please the Mem Sahib",
 "Someone told the Ayah clearly that if she wanted to please the Mem Sahib, she must keep the child out of sight.",
 "'was made to understand' is a passive form: someone made her know it; 'if she wished ... she must' gives the rule the Ayah had to follow."),
]
phrases = [
("break out","phrasal verb","To start suddenly. It is used for fires, wars and illnesses.",["broke out","broken out"],"The cholera had broken out in its most fatal form"),
("run away","phrasal verb","To leave a place quickly, because you are afraid or do not want to be there.",["ran away","run away"],"others had run away in terror"),
("give up","phrasal verb","To stop doing something, or to leave it.",["gave up"],"she gave up her place in three months"),
("hand over","phrasal verb","To give something or someone to another person.",["handed over","handed her over"],"she handed her over to the care of an Ayah"),
("out of sight","phrase","Where nobody can see.",None,"keep the child out of sight as much as possible"),
("find out","phrasal verb","To learn a fact that you did not know.",["found out"],"Mary found out that she had neither father nor mother left"),
]
