words = [
("arched","past-tense verb","Made a curved shape like a bridge. Here the sky curved high over the moor."),
("fleece","noun","The wool of a sheep. Here it describes soft white clouds."),
("dialect","noun","A way of speaking that is special to one part of a country."),
("soart","noun","A Yorkshire way to say 'sort'. 'Nowt o' th' soart' means 'nothing of the sort'."),
("wistfully","adverb","In a sad way, wishing for something you cannot have."),
("reflectively","adverb","In a thoughtful way."),
("vixon","noun","A Yorkshire way to say 'vixen', a female fox. Martha's mother uses it for a bad-tempered girl."),
("daffydowndilly","noun","An old name for a daffodil, a yellow spring flower."),
("crocus","noun","A small spring flower that comes up from the ground early in the year."),
("snowdrop","noun","A small white flower that comes up in late winter."),
("pert","adjective","Quick, lively and not afraid."),
("slyly","adverb","In a secret way that shows you know something others do not."),
("perennial","adjective","A perennial plant lives for more than two years and grows again each spring."),
("flirted","past-tense verb","Moved quickly and with fun, to be noticed."),
("mole","noun","A small animal that lives under the ground and digs tunnels."),
("rusty","adjective","Covered with the red-brown coating that forms on old iron."),
]
paras = [
(8,4,"The rainstorm had ended and the gray mist and clouds had been swept away",
 "The storm is over and the sky is a deep, bright blue. Mary has never seen a sky like it.",
 "The rainstorm had ended. The wind had swept away the gray mist and clouds in the night. The wind itself had stopped, and a bright, deep blue sky curved high over the moorland. Mary had never dreamed of a sky so blue. In India the skies were hot and blazing. This sky was a deep cool blue that almost seemed to sparkle like the water of a lovely lake with no bottom. Here and there, high up in the curved blueness, small clouds of snow-white wool floated. The moor, which went on a long way, looked softly blue. It no longer looked dark purple-black or awful gray.",
 ["rainstorm","arched","fleece","far-reaching","dreary"]),
(8,56,"It was something like a ring of rusty iron or brass",
 "Mary sees something in the soil and picks it up. It is an old key.",
 "Mary looked at the hole. She did not really know why it was there. As she looked, she saw something almost buried in the newly dug soil. It was something like a ring of rusty iron or brass. When the robin flew up into a tree nearby, she put out her hand and picked up the ring. It was more than a ring. It was an old key, and it looked as if it had been buried for a long time.",
 ["rusty","brass","buried"]),
]
sents = [
("It goes off in a night like it was pretendin’",
 "The storm goes away in one night, as if it were pretending it had never been here.",
 "'like it was pretendin'' is Martha's Yorkshire talk for 'as if it were pretending'; 'had never been' is past perfect, looking back from the pretending."),
("Tha’s never used tha’ legs since tha’ was born, it seems to me",
 "It seems to me that you have never used your legs since you were born.",
 "'Tha's never used' is Yorkshire for 'You have never used'; 'it seems to me' is an extra comment placed at the end."),
("He knows every cabbage stump in th’ gardens, let alone th’ people",
 "He knows every cabbage stump in the gardens, and he knows the people even better.",
 "'let alone' adds a second thing that is even more sure than the first: if he knows the cabbage stumps, he surely knows the people."),
("nothing in the world would make her put out her hand toward him",
 "The robin knew that nothing would make Mary put out her hand to him.",
 "'knew (that) nothing ... would make her' uses 'would' for the future from a past point of view; 'that' is left out."),
]
phrases = [
("sit up","phrasal verb","To move from lying down to a sitting position.",["sat up","sitting up"],"sitting up on her heels"),
("go off","phrasal verb","To leave, or to end.",["goes off","went off"],"It goes off in a night"),
("bring to one's senses","idiom","To make someone stop being foolish.",["brought me to my senses"],"it brought me to my senses in a minute"),
("let alone","phrase","Used to say that the next thing is even more true than the first.",None,"let alone th’ people"),
("dig up","phrasal verb","To take out of the ground by digging.",["dig up","digging up"],"trying to dig up a mole"),
("pick up","phrasal verb","To lift something from the ground.",["picked up"],"she put out her hand and picked the ring up"),
("walk away","phrasal verb","To go away on foot.",["walked away"],"She walked away, slowly thinking"),
("jump for joy","idiom","To be very happy.",None,"I just jump for joy when I’m crossin’ th’ moor"),
]
