words = [
("glistening","adjective","Shining because it is wet."),
("waterproof","noun","A coat or a cover that keeps water out. Here it is a coat made to keep off rain."),
("lulled","past-tense verb","Made calm and sleepy by a soft, even sound."),
("stationmaster","noun","The person in charge of a railway station."),
("tha","pronoun","A Yorkshire way to say 'you'. In the book it is often written tha'."),
("thee","pronoun","A Yorkshire way to say 'you' (as an object), used to one person."),
("thy","determiner","A Yorkshire and old way to say 'your'."),
("th","determiner","A short Yorkshire way to say 'the', written th' in the book."),
("aye","interjection","Yes. It is used in Yorkshire."),
("enow","adjective","A Yorkshire way to say 'enough'."),
("browt","past-tense verb","A Yorkshire way to say 'brought'."),
("brougham","noun","A closed carriage pulled by a horse, with four wheels."),
("footman","noun","A man servant who helps people in and out of a carriage and opens doors."),
("burly","adjective","Big, strong and heavy."),
("coachman","noun","A man whose job is to drive a carriage pulled by horses."),
("cushioned","adjective","Made soft with pillows or pads."),
("timid","adjective","Easily frightened; not brave."),
("whitewashed","adjective","Painted white with a cheap white paint made of lime and water."),
("vicarage","noun","The house where the vicar, a church leader, lives."),
("dense","adjective","Thick and hard to see through."),
("jolt","noun","A sudden rough movement."),
("expanse","noun","A very large, wide, open area."),
("singular","adjective","Strange; not like other things."),
("heather","noun","A low wild plant with small purple flowers that grows on moors."),
("gorse","noun","A wild bush with sharp thorns and yellow flowers."),
("broom","noun","A wild bush with long thin stems and yellow flowers. Here it is a plant, not a tool for sweeping."),
("bleak","adjective","Cold, bare and without comfort."),
("lodge","noun","A small house at the gate of a big house or a park."),
("avenue","noun","A wide road with trees on both sides, which leads to a big house."),
("vault","noun","A roof shaped like an arch. Here the trees make it look like the roof of a long dark room."),
("ramble","verb","To spread out in a loose, uneven way, as a big house does."),
("panels","plural noun","Flat pieces of wood set in a door or a wall."),
("studded","adjective","Covered with small round pieces of metal."),
("portraits","plural noun","Pictures of people."),
("armor","noun","A metal suit that soldiers wore in the past to keep safe in a fight."),
("husky","adjective","Low and rough, like a voice from a dry throat."),
("unceremoniously","adverb","Quickly and without being polite."),
]
paras = [
(4,6,"“I see tha’s got back,” he said",
 "The stationmaster speaks to Mrs Medlock in Yorkshire talk. Mary cannot easily understand it.",
 "'I see you have come back,' he said. 'And you have brought the young one with you.'",
 ["tha’s","browt","th’","’un","thee"]),
(4,16,"The carriage lamps shed a yellow light on a rough-looking road",
 "The carriage reaches the moor in the dark. Mary hears the wind, which makes a strange sound.",
 "The lamps of the carriage threw a yellow light on a rough-looking road. The road seemed to be cut through bushes and low plants. These ended in a great wide area of dark that seemed to spread out in front of them and all around them. A wind was rising and making a strange, wild, low, rushing sound.",
 ["shed","expanse","singular"]),
(4,27,"The entrance door was a huge one made of massive, curiously shaped panels",
 "Mary enters the great hall of Misselthwaite Manor. It is so dark that she feels small and lost.",
 "The door at the front was a huge one. It was made of heavy, oddly shaped pieces of oak, with big iron nails in them, and it was held together with great iron bars. It opened into an enormous hall. The hall was so dimly lit that the faces in the pictures on the walls, and the figures in the metal suits, made Mary feel she did not want to look at them. She stood on the stone floor and looked like a very small, strange, black figure. She felt as small and lost and strange as she looked.",
 ["massive","panels","studded","portraits","armor","dimly"]),
]
sents = [
("she was not at all a timid child and she was not exactly frightened",
 "Mary was not a shy child at all, and she was not really afraid.",
 "'not at all' and 'not exactly' make the meaning softer: she was not afraid, but she did feel something was strange."),
("it seemed quite proper that other people should wait on one",
 "It seemed right to Mary that other people should serve her.",
 "'should' here means it is the right thing to do; 'one' means 'a person like her'; 'wait on' means 'serve'."),
("the trees (which nearly met overhead) made it seem as if they were driving",
 "The trees nearly touched each other above them, and it seemed as if they were driving through a long dark room.",
 "'(which nearly met overhead)' is a side comment about the trees; 'made it seem as if ...' means 'gave the feeling that ...'."),
("So long as I know what’s expected of me, I can manage",
 "I can do the job if I know what they want me to do.",
 "'So long as' means 'if' (only if); 'what's expected of me' is a noun clause meaning 'what people want me to do'."),
]
phrases = [
("cheer up","phrasal verb","To become happier.",["cheered up"],"Mrs. Medlock cheered up very much over her tea"),
("drive off","phrasal verb","To go away in a car or carriage.",["drove off"],"they drove off, the little girl found herself seated"),
("look out","phrasal verb","To look through a window or a door to the outside.",["looked out"],"Look out of the window in about ten minutes"),
("on and on","phrase","Without stopping, for a long time.",None,"On and on they drove through the darkness"),
("catch sight of","idiom","To see something for a short time.",["caught sight of"],"she first caught sight of a light"),
("at all events","idiom","In any case; whatever happens.",None,"We shall get a good cup of tea after a bit, at all events"),
]
