words = [
("torrents","plural noun","Very heavy rain. 'In torrents' means in great amounts."),
("moithered","adjective","A Yorkshire word for confused and upset by too much noise or work."),
("litter","noun","A group of baby animals born at the same time to one mother."),
("tamed","past-tense verb","Made an animal gentle so that it is not afraid of people."),
("resent","verb","To feel angry about something because it seems unfair."),
("collie","noun","A kind of dog with long hair, used for looking after sheep."),
("perplexed","adjective","Confused and not sure what to do or think."),
("luxurious","adjective","Very comfortable and rich."),
("pewter","noun","A grey metal used to make plates and cups."),
("abundant","adjective","More than enough; plenty."),
("romping","noun","Playing in a noisy, rough way."),
("gallery","noun","A long room or passage, here with pictures on the walls."),
("satin","noun","A smooth, shiny cloth."),
("velvet","noun","A soft cloth with a thick, smooth surface."),
("ruffs","plural noun","Stiff, round collars with many folds, worn around the neck in the past."),
("brocade","noun","A rich cloth with a raised pattern woven into it."),
("inlaid","adjective","Decorated with small pieces of another material set into the surface."),
("mantel","noun","The shelf above a fireplace."),
("cabinet","noun","A piece of furniture with doors and shelves, for keeping things."),
("ivory","noun","The hard white material from the tusks of elephants."),
("mahout","noun","A man who rides and looks after an elephant in India."),
("palanquin","noun","A covered seat or bed that is carried on poles by people, or on an animal."),
("cuddled","past-tense verb","Held close together to be warm."),
("whine","noun","A long, high, unhappy sound."),
("muffled","adjective","Made less loud, so that it is hard to hear."),
]
paras = [
(7,17,"Mary did not ask where the library was",
 "Mary decides to look for the library by herself. The servants live well while their master is away.",
 "Mary did not ask where the library was, because a new idea suddenly came to her. She decided to go and find it herself. She was not worried about Mrs. Medlock. Mrs. Medlock always seemed to be in her comfortable housekeeper's sitting-room downstairs. In this strange place, one hardly ever saw anyone at all. In fact, there was no one to see but the servants. When their master was away, they lived a rich and comfortable life below the stairs. There was a huge kitchen with shining brass and pewter hanging in it, and a large servants' hall. Four or five big meals were eaten there every day, and there was a lot of noisy, happy playing when Mrs. Medlock was out of the way.",
 ["inspired","made up her mind","luxurious","pewter","abundant","romping"]),
(7,22,"She opened the door of the room and went into the corridor",
 "Mary walks through the corridors and looks at the pictures in the gallery. She feels the faces are looking at her.",
 "Mary opened the door of the room and went into the corridor, and then she began her wanderings. It was a long corridor, and it branched into other corridors. It led her up short flights of steps which went up to others again. There were doors and doors, and there were pictures on the walls. Sometimes they were pictures of dark, strange landscapes, but most often they were portraits of men and women in strange, grand clothes made of satin and velvet. She found herself in one long gallery whose walls were covered with these portraits. She had never thought there could be so many in any house. She walked slowly down this place and stared at the faces, which also seemed to stare at her. She felt as if they were wondering what a little girl from India was doing in their house. Some were pictures of children. There were little girls in thick satin frocks which reached to their feet and stood out about them. There were boys with puffed sleeves and lace collars and long hair, or with big ruffs around their necks. She always stopped to look at the children and to wonder what their names were, and where they had gone, and why they wore such odd clothes. There was a stiff, plain little girl rather like herself. She wore a green brocade dress and held a green parrot on her finger. Her eyes had a sharp, curious look.",
 ["branched","landscapes","portraits","satin","velvet","puffed","ruffs","brocade"]),
]
sents = [
("She had never been taught to ask permission to do things",
 "Nobody had ever taught Mary to ask if she could do things.",
 "'had never been taught' is a passive past perfect: the teaching never happened before that time; 'to ask permission' is an infinitive."),
("Since so many rooms had been built, people must have lived in them",
 "Because so many rooms were built, people must have lived in them.",
 "'must have + past participle' is a guess about the past; 'Since' here means 'because'."),
("It was not until she climbed to the second floor that she thought",
 "Only after she climbed to the second floor did she think of turning the handle of a door.",
 "'It was not until ... that ...' puts the focus on the time: the thing happened only then, and not before."),
("The tapestry was the covering of a door which fell open",
 "The tapestry covered a door. The door fell open.",
 "'which fell open' is a relative clause that tells which door; 'fell open' means opened by itself."),
]
phrases = [
("bring back","phrasal verb","To make you remember something.",["brought back"],"brought back to her mind the hundred rooms"),
("look after","phrasal verb","To take care of someone.",["look after"],"You’ll have to play about and look after yourself"),
("take back","phrasal verb","To bring something or someone back to where you came from.",["took back"],"I would take them back with me"),
("pull away","phrasal verb","To take someone away by pulling.",["pulled away"],"took Mary by the arm and pulled her away"),
("find out","phrasal verb","To learn a fact that you did not know.",["found out"],"sometime she would find out"),
("lose one's way","idiom","To not know the way and become lost.",["lost her way"],"she lost her way by turning down the wrong corridor"),
]
