words = [
("inactive","adjective","Not doing anything; not working."),
("baffling","adjective","Very hard to understand; confusing."),
("howsoever","adverb","However. This is an old way to say it."),
("glossy","adjective","Smooth and shining."),
("contrariness","noun","The habit of doing the opposite of what other people want."),
("scampering","present participle","Running quickly with light steps."),
("peddling","present participle","Going from place to place to sell small things."),
("fumbling","present participle","Moving your hands in a clumsy way to find something."),
("skip","verb","To jump over a rope that you swing under your feet and over your head. A skipping-rope is the rope.",["skipped","skipping"]),
("tuppence","noun","Two pennies, a small amount of old British money."),
("impudence","noun","Rude behaviour that shows no respect."),
("clumsy","adjective","Not smooth or neat in how you move."),
("trill","noun","A quick, high song of a bird, with the same sound repeated fast."),
("adorably","adverb","In a way that makes you love it."),
("gust","noun","A short, strong rush of wind."),
("knob","noun","A round handle on a door."),
("heathen","noun","A person who does not follow the religion of the speaker. Ben uses it for people who are not Christian."),
("pipin","adjective","Very hot. The book writes it as pipin'; 'piping hot' means very hot."),
("odds","plural noun","'Odds and ends' means small things of different kinds."),
]
paras = [
(9,2,"She looked at the key quite a long time",
 "Mary thinks about the key. She would like to open the closed garden and play there alone.",
 "She looked at the key for quite a long time. She turned it over and over and thought about it. As the writer has said before, she was not a child who had been taught to ask permission or ask older people about things. All she thought about the key was this: if it was the key to the closed garden, and she could find where the door was, she could perhaps open it. She could see what was inside the walls and what had happened to the old rose-trees. She wanted to see the garden because it had been shut up for so long. It seemed that it must be different from other places, and that something strange must have happened to it in ten years. Besides, if she liked it, she could go into it every day and shut the door behind her. She could make up some play of her own and play it quite alone. Nobody would know where she was, but would think that the door was still locked and the key buried in the earth. The thought of that pleased her very much.",
 ["consult","shut up","play of her own"]),
(9,3,"Living as it were, all by herself in a house",
 "Living alone in the big house and the fresh air from the moor are changing Mary. She begins to care about things and feels less contrary.",
 "Mary was living, so to speak, all by herself in a house with a hundred rooms that were closed in a way that was a mystery. She had nothing at all to do to amuse herself. This had set her slow brain to work, and it was waking up her imagination. There is no doubt that the fresh, strong, clean air from the moor had a great deal to do with it. The air had given her an appetite, and fighting the wind had stirred her blood. In the same way, these things had stirred her mind. In India she had always been too hot, slow and weak to care much about anything. But in this place she was beginning to care and to want to do new things. Already she felt less 'contrary', though she did not know why.",
 ["as it were","inactive","imagination","languid","contrary"]),
(9,51,"One of the nice little gusts of wind rushed down the walk",
 "A strong wind moves the ivy, and Mary sees a round knob under the leaves. It is the knob of a door.",
 "One of the nice little gusts of wind rushed down the walk, and it was stronger than the rest. It was strong enough to move the branches of the trees. It was more than strong enough to swing the hanging pieces of ivy that had not been cut. Mary had stepped close to the robin. Suddenly the gust of wind swung aside some loose ivy. More suddenly still, she jumped toward it and caught it in her hand. She did this because she had seen something under it. It was a round knob that had been covered by the leaves hanging over it. It was the knob of a door.",
 ["gusts","sway","trailing sprays","knob"]),
]
sents = [
("Living as it were, all by herself in a house with a hundred",
 "Living, so to speak, all alone in a house with a hundred rooms that were closed in a mysterious way, had set her mind to work.",
 "'Living ... had set her ... to working' has an -ing phrase as its subject; 'as it were' means 'so to speak'."),
("It seemed as if it must be different from other places",
 "It seemed that the garden must be different from other places.",
 "'seemed as if' tells how things look; 'must be' shows Mary is almost sure, because the garden had been shut for so long."),
("If tha’d been our ’Lizabeth Ellen tha’d have give me a kiss",
 "If you had been our Lizabeth Ellen, you would have given me a kiss.",
 "'If + had been, would have + past participle' is about the past and what did not happen; Martha's Yorkshire says 'give' for 'given'."),
("Nothing in the world is quite as adorably lovely as a robin",
 "A robin is the loveliest thing in the world when he shows off.",
 "'nothing ... as ... as' is a comparison that says a robin is the best; 'when he shows off' tells the time."),
]
phrases = [
("show off","phrasal verb","To do something so that people will look at you and admire you.",["shows off"],"merely to show off"),
("go out","phrasal verb","To leave a place, for example the house.",["went out"],"Martha went out of the room"),
("turn back","phrasal verb","To go back the way you came.",["turned back"],"turned back rather slowly"),
("make up","phrasal verb","To think of an idea or a story.",["make up"],"she could make up some play of her own"),
("keep on","phrasal verb","To go on doing something without stopping.",["keep on"],"Tha’ keep on,” said Ben"),
("run off","phrasal verb","To go away quickly.",["run off"],"Run off outside an’ play with thy rope"),
]
