words = [
("vexes","verb","Makes someone annoyed or angry."),
("tantrum","noun","A sudden fit of anger, like a child's."),
("agitated","adjective","Very upset and unable to stay calm."),
("bewitched","past-tense verb","Put under a spell; here, changed by what seems like magic."),
("sylum","noun","Short for asylum, an old word for a place for people who are very ill in the mind."),
("raved","past-tense verb","Spoke wildly, as if out of his mind."),
("brace","noun","A stiff support worn on the body to hold the back straight."),
("fretted","past-tense verb","Was worried and unhappy."),
("rheumatic","adjective","Of a sickness that makes the joints hurt. 'Rheumatic fever' is a serious sickness with fever and sore joints."),
("typhoid","noun","A serious sickness with a high fever."),
("brocaded","adjective","Made of rich cloth with a raised pattern."),
("curtsy","noun","A small bow made by a girl or woman, bending the knees."),
("rajah","noun","An Indian prince or king."),
("charm","verb","To make animals or people listen and obey, as if by magic."),
("superb","adjective","Very fine."),
("burrows","plural noun","Holes in the ground made by animals to live in."),
("resentful","adjective","Angry and hurt about something unfair."),
("boasted","past-tense verb","Spoke with too much pride about oneself or something one has."),
("reproachfully","adverb","In a way that shows you think someone has done wrong."),
]
paras = [
(15,28,"Nobody knows for sure and certain",
 "Martha tells Mary what is wrong with Colin. Mr Craven went out of his mind when Colin was born because Mrs Craven died.",
 "'Nobody knows for sure and certain,' said Martha. 'Mr. Craven went out of his mind when the baby was born. The doctors thought he would have to be put in an asylum. It was because Mrs. Craven died, like I told you. He would not set eyes on the baby. He just raved and said it would be another hunchback like him, and it had better die.'",
 ["sylum","raved","hunchback"]),
(15,64,"This is the first one,” said Mary, seating herself on the big stool",
 "Mary tells Colin the first thing she was thinking. She once saw a boy Rajah in India who spoke to his people as Colin spoke to Martha.",
 "'This is the first one,' said Mary, sitting down on the big stool. 'Once in India I saw a boy who was a Rajah. He had rubies and emeralds and diamonds stuck all over him. He spoke to his people just as you spoke to Martha. Everybody had to do everything he told them, in a minute. I think they would have been killed if they had not.'",
 ["rajah","rubies","emeralds"]),
(15,105,"It was the best thing she could have said",
 "Talking about Dickon and the moor makes Mary and Colin laugh like two ordinary healthy children.",
 "It was the best thing she could have said. To talk about Dickon meant to talk about the moor and the cottage, and the fourteen people who lived in it on sixteen shillings a week. It meant the children who got fat on the moor grass like the wild ponies. It meant Dickon's mother and the skipping-rope, and the moor with the sun on it, and the pale green points sticking up out of the black earth. It was all so alive that Mary talked more than she had ever talked before, and Colin both talked and listened as he had never done either before. They began to laugh over nothing, as children do when they are happy together. In the end they were making as much noise as two ordinary, healthy, natural ten-year-old children, instead of a hard, little, unloving girl and a sickly boy who believed that he was going to die.",
 ["sod","nothings","sickly"]),
]
sents = [
("He knows us daren’t call our souls our own",
 "He knows we do not dare to say that anything is ours.",
 "'us' is Yorkshire for 'we'; 'daren't' is 'dare not'; 'call our souls our own' is a saying: the servants have no freedom."),
("Mr. Craven went off his head like when he was born",
 "Mr Craven went out of his mind when Colin was born.",
 "'went off his head' means became mad; 'like when he was born' is Yorkshire for 'at the time he was born'."),
("Have you to do what I please or have you not?",
 "Do you have to do what I want, or do you not?",
 "'Have you to do' is an old way of asking 'Do you have to do'; 'or have you not' ends the question."),
]
phrases = [
("shake in one’s shoes","idiom","To be very afraid.",["shaking in her shoes"],"Poor Martha was shaking in her shoes"),
("go off","phrasal verb","'Go off one's head' means to become mad.",["went off"],"Mr. Craven went off his head"),
("roll up","phrasal verb","To fold something into a roll.",["rolled up"],"she rolled up her knitting"),
("lie back","phrasal verb","To lean back and rest.",["lay back"],"Colin lay back on his cushion"),
("fall back","phrasal verb","To step back.",["fell back"],"Mrs. Medlock almost fell back"),
("walk into","phrasal verb","To enter a place, often in an unplanned way.",["walked into"],"as if an elderly cat and dog had walked into the room"),
]
