words = [
("sly","adjective","Clever in a quiet way, in order to find out things or get what you want."),
("scrawny","adjective","Thin and bony, in an ugly way."),
("slamp","verb","A Yorkshire word meaning to lie down flat. Martha says Mary's hair does not slamp down flat on her head."),
("yeller","adjective","A Yorkshire way to say 'yellow'."),
("nigh","adverb","A Yorkshire and old word for near. 'Not nigh so' means 'not nearly so'."),
("waft","noun","A light stream of air carrying a smell."),
("fluting","adjective","Making soft, high, sweet sounds like a flute."),
("scores","plural noun","Many; twenty or more. 'Scores of birds' means very many birds."),
("unbolt","verb","To slide back a bolt, a metal bar that holds a door shut."),
("herbaceous","adjective","Of plants that have soft stems and die down each winter. 'Herbaceous beds' are garden beds of such plants."),
("unfurling","present participle","Opening out from a rolled-up or folded shape."),
("plumaged","adjective","Having feathers of a certain kind. 'Glossy-plumaged' means with shiny feathers."),
("alighted","past-tense verb","Came down and landed, as a bird does."),
("tousled","adjective","With untidy hair."),
("rook","noun","A big black bird of the crow family."),
("mould","noun","Soft, rich earth."),
("rapture","noun","A feeling of great joy."),
("munnot","verb","A Yorkshire way to say 'must not'."),
("meddle","verb","To get into something that is not your business."),
("cripple","noun","An old word for a person who cannot walk or move well. Here it means someone whose body does not grow straight."),
("gauze","noun","Very thin, light cloth that you can see through."),
("veil","noun","A thin cloth that covers the face or something else."),
]
paras = [
(16,4,"In her talks with Colin, Mary had tried to be very cautious",
 "Mary is careful about the secret garden when she talks with Colin. She wants to know if he can keep a secret and if she could take him there without anyone knowing.",
 "In her talks with Colin, Mary had tried to be very careful about the secret garden. There were certain things she wanted to find out from him, but she felt that she must find them out without asking him direct questions. First, as she began to like being with him, she wanted to know if he was the kind of boy you could tell a secret to. He was not at all like Dickon, but he was so pleased with the idea of a garden no one knew about that she thought he could perhaps be trusted. But she had not known him long enough to be sure. The second thing she wanted to find out was this. If he could be trusted, would it be possible to take him to the garden without anyone finding out? The grand doctor had said that he must have fresh air, and Colin had said that he would not mind fresh air in a secret garden. Perhaps if he had a great deal of fresh air, and knew Dickon and the robin, and saw things growing, he might not think so much about dying. Mary had seen herself in the glass sometimes lately. She had seen that she looked quite different from the child she had seen when she arrived from India. This child looked nicer. Even Martha had seen a change in her.",
 ["cautious","direct","trusted"]),
(16,48,"We munnot stir,” he whispered in broad Yorkshire",
 "Dickon sees Ben Weatherstaff's robin building its nest. He tells Mary to stay still so that it will not be frightened.",
 "'We must not move,' he whispered in strong Yorkshire speech. 'We must hardly breathe. I knew he was looking for a mate when I saw him last. It is Ben Weatherstaff's robin. He is building his nest. He will stay here if we do not frighten him.'",
 ["munnot","scarce","flight"]),
(16,68,"Everybody as knowed about Mester Craven knowed there was a little lad",
 "Dickon explains how he knew about Colin. People who knew Mr Craven knew about the boy, and Mrs Medlock talks about him at the Sowerby cottage.",
 "'Everybody who knew about Mr. Craven knew there was a little boy who was likely to be a cripple. They knew Mr. Craven did not like him to be talked about. People are sorry for Mr. Craven because Mrs. Craven was such a pretty young lady, and they were so fond of each other. Mrs. Medlock stops in our cottage whenever she goes to Thwaite. She does not mind talking to mother in front of us children, because she knows we have been brought up to be trusty. How did you find out about him? Martha was in a lot of trouble the last time she came home. She said you had heard him crying and you were asking questions, and she did not know what to say.'",
 ["mester","cripple","trusty","frettin"]),
]
sents = [
("Tha’ knew how to build tha’ nest before tha’ came out o’ th’ egg",
 "You knew how to build your nest before you came out of the egg.",
 "'Tha'' is Yorkshire for 'you' and 'tha' nest' for 'your nest'; 'knew how to build' is 'knew' plus 'how' plus 'to' and a verb."),
("He’d be out with us for good if he got th’ notion",
 "He would be finished with us for ever if he got the idea that we were in his way.",
 "'if he got th' notion' is a 'if' clause that gives the condition; 'us was' is Yorkshire for 'we were'."),
("way o’ thinkin’ and doin’ things an’ a body had better not meddle",
 "They have their own way of thinking and doing things, and a person had better not mix in.",
 "'had better not meddle' means 'should not meddle'; 'a body' means 'a person'."),
]
phrases = [
("get up","phrasal verb","To rise from bed or from the ground.",["got up","get up"],"He got up himself, laughing and glowing"),
("tune up","phrasal verb","To get ready to play music by making the sounds right.",["tune up"],"beginning to tune up for a concert"),
("come upon","phrasal verb","To find something by chance.",["come upon"],"They had come upon a whole clump of crocuses"),
("settle down","phrasal verb","To sit or lie down comfortably.",["settled down"],"They settled down softly upon the grass"),
("look out","phrasal verb","To take care.",["Look out"],"Look out tha’ doesn’t tell on us"),
("push up","phrasal verb","To come up through the earth.",["pushed up","push up"],"See how these has pushed up"),
("stir up","phrasal verb","To move around.",None,None),
]
phrases=[p for p in phrases if p[0]!="stir up"]
