words = [
("determined","adjective","Having made up your mind to do something and not willing to stop."),
("intimate","adjective","Close and friendly."),
("flattered","adjective","Pleased because someone shows that they like or respect you."),
("civil","adjective","Polite."),
("vanity","noun","Too much pride in how you look or what you do."),
("flightiness","noun","Behaviour that changes quickly and cannot be trusted."),
("hobnailed","adjective","Having a boot with thick nails in the bottom to make it strong."),
("sarcastic","adjective","Saying the opposite of what you mean, to make fun of someone."),
("currant","noun","A small round fruit that grows on a bush."),
("danged","adjective","A mild way to say 'damned', used by Ben in the book to show surprise."),
("bachelder","noun","A Yorkshire way to say 'bachelor', a man who is not married."),
("rheumatics","plural noun","A sickness that makes the joints hurt and be stiff. People now say 'rheumatism'."),
("pheasant","noun","A large wild bird with a long tail. People hunt it for food."),
("tremulous","adjective","Shaking a little."),
("trowel","noun","A small garden tool with a short handle, used for digging small holes."),
("hoe","noun","A garden tool with a long handle and a flat blade, used for cutting weeds."),
("larkspur","noun","A tall garden plant with blue, pink or white flowers."),
("mignonette","noun","A small garden plant with flowers that smell sweet."),
("flout","verb","To show that you do not respect someone, in an open way."),
("sidled","past-tense verb","Moved sideways, in small quick steps, as a bird does."),
("obstinate","adjective","Not willing to change your mind, even when other people ask you to."),
("defiantly","adverb","In a way that shows you will not obey."),
]
paras = [
(11,3,"During that week of sunshine, she became more intimate with Ben Weatherstaff",
 "Mary becomes friendlier with Ben Weatherstaff. He does not mind her as much as before, and she is more polite.",
 "During that week of sunshine, Mary became closer to Ben Weatherstaff. She surprised him several times by seeming to start up beside him, as if she had sprung out of the earth. The truth was that she was afraid he would pick up his tools and go away if he saw her coming. So she always walked toward him as quietly as she could. But he did not mind her as strongly as he had at first. Perhaps he was secretly rather pleased that she clearly wanted to be with an old man. Also, she was more polite than she had been. He did not know that when she first saw him, she spoke to him as she would have spoken to a native of India. She had not known that a cross, strong old Yorkshire man was not used to bowing to his masters and just being ordered by them to do things.",
 ["intimate","flattered","evident","civil","native","salaam"]),
(11,54,"It was a very strange thing indeed",
 "Mary sees Dickon for the first time. He plays a pipe, and wild animals come near to listen.",
 "It was a very strange thing. She stopped to look at it, and for a moment she could hardly breathe. A boy was sitting under a tree with his back against it, playing on a rough wooden pipe. He was a funny-looking boy of about twelve. He looked very clean. His nose turned up and his cheeks were as red as poppies. Mistress Mary had never seen such round and such blue eyes in any boy's face. On the trunk of the tree he leaned against, a brown squirrel was holding on and watching him. From behind a bush nearby, a male pheasant was carefully stretching his neck to peep out. Quite near him were two rabbits sitting up and sniffing with shaking noses. It really seemed as if they were all coming nearer to watch him and listen to the strange low little call that his pipe made.",
 ["pheasant","delicately","tremulous","poppies","pipe"]),
]
sents = [
("Perhaps he was secretly rather flattered by her evident desire for his elderly company",
 "Perhaps he was secretly a little pleased that she clearly wanted to be with an old man.",
 "'was flattered by' is a passive form: her wish made him feel pleased; 'her evident desire for his ... company' is a noun phrase meaning 'her clear wish to be with him'."),
("he would not have stirred for the world, lest his robin should start away",
 "He did not move at all, because he was afraid his robin would fly away.",
 "'lest ... should' means 'in case' or 'for fear that'; it is an old way to say what you want to avoid."),
("Birds is rare choosers an’ a robin can flout a body",
 "Birds are very careful about who they choose, and a robin can treat a person with more disrespect than a man can.",
 "'Birds is' is Yorkshire for 'Birds are'; 'a body' means 'a person'; 'rare choosers' means birds that choose with great care."),
]
phrases = [
("make up to","phrasal verb","To try to be friendly with someone so that they will like you.",["making up to","makin’ up to","making up to"],"Makin’ up to th’ women folk just for vanity"),
("start up","phrasal verb","To rise or appear suddenly.",["start up"],"seeming to start up beside him"),
("look over","phrasal verb","To look at someone carefully from top to bottom.",["looked over"],"while he looked her over"),
("put up with","phrasal verb","To accept someone or something that you do not like.",None,"Tha’ can put up with me for a bit sometimes"),
("pick up","phrasal verb","To lift something from the ground or a table.",["pick up"],"he would pick up his tools and go away"),
("get over","phrasal verb","To win someone's good opinion by clever ways.",["get over"],"Tha’ thinks tha’ll get over me by doin’ that"),
("burst out","phrasal verb","To suddenly begin to do something, for example to cry.",["burst out crying"],"burst out crying"),
]
