words = [
("ajar","adjective","A little open. A door that is ajar is not fully closed."),
("rebellious","adjective","Not willing to obey rules or people in charge."),
("glimmer","noun","A weak, unsteady light."),
("agate","noun","A hard stone with lines of colour. Here it is used for the grey colour of Colin's eyes."),
("lashes","plural noun","The hairs along the edge of the eyelid."),
("wrapper","noun","A loose piece of clothing worn over night clothes."),
("invalid","noun","A person who is ill or weak for a long time."),
("indifferently","adverb","In a way that shows you do not care."),
("persistently","adverb","In a way that does not stop or give up."),
("clambered","past-tense verb","Climbed in a rough, awkward way, using hands and feet."),
("tramp","verb","To walk with heavy steps through a place."),
("complainingly","adverb","In an unhappy way, as if saying something is wrong."),
("chanting","adjective","Said or sung in a slow, even way, again and again."),
("hindustani","noun","A language spoken in India."),
("tumbled","past-tense verb","Fell or hung down in a loose, untidy way."),
("mournful","adjective","Sad and slow."),
]
paras = [
(14,12,"The door of her room was ajar and the sound came down the corridor",
 "Mary hears crying again at night. She decides to find out what it is.",
 "The door of her room was a little open, and the sound came down the corridor. It was a far-off faint sound of unhappy crying. She listened for a few minutes, and each minute she became more and more sure. She felt that she must find out what it was. It seemed even stranger than the secret garden and the buried key. Perhaps she was in a mood to break rules, and this made her brave. She put her foot out of bed and stood on the floor.",
 ["ajar","fretful","rebellious","bold"]),
(14,19,"The boy had a sharp, delicate face the color of ivory",
 "Mary sees the boy in the bed. He looks ill, with big eyes and a lot of hair.",
 "The boy had a sharp, thin face the color of ivory, and he seemed to have eyes too big for it. He also had a lot of hair, which fell over his forehead in heavy locks and made his thin face seem smaller. He looked like a boy who had been ill. But he was crying more as if he were tired and cross than as if he were in pain.",
 ["delicate","ivory","locks"]),
(14,117,"He lay quite still and listened while she went on talking",
 "Mary tells Colin about the garden, the robin and Ben Weatherstaff. The talk about the robin makes Colin smile.",
 "He lay quite still and listened while she went on talking. She spoke about the roses, which might have climbed from tree to tree and hung down. She spoke about the many birds which might have built their nests there because it was so safe. Then she told him about the robin and Ben Weatherstaff. There was so much to tell about the robin, and it was so easy and safe to talk about it, that she stopped feeling afraid. The robin pleased him so much that he smiled until he looked almost beautiful. At first Mary had thought that he was even plainer than herself, with his big eyes and heavy locks of hair.",
 ["clambered","ceased","locks"]),
]
sents = [
("Perhaps the fact that she was in a rebellious mood made her bold",
 "Perhaps she was brave because she was in a mood to break the rules.",
 "'the fact that she was ... made her bold' has a long subject that starts with 'the fact that'; 'made her bold' means 'caused her to be bold'."),
("If I were to live, this place would sometime belong to me",
 "If I lived, this place would one day be mine.",
 "'If I were to live' is an imagined case about the future; 'would' shows the result."),
("I should have been afraid you would see me",
 "I would have been afraid that you would see me.",
 "'should have been' is the British form of 'would have been'; the 'that' before 'you would see me' is left out."),
("If she had lived I believe I should not have been ill always",
 "I believe that if my mother had lived, I would not have been ill all the time.",
 "'If she had lived ... should not have been' is about the past and what did not happen; 'ill always' puts 'always' after the word."),
]
phrases = [
("find out","phrasal verb","To learn a fact that you did not know.",["find out"],"I am going to find out what it is"),
("go on","phrasal verb","To keep doing something.",["went on","go on","going on"],"she went on chanting and stroking"),
("lie awake","phrase","To stay awake in bed.",["lying awake"],"She had been lying awake turning from side to side"),
("talk over","phrasal verb","To speak about someone or something.",["talk me over","talked over"],"I won’t let people see me and talk me over"),
]
