words = [
("matted","adjective","Twisted together in a thick, tight mass."),
("tendril","noun","A thin, curling part of a climbing plant that holds on to things."),
("hazy","adjective","Not clear, as if seen through a thin mist."),
("tangle","noun","A mass of things twisted together."),
("alcove","noun","A small space set back into a wall or a hedge."),
("urn","noun","A tall vase, often with a foot, used for plants."),
("bulb","noun","A round part of a plant under the ground, from which a flower grows."),
("narcissus","noun","A spring flower with a sweet smell. Daffodils are one kind."),
("jonquil","noun","A yellow or white spring flower like a small daffodil."),
("weed","noun","A wild plant that grows where you do not want it."),
("smothering","present participle","Covering something so thickly that it cannot breathe or grow."),
("pondered","past-tense verb","Thought about something carefully."),
("forevermore","adverb","For all time to come."),
("eyeteeth","plural noun","The two pointed teeth in the upper jaw. 'Like pulling eyeteeth' means very hard to do."),
("dictated","past-tense verb","Said words aloud for someone else to write down."),
("restlessly","adverb","In a way that shows you cannot be calm or still."),
]
paras = [
(10,2,"It was the sweetest, most mysterious-looking place anyone could imagine",
 "Mary sees the secret garden. Climbing roses cover the walls and trees. She cannot tell if they are dead or alive.",
 "It was the sweetest, most mysterious-looking place that anyone could imagine. The high walls that shut it in were covered with the bare stems of climbing roses, so thick that they were twisted together. Mary Lennox knew they were roses, because she had seen a great many roses in India. All the ground was covered with grass of a winter brown. Out of it grew groups of bushes which were surely rosebushes, if they were alive. There were many standard roses that had spread their branches so much that they were like little trees. There were other trees in the garden. One of the things that made the place look strangest and loveliest was that climbing roses had run all over these trees. They had swung down long thin curling stems which made light swinging curtains. Here and there the roses had caught hold of each other, or of a branch that reached far, and had crept from one tree to another and made lovely bridges of themselves. There were no leaves and no roses on them now, and Mary did not know if they were dead or alive. But their thin gray or brown branches looked like a kind of misty cloak spreading over everything, walls, trees, and even the brown grass, where they had fallen from their ties and run along the ground. It was this misty tangle from tree to tree that made it all look so mysterious. Mary had thought it must be different from other gardens which had not been left all by themselves for so long. And it was different from any other place she had ever seen in her life.",
 ["matted","standard roses","tendrils","far-reaching","hazy","mantle","fastenings","tangle"]),
(10,18,"She did not know anything about gardening",
 "Mary starts to clear the weeds and grass around the small green plants so they can grow.",
 "She did not know anything about gardening. But the grass seemed so thick in some of the places where the green points were pushing through that she thought they did not have room enough to grow. She searched about until she found a rather sharp piece of wood. She knelt down and dug, and pulled out the weeds and grass, until she made nice little clear places around the green points.",
 ["weeded out","weeds"]),
]
sents = [
("If she had been Ben Weatherstaff she could have told",
 "If Mary had been Ben Weatherstaff, she could have told by looking whether the wood was alive.",
 "'If she had been ... she could have told' is about the past and what did not happen: Mary was not Ben; the next words in the book, 'by looking at it', tell how she could tell."),
("It isn’t a quite dead garden,” she cried out softly",
 "The garden is not completely dead, she cried out softly to herself.",
 "'a quite dead garden' puts 'quite' before 'a'; it is the old word order for 'quite a dead garden'. 'Not quite dead' means a little alive."),
("a woman as brings up twelve children learns something besides her A.B.C.",
 "A woman who raises twelve children learns something besides her letters.",
 "'as' here is Yorkshire for 'who' in a relative clause; 'brings up' means raises; 'besides' means 'in addition to'."),
("she was obliged to clear the table and carry the plates and dishes downstairs",
 "Martha had to clear the table and carry the plates and dishes downstairs.",
 "'was obliged to + verb' means 'had to'; 'clear ... and carry ...' are two actions joined after 'to'."),
]
phrases = [
("come alive","phrase","To begin to live again.",["come alive"],"the garden won’t be dead at all —it will come alive"),
("look up","phrasal verb","To lift your eyes to look at something above you.",["looked up"],"looked up at the sprays and tendrils"),
("put out","phrasal verb","To make something start to grow.",["put out"],"might put out leaves and buds as the weather got warmer"),
("lead on","phrasal verb","To make someone go further.",["led on"],"she was led on from bed to bed"),
("take to","phrasal verb","To start doing something as a habit.",["take to"],"Art tha’ goin’ to take to diggin’"),
("bring up","phrasal verb","To take care of a child until it grows up.",["brings up"],"A woman as brings up twelve children"),
("light up","phrasal verb","To become bright with joy.",["lighted up"],"Martha’s face quite lighted up"),
("break out","phrasal verb","To begin to speak suddenly.",["broke out"],"she broke out"),
]
