words = [
("creeper","noun","A plant that climbs up walls or trees."),
("lichen","noun","A flat, grey-green growth on the bark of trees or on stones."),
("upholding","present participle","Holding up; carrying the weight of something."),
("reverent","adjective","Showing deep respect."),
("wick","adjective","A Yorkshire word for alive and full of life. Mary is told that it means alive or lively."),
("thrived","past-tense verb","Grew strong and well."),
("exultantly","adverb","In a way that shows great joy."),
("industriously","adverb","In a way that shows hard work."),
("nesh","adjective","A Yorkshire word for weak or easily hurt by cold."),
("whitethorn","noun","A small tree with thorns and white flowers, also called hawthorn."),
("knobstick","noun","A stick with a round lump at the top."),
("spick","adjective","'Spick and span' means very clean and neat."),
("spiteful","adjective","Wanting to hurt someone."),
("distended","adjective","Swollen; stretched out because it is full."),
("stifle","verb","To stop a sound from coming out."),
("lily","noun","A tall garden flower with large petals. 'Lilies o' th' valley' are small white flowers shaped like bells."),
("missel","noun","A kind of large thrush, a brown bird that sings. Here it is part of 'missel thrush'."),
]
paras = [
(12,15,"He stepped over to the nearest tree",
 "Dickon shows Mary a branch that looks brownish green. He tells her there is dead wood to cut out.",
 "Dickon stepped over to the nearest tree. It was a very old tree with gray lichen all over its bark, but it held up a curtain of tangled branches. He took a thick knife out of his pocket and opened one of its blades.",
 ["lichen","upholding","tangled"]),
(12,42,"I never ketched cold since I was born",
 "Dickon says he never catches cold because he has always been out in all kinds of weather.",
 "'Not me,' he said, with a grin. 'I have never caught a cold since I was born. I was not brought up weak. I have run about on the moor in all weathers, like the rabbits do. Mother says I have sniffed in too much fresh air for twelve years to ever start sniffing because of a cold. I am as tough as a stick from a hawthorn tree.'",
 ["ketched","nesh","whitethorn","knobstick"]),
(12,71,"there doesn’t seem to be no need for no one to be contrary",
 "Dickon says no one needs to be contrary when there are flowers and friendly wild animals around.",
 "'Eh!' he said. As he crumbled the rich black soil, she saw that he was breathing in the smell of it. 'There seems to be no need for anyone to be contrary when there are flowers and such things, and so many friendly wild animals running about making homes for themselves, or building nests and singing and whistling, is there?'",
 ["crumbled","suchlike","contrary"]),
]
sents = [
("Th’ other ones takes two years to bloom from seed",
 "The other flowers take two years to come into flower from seed.",
 "'Th' other ones takes' is Yorkshire; in standard English it is 'The other ones take'. 'Takes' goes with 'ones', which is plural."),
("I’ve sniffed up too much fresh air for twelve year’",
 "I have breathed in so much fresh air for twelve years that I will never sniff because of a cold.",
 "'too much ... to ever get to ...' means the amount is so big that the result cannot happen; 'twelve year'' is Yorkshire for 'twelve years'."),
("Whatever happens, you —you never would tell?",
 "Whatever happens, you would never tell anyone, would you?",
 "'Whatever happens' means 'no matter what happens'; 'you never would tell?' is a question made from a statement, and 'would' is about what he is willing to do."),
]
phrases = [
("dig about","phrasal verb","To dig around a place.",["dug about"],"dug about roots with the spade"),
("cut out","phrasal verb","To take something away by cutting.",["cut out"],"lots o’ dead wood as ought to be cut out"),
("die out","phrasal verb","To stop living, one after another.",["died out"],"The delicatest ones has died out"),
("run wild","idiom","To grow without anyone looking after it.",["run wild","ran wild"],"They’ve run wild,” he said"),
("catch sight of","idiom","To see something for a short time.",["caught sight of"],"he caught sight of something"),
("check off","phrasal verb","To mark things one by one.",["checked off"],"Mary checked them off on her fingers"),
("sit up","phrasal verb","To move from lying to sitting, or to sit with a straight back.",["sat up"],"Dickon sat up on his heels"),
("call up","phrasal verb","To make an animal come by calling.",["call up"],"I’ll call th’ robin up"),
]
