words = [
("overexert","verb","To work your body too hard."),
("brute","noun","A rough, unkind person."),
("undisturbedly","adverb","In a calm way, not upset at all."),
("slapping","adjective","Hitting with the open hand. 'A slapping sort of man' means a man who slaps people."),
("prejudice","noun","A bad opinion formed before you know the facts. 'Without prejudice' means with a fair mind."),
("impartially","adverb","In a fair way, taking no side."),
("crevices","plural noun","Narrow cracks or gaps in a wall or rock."),
("satiny","adjective","Smooth and shiny, like satin cloth."),
("tints","plural noun","Shades of a colour."),
("defying","present participle","Standing up against someone or something in a bold way."),
("wreathing","present participle","Winding round something in a ring."),
("cascades","plural noun","Falls, like water falling down in a stream."),
("sundial","noun","A tool that shows the time by a shadow from the sun."),
("unsheath","verb","To take out of a cover. Here it means buds opening out of their covers."),
("acquaintance","noun","Knowledge of a person or thing. 'Make the acquaintance of' means get to know."),
("fakirs","plural noun","Holy men in India who go without comforts and are said to do wonderful things."),
("imposing","adjective","Making people feel respect because it seems great."),
("orator","noun","A person who makes a speech."),
("sinetifik","adjective","Ben's way to say 'scientific'."),
("devotees","plural noun","People who are very strongly given to a religion or a belief."),
("majestic","adjective","Grand and beautiful, like a king."),
("dervishes","plural noun","Holy men of a certain faith who sway or whirl about in their prayers."),
("entranced","adjective","So pleased that you cannot look away."),
("goodly","adjective","Fairly large."),
("sermon","noun","A talk about religion given in a church."),
("athlete","noun","A person who is very good at sports and is strong."),
("prizefighter","noun","A man who fights with his fists for money."),
("snubbed","adjective","Treated in a cold way, as if not important."),
("disrespectful","adjective","Showing no respect."),
("stimulated","past-tense verb","Made more excited or active."),
("gratified","adjective","Pleased."),
("experiment","noun","A test that you make to find out if something is true."),
("scientific","adjective","Of science; done in a careful way to find out facts."),
("convincing","adjective","Able to make people believe you."),
("fascination","noun","A strong power to interest or attract."),
("drill","noun","Training for soldiers where they do the same things again and again."),
("champion","noun","A person who wins in a sport."),
("stumbling","noun","Nearly falling when walking."),
]
paras = [
(24,7,"Even Mary had found out that one of Colin’s chief peculiarities",
 "Colin does not know how rude he is when he gives orders. Mary had been like him, so she wanted to tell him about it.",
 "Even Mary had found out that one of Colin's main strange ways was that he did not know in the least what a rude little brute he was with his way of ordering people about. He had lived on a sort of desert island all his life, and as he had been the king of it he had made his own manners and had had no one to compare himself with. Mary had been rather like him herself. Since she had been at Misselthwaite she had slowly found that her own manners had not been of the kind which is usual or popular. Having found this out, she thought it interesting enough to tell Colin. So she sat and looked at him curiously for a few minutes after Dr. Craven had gone. She wanted to make him ask her why she was doing it, and of course he did.",
 ["peculiarities","brute","compare"]),
(24,39,"The great scientific discoveries I am going to make",
 "Colin says his discoveries will be about Magic. He says there is Magic in everything and people do not yet know how to use it.",
 "'The great scientific discoveries I am going to make,' he went on, 'will be about Magic. Magic is a great thing, and hardly anyone knows anything about it except a few people in old books, and Mary a little, because she was born in India where there are fakirs. I believe Dickon knows some Magic, but perhaps he does not know he knows it. He charms animals and people. I would never have let him come to see me if he had not been an animal charmer, which is a boy charmer too, because a boy is an animal. I am sure there is Magic in everything, only we have not sense enough to get hold of it and make it do things for us, like electricity and horses and steam.'",
 ["scientific","discoveries","fakirs"]),
(24,89,"Colin flushed triumphantly. He had made himself believe that he was going",
 "Colin has made himself believe he will get well. He likes to imagine his father seeing a strong son.",
 "Colin's face went red with pride. He had made himself believe that he was going to get well, which was really more than half the battle, if he had known it. The thought that excited him more than any other was imagining what his father would look like when he saw that he had a son as straight and strong as other fathers' sons. One of his darkest miseries in the unhealthy past days had been his hatred of being a sickly boy with a weak back, whose father was afraid to look at him.",
 ["triumphantly","stimulated","morbid"]),
]
sents = [
("If you had been his own boy and he had been a slapping sort",
 "If you had been his own son, and he had been a man who slaps.",
 "Both parts use 'if ... had been' for what did not happen; the result comes next, 'he would have slapped you'."),
("It seemed very certain that something was upholding and uplifting him",
 "It seemed very sure that something was holding him up and lifting his spirits.",
 "'It seemed very certain that' starts a clause with 'something was ...'; 'upholding and uplifting' are two '-ing' words joined by 'and'."),
]
phrases = [
("order about","phrasal verb","To give orders to people all the time.",["ordering people about"],"his way of ordering people about"),
("think out","phrasal verb","To work something out by thinking.",["thinking the thing out"],"thinking the thing out quite without prejudice"),
("cheer up","phrasal verb","To become happier.",["cheered up"],"Then he cheered up."),
("sit down","phrasal verb","To take a seat.",["sit down"],"they sat down in their circle"),
]
