words = [
("radiantly","adverb","In a bright, shining way."),
("canopy","noun","A cover that hangs or spreads over a place, like a roof."),
("hatched","past-tense verb","Came out of an egg."),
("flusters","verb","Makes someone nervous and confused."),
("squawks","plural noun","Loud, rough cries of birds."),
("foraging","present participle","Searching for food."),
("suggestive","adjective","Making you think of something."),
("rhododendron","noun","A bush with large, bright flowers."),
("crumpets","plural noun","Small round soft cakes eaten hot with butter."),
("domestic","adjective","Of the home. 'Domestic errands' means jobs for the nest."),
("mellow","adjective","Soft, warm and gentle."),
("lances","plural noun","Long thin spears. Here it means the long thin rays of the sun."),
("harangued","past-tense verb","Spoke angrily and for a long time."),
("besom","noun","A Yorkshire word for a bad-tempered, annoying woman or girl. It is also the word for a broom."),
("drat","interjection","An old word used when you are annoyed."),
("impidint","adjective","Ben's way to say 'impudent'; rude and bold."),
("outraged","adjective","Very angry about something that seems wrong."),
("spellbound","adjective","Held still, as if by magic."),
("beckoned","past-tense verb","Made a sign with the hand for someone to come."),
("imperiously","adverb","In a proud way that expects people to obey."),
("gnarled","adjective","Rough, twisted and knotted, as old wood or old hands."),
("tactless","adjective","Saying things without thinking how they may hurt."),
("disentangle","verb","To free from something that holds it."),
("gabbled","past-tense verb","Spoke very fast and not clearly."),
("lath","noun","A thin, narrow strip of wood."),
("wraith","noun","A ghost."),
("mon","noun","A Yorkshire way to say 'man'."),
("upright","adverb","Straight up."),
("thowt","verb","A Yorkshire way to say 'thought'."),
("abide","verb","To bear or put up with someone."),
("woodpecker","noun","A bird that hits trees with its beak to find insects."),
("majesty","noun","Great beauty and power that make people feel respect."),
("reigned","past-tense verb","Ruled, as a king does. 'Delight reigned' means joy was everywhere."),
]
paras = [
(22,2,"One of the strange things about living in the world",
 "The author says that now and then a person feels sure that he will live for ever. This can happen at dawn, at sunset, at night or in someone's eyes.",
 "One of the strange things about living in the world is that only now and then is one quite sure one is going to live for ever and ever. One knows it sometimes when one gets up at the soft, serious time of dawn and goes out and stands alone. One throws one's head far back and looks up and up, and watches the pale sky slowly changing and flushing, and wonderful unknown things happening, until the East almost makes one cry out, and one's heart stands still at the strange unchanging greatness of the rising of the sun. It has been happening every morning for thousands and thousands and thousands of years. One knows it then for a moment or so. One knows it sometimes when one stands by oneself in a wood at sunset, and the mysterious deep gold stillness coming through and under the branches seems to be saying something slowly, again and again, that one cannot quite hear, however much one tries. Then sometimes the great quiet of the dark blue at night, with millions of stars waiting and watching, makes one sure. Sometimes a sound of far-off music makes it true, and sometimes a look in someone's eyes.",
 ["tender","solemn","majesty","immense"]),
(22,28,"We mun look as if it wasn’t no different from th’ other trees",
 "Dickon and Mary agreed to look cheerful and not tell Colin how the branch broke. Dickon said Mrs Craven may still be near, looking after her son.",
 "'We must look as if it was no different from the other trees,' he had said. 'We could never tell him how it broke, poor boy. If he says anything about it we must try to look cheerful.' 'Yes, we must,' Mary had answered.",
 ["mun"]),
(22,68,"And this, if you please, this is what Ben Weatherstaff beheld",
 "Ben Weatherstaff sees a wheeled chair with Colin in it. Colin looks like a young Rajah giving orders.",
 "And this, if you please, this is what Ben Weatherstaff saw, and it made his mouth drop open. A wheeled chair with rich cushions and rugs came toward him, looking like a kind of State Coach. A young Rajah leaned back in it. He had royal command in his great black-rimmed eyes, and a thin white hand held out proudly toward him. The chair stopped right under Ben Weatherstaff's nose. It was no wonder his mouth dropped open.",
 ["beheld","luxurious","haughtily"]),
(22,81,"It was too much. The strength which Colin usually threw into his tantrums",
 "Ben asks if Colin has crooked legs. Colin is so angry that he finds a new strength.",
 "It was too much. The strength which Colin usually threw into his tantrums rushed through him now in a new way. Never yet had he been accused of crooked legs, even in whispers. Ben Weatherstaff's voice showed that he simply believed they were crooked, and this was more than a Rajah's flesh and blood could stand. His anger and hurt pride made him forget everything but this one moment. They filled him with a power he had never known before, an almost unnatural strength.",
 ["accused","endure","unnatural"]),
]
sents = [
("she’s seen th’ little chaps when it seemed like th’ sweat must be droppin’",
 "She has seen the little birds when it seemed that the sweat must be dropping off them.",
 "'seemed like' is used here for 'seemed that'; 'must be droppin'' uses 'must' for what is very likely."),
("If I wasn’t a bachelder, an’ tha’ was a wench o’ mine",
 "If I were not a bachelor, and you were a girl of mine.",
 "'If I wasn't ... and you were' starts an imagined case that is finished in the next words; 'bachelder' is Ben's way to say 'bachelor'."),
("Layin’ tha’ badness on a robin —not but what he’s impidint enow",
 "You put the blame for your badness on a robin, though he is rude enough for anything.",
 "'Layin'' (laying) starts the phrase without 'You are'; 'not but what' means 'though'."),
]
phrases = [
("go on","phrasal verb","To keep doing something.",["went on"],"Colin went on"),
("stand still","phrase","To not move.",["stood still"],"Dickon paused in what he was doing and stood still"),
("burst open","phrasal verb","To open suddenly and wide.",["burst open"],"here and there one had burst open wide"),
("jump down","phrasal verb","To come down by jumping.",["jump down"],"to jump down and deal with her"),
("tear off","phrasal verb","To pull something away.",["tear off"],"to tear the coverings off his lower limbs"),
("think better of","idiom","To change your mind and decide not to do something.",["thought better of"],"he evidently thought better of it"),
("burst forth","phrasal verb","To speak suddenly.",["burst forth"],"he burst forth, “th’ lies folk tells!"),
]
