words = [
("revealed","past-tense verb","Showed what was hidden."),
("conveyed","past participle","Made known, without words or in a quiet way."),
("gibberish","noun","Talk that has no meaning, or that someone cannot understand."),
("secrete","verb","To hide something. Here, the robin hides himself in a bush."),
("disconcerting","adjective","Making you feel uneasy or confused."),
("fledged","adjective","Having grown feathers and able to fly."),
("brooded","past participle","Covered with wings to keep warm. Here, 'brooded over by a great peace' means filled with peace."),
("restive","adjective","Not able to keep still; restless."),
("inordinately","adverb","Much more than usual."),
("boudoir","noun","A woman's private sitting room or bedroom."),
("pilgrimage","noun","A journey to a special place. Here, Mary's first walk through the empty rooms."),
("weird","adjective","Very strange."),
("impress","verb","To make someone feel respect or interest."),
("fixedly","adverb","Without moving the eyes away."),
("dresser","noun","A big kitchen table or piece of furniture with shelves, used for dishes."),
("unaccustomed","adjective","Not used to something."),
("unceasingly","adverb","Without stopping."),
("tilted","past participle","Leaned to one side."),
("horrified","adjective","Very shocked and afraid."),
("outbreak","noun","A sudden start of something, such as shouting."),
("galleries","plural noun","Long rooms or halls, often for showing pictures."),
("parrot","noun","A bird with bright feathers that can copy words."),
]
paras = [
(26,2,"And the secret garden bloomed and bloomed",
 "The robin's mate sits on eggs in the nest. The robin and his mate feel that everything in the garden understands how precious eggs are.",
 "And the secret garden bloomed and bloomed, and every morning showed new wonders. In the robin's nest there were eggs, and the robin's mate sat upon them, keeping them warm with her feathery little breast and careful wings. At first she was very nervous, and the robin himself watched angrily. Even Dickon did not go near the close-grown corner in those days. He waited until, by some quiet mysterious spell, he seemed to have made the little pair understand that in the garden there was nothing which was not quite like themselves. Nothing there failed to understand the wonderfulness of what was happening to them, the great, tender, terrible, heartbreaking beauty and seriousness of Eggs. If there had been one person in that garden who had not known, deep inside, that if an Egg were taken away or hurt the whole world would whirl round and crash through space and come to an end, and if there had been even one who did not feel it and act as it demanded, there could have been no happiness even in that golden springtime air. But they all knew it and felt it, and the robin and his mate knew they knew it.",
 ["indignantly","conveyed","solemnity"]),
(26,4,"But at the outset it seemed necessary to be on guard",
 "The robin is afraid of Mary and Colin at first. He sees Colin move in a strange slow way and thinks he may be getting ready to pounce, like a cat.",
 "But at the start it seemed necessary to be on guard against the other two. First, the boy creature did not come into the garden on his legs. He was pushed in on a thing with wheels, and the skins of wild animals were thrown over him. That in itself was doubtful. Then when he began to stand up and move about, he did it in a strange way that was new to him, and the others seemed to have to help him. The robin used to hide himself in a bush and watch this anxiously, his head tilted first on one side and then on the other. He thought that the slow movements might mean that the boy was getting ready to pounce, as cats do. When cats are getting ready to pounce they creep over the ground very slowly. The robin talked this over with his mate a great deal for a few days. After that he decided not to speak of it, because her fear was so great that he was afraid it might hurt the Eggs.",
 ["outset","secrete","pounce","unaccustomed"]),
(26,39,"Because it doesn’t make me angry any more to see her laughing",
 "Colin says he keeps the curtain open because it no longer makes him angry to see his mother laughing. He saw her in the moonlight and liked to look at her.",
 "'Because it does not make me angry any more to see her laughing. I woke up when it was bright moonlight two nights ago. I felt as if the Magic was filling the room and making everything so splendid that I could not lie still. I got up and looked out of the window. The room was quite light and there was a patch of moonlight on the curtain, and somehow that made me go and pull the cord. She looked right down at me as if she were laughing because she was glad I was standing there. It made me like to look at her. I want to see her laughing like that all the time. I think she must have been a sort of Magic person perhaps.'",
 ["moonlight"]),
]
sents = [
("If there had been one person in that garden who had not known",
 "If there had been even one person in that garden who had not known.",
 "'If there had been ... who had not known' is about the past and what did not happen; 'who had not known' tells about the person."),
("so the queer gibberish he used when he spoke to humans",
 "so the strange talk he used with humans.",
 "'so' joins this to the reason before it; 'queer gibberish' is odd talk that has no meaning to the robin, and 'he used' is a short clause telling which talk."),
]
phrases = [
("on guard","idiom","Ready to protect yourself from danger.",["on guard"],"necessary to be on guard against the other two"),
("get up","phrasal verb","To rise from a sofa, chair or bed.",["get up"],"it was not safe to get up and walk about"),
("find out","phrasal verb","To learn a fact that was hidden.",["found me out"],"Mrs. Medlock nearly found me out"),
("start up","phrasal verb","To jump up suddenly.",["started up"],"Colin started up on his sofa"),
("ramble about","phrasal verb","To walk around without a plan.",["ramble about"],"We will ramble about every rainy day"),
]
