words = [
("astounding","adjective","Very surprising."),
("hypochondriac","noun","A person who is always afraid that he is ill, even when he is not."),
("detestation","noun","Very strong hate."),
("circumstances","plural noun","The things that happen around a person and affect his life."),
("thistle","noun","A wild plant with sharp prickles and purple flowers."),
("fjords","plural noun","Long, narrow arms of the sea between high rocky hills, in Norway."),
("gentians","plural noun","Mountain flowers that are a deep blue."),
("rift","noun","A narrow opening or crack."),
("luscious","adjective","Rich, sweet and pleasant."),
("stagnant","adjective","Not moving or flowing; still and dirty. Said of water."),
("reposeful","adjective","Calm and restful."),
("verdure","noun","Fresh green plants and leaves."),
("terrace","noun","A flat, level place beside a house or by the water."),
("salver","noun","A flat tray, used for carrying letters or food."),
("sovereign","noun","An old British gold coin."),
("languidly","adverb","In a slow, weak way, without energy."),
("embowered","adjective","Shut in by leafy branches, like a shady room."),
("portal","noun","A grand door or gate."),
("suppressed","adjective","Held back so that it is not heard."),
("scuffling","adjective","Making the sound of feet moving about in a rough way."),
("headlong","adverb","Fast and without thinking."),
("significant","adjective","Having a special meaning."),
("shrewdly","adverb","In a clever way that shows good judgment."),
("stepladder","noun","A short ladder with steps, which stands by itself."),
("villa","noun","A large house in the country, often in a warm place."),
("sup","verb","To drink a little at a time."),
("shrinking","noun","A feeling of wanting to draw away from something."),
("flustered","adjective","Nervous and confused."),
("encircled","past participle","Surrounded by a ring."),
("nudging","adjective","Pushing someone lightly with the elbow."),
("laurels","plural noun","Bushes with shiny dark green leaves."),
("remote","adjective","Far away and quiet."),
("germ","noun","A very small living thing that can cause disease."),
("digestion","noun","The way the body breaks down food in the stomach."),
]
paras = [
(28,2,"In each century since the beginning of the world wonderful things have been discovered",
 "The author says that people at first refuse to believe new things, and later they happen. One new thing is that thoughts are as powerful as electric batteries and can be as good as sunlight or as bad as poison.",
 "In each century since the beginning of the world, wonderful things have been found. In the last century more amazing things were found out than in any century before. In this new century hundreds of things that are still more surprising will be brought to light. At first people refuse to believe that a strange new thing can be done. Then they begin to hope it can be done. Then they see it can be done. Then it is done, and all the world wonders why it was not done centuries ago. One of the new things people began to find out in the last century was that thoughts, just mere thoughts, are as powerful as electric batteries. They are as good for one as sunlight is, or as bad for one as poison. To let a sad thought or a bad one get into your mind is as dangerous as letting a scarlet fever germ get into your body. If you let it stay there after it has got in, you may never get over it as long as you live.",
 ["astounding","electric","germ","scarlet"]),
(28,3,"So long as Mistress Mary’s mind was full of disagreeable thoughts",
 "While Mary's mind was full of unpleasant thoughts she was a sickly, unhappy child. When her mind filled with robins, cottages, springtime and the garden, there was no room left for them.",
 "As long as Mistress Mary's mind was full of unpleasant thoughts, about her dislikes and sour opinions of people and her decision not to be pleased by or interested in anything, she was a yellow-faced, sickly, bored and unhappy child. But things were very kind to her, though she was not at all aware of it. They began to push her about for her own good. Slowly her mind filled itself with robins, and moorland cottages crowded with children, and queer bad-tempered old gardeners, and common little Yorkshire housemaids. It filled with springtime and with secret gardens coming alive day by day, and also with a moor boy and his creatures. Then there was no room left for the unpleasant thoughts which affected her liver and her digestion and made her yellow and tired.",
 ["disagreeable","circumstances","digestion"]),
(28,9,"As he sat gazing into the clear running of the water",
 "Mr Craven sits by a stream in the valley and looks at blue forget-me-nots. His mind and body become quiet, and something seems to be freed in him.",
 "As he sat looking into the clear running of the water, Archibald Craven slowly felt his mind and body both grow quiet, as quiet as the valley itself. He wondered if he were going to sleep, but he was not. He sat and looked at the sunlit water, and his eyes began to see things growing at its edge. There was one lovely mass of blue forget-me-nots growing so close to the stream that its leaves were wet. He found himself looking at these, as he remembered he had looked at such things years ago. He was thinking tenderly how lovely it was and what wonders of blue its hundreds of little blossoms were. He did not know that just that simple thought was slowly filling his mind, filling and filling it until other things were softly pushed aside. It was as if a sweet clear spring had begun to rise in a still, dirty pool, and had risen and risen until at last it swept the dark water away. But of course he did not think of this himself. He only knew that the valley seemed to grow quieter and quieter as he sat and stared at the bright delicate blueness. He did not know how long he sat there or what was happening to him. At last he moved as if he were waking up, and he got up slowly and stood on the moss carpet, drawing a long, deep, soft breath and wondering at himself. Something seemed to have been untied and set free in him, very quietly.",
 ["forget-me-nots","stagnant","released"]),
(28,23,"And then the dream ended. But he did not awaken.",
 "The dream ends, and Mr Craven sleeps until morning. An Italian servant brings him letters, and he remembers the dream.",
 "And then the dream ended. But he did not wake. He slept soundly and sweetly all through the lovely night. When he did wake at last, it was bright morning and a servant was standing staring at him. He was an Italian servant. He was used, as all the servants of the villa were, to accepting without question any strange thing his foreign master might do. No one ever knew when he would go out or come in, or where he would choose to sleep, or if he would roam about the garden or lie in the boat on the lake all night. The man held a tray with some letters on it, and he waited quietly until Mr. Craven took them. When he had gone away, Mr. Craven sat a few moments holding them in his hand and looking at the lake. His strange calm was still upon him, and something more. It was a lightness, as if the cruel thing which had been done had not happened as he thought, as if something had changed. He was remembering the dream, the real, real dream.",
 ["salver","roam","accustomed"]),
(28,76,"The place was a wilderness of autumn gold and purple and violet blue",
 "The garden is full of autumn colour. Mr Craven sees late lilies and late roses, and the yellowing trees make the garden feel like a temple.",
 "The place was a wilderness of autumn gold and purple and violet blue and flaming scarlet. On every side were sheaves of late lilies standing together, lilies which were white or white and ruby. He remembered well when the first of them had been planted, that just at this season of the year their late glories should show themselves. Late roses climbed and hung and clustered, and the sunshine deepening the colour of the yellowing trees made one feel that one stood in a temple shut in by leafy branches.",
 ["wilderness","embowered"]),
]
sents = [
("At first people refuse to believe that a strange new thing can be done",
 "At first people will not believe that a strange new thing can be done.",
 "'At first ... then ... then' puts the steps in order; 'that a strange new thing can be done' is a passive clause that tells what they refuse to believe."),
("he had never tried to put any other thoughts in the place",
 "He had never tried to put any other thoughts in the place.",
 "'had never tried to put' uses 'had' with a past participle to tell about the past before the story's time; 'the dark ones' stands for 'the dark thoughts'."),
("Of course this was the wrong Magic —to begin by saying “too late.”",
 "Of course this was the wrong Magic, to begin by saying 'too late'.",
 "The words after the dash explain what 'the wrong Magic' was; 'to begin by saying' is 'to begin' plus 'by' and an '-ing' verb."),
("Aye, that I did,” he answered with a shrewdly significant air",
 "Yes, I did, he answered, as if he knew something important.",
 "'that I did' puts the object first for stress, in Yorkshire speech, and means 'I did that'; 'with a ... air' tells how he spoke."),
]
phrases = [
("find out","phrasal verb","To learn a fact that you did not know.",["found out"],"more amazing things were found out than in any century before"),
("get over","phrasal verb","To become well again after something bad.",["get over"],"you may never get over it as long as you live"),
("push out","phrasal verb","To make something leave a place.",["push out"],"push it out by putting in an agreeable"),
("throw oneself down","idiom","To lie down suddenly, because you are tired.",["thrown himself down"],"had thrown himself down to rest"),
("wander about","phrasal verb","To walk around with no plan.",["wandering about"],"a man wandering about certain faraway beautiful places"),
("come back","phrasal verb","To return.",["come back","came back"],"it came back like a sound from a golden flute"),
("burst through","phrasal verb","To go through something with force.",["burst through"],"a boy burst through it at full speed"),
("make out","phrasal verb","To understand a person.",["make him out"],"can exactly make him out"),
("on the spot","idiom","At the place where something happens.",["on the spot"],"he was on the spot"),
]
