words = [
("absorbing","adjective","Holding all of your interest."),
("transported","past participle","Carried from one place to another."),
("rumors","plural noun","Stories that people tell, without knowing if they are true."),
("filtered","past-tense verb","Passed slowly through, a little at a time."),
("notwithstanding","adverb","In spite of that."),
("uncanny","adjective","Strange, in a way that is a little frightening."),
("humped","adjective","With a lump on the back."),
("menagerie","noun","A collection of wild animals kept together."),
("leniently","adverb","In a kind, mild way."),
("servitor","noun","A servant."),
("lordly","adjective","Proud and acting like a lord."),
("trample","verb","To walk over something or someone in a rough way."),
("morbid","adjective","Having gloomy thoughts, especially about sickness and death."),
("garlands","plural noun","Rings of flowers and leaves."),
("procession","noun","A long line of people moving along together."),
("tendrils","plural noun","Thin curling parts of a climbing plant."),
("privately","adverb","In one's own mind, without telling others."),
("exaggerated","adjective","Made to seem bigger or worse than the truth."),
("fanciful","adjective","Made up from the imagination."),
("hitherto","adverb","Until this time."),
("undignified","adjective","Not serious or proper; silly."),
("consort","noun","The husband or wife of a king or queen. 'Prince Consort' was the title of Queen Victoria's husband."),
("thrill","noun","A strong feeling of excitement."),
("lilac","noun","A bush with sweet-smelling purple or white flowers."),
("outspread","adjective","Spread out wide."),
]
paras = [
(21,13,"It was perhaps well he had been prepared or he might have been startled",
 "Mr Roach goes into Colin's room. A crow on a chair says 'Caw' and he almost jumps back.",
 "It was perhaps good that he had been told what to expect, or he might have been startled. When the bedroom door was opened, a large crow sat on the high back of a carved chair. It seemed quite at home there. It said 'Caw, Caw' quite loudly to tell that a visitor had come in. In spite of Mrs. Medlock's warning, Mr. Roach only just stopped himself from jumping backward, which would have been very undignified.",
 ["prepared","undignified","announced"]),
(21,41,"That morning when you ran in and said",
 "Colin tells Mary what he pictured when she said 'It's come!'. He imagined a happy crowd of people with flowers and pipes.",
 "'That morning when you ran in and said \"It has come! It has come!\" you made me feel quite strange. It sounded as if things were coming with a great procession and big bursts and waves of music. I have a picture like it in one of my books. It has crowds of lovely people and children with garlands and branches with blossoms on them. Everyone is laughing and dancing and crowding and playing on pipes. That was why I said, \"Perhaps we shall hear golden trumpets,\" and told you to throw open the window.'",
 ["procession","wafts","garlands"]),
(21,71,"But Colin had actually dropped back against his cushions",
 "Colin covers his eyes until the chair is inside the garden. Then he looks around and sees the green leaves, the flowers and the sun.",
 "But Colin had actually dropped back against his cushions, even though he gasped with delight. He had covered his eyes with his hands and held them there, shutting out everything, until they were inside and the chair stopped as if by magic and the door was closed. Not until then did he take them away and look round and round and round, as Dickon and Mary had done. Over walls and earth and trees and swinging sprays and tendrils the fair green veil of tender little leaves had crept. In the grass under the trees and the gray urns in the alcoves, and here and there everywhere, were touches or splashes of gold and purple and white. The trees were showing pink and snow above his head. There were fluttering of wings and faint sweet pipes and humming and scents and scents. The sun fell warm upon his face like a hand with a lovely touch. In wonder Mary and Dickon stood and stared at him. He looked so strange and different because a pink glow of color had actually crept all over him, ivory face and neck and hands and all.",
 ["tendrils","veil","ivory"]),
]
sents = [
("Shut in and morbid as his life had been, Colin had more imagination",
 "Although his life had been shut in and gloomy, Colin had more imagination than Mary.",
 "'Shut in and morbid as his life had been' puts the describing words first and means 'although his life had been'; 'than she had' finishes the comparison."),
("I’d rather give up the case this moment, sir, than even stay here",
 "I would rather stop working on this case right now than even stay here.",
 "'would rather ... than' shows a choice; 'give up the case' means stop caring for the patient."),
]
phrases = [
("drop in","phrasal verb","To visit for a short time.",["dropped in"],"who dropped in to inspect him"),
("call in","phrasal verb","To visit someone for a short time.",["call in"],"I’ll call in again later in the afternoon"),
("take out","phrasal verb","To lead someone out of a place.",["took him out"],"Mrs. Medlock took him out of the room"),
("wind in and out","phrase","To follow a path that bends this way and that.",["wound in and out"],"they wound in and out among the shrubbery"),
("look on","phrasal verb","To watch without taking part.",["looking on"],"The little girl from India was sitting on a big footstool looking on"),
("grow out of","phrasal verb","To stop a habit as you grow older.",["grow out of"],"Perhaps he’ll grow out of it"),
]
