words = [
("twilight","noun","The soft, dim light after the sun has gone down."),
("enclosed","adjective","Closed in on all sides, as by a wall."),
("haze","noun","A thin mist that makes things hard to see clearly."),
("waxy","adjective","Pale and smooth like wax."),
("domain","noun","A place that belongs to someone. Here it means the secret garden."),
("heartless","adverb","Without kindness."),
("pother","noun","A state of worry and fuss."),
("currants","plural noun","Small dried black fruits, used in cakes and buns."),
("bounteous","adjective","Giving freely and a lot; very generous."),
("copious","adjective","In large amounts."),
("bloated","adjective","Swollen and puffed up."),
("sensitive","adjective","Easily hurt or upset."),
("abnormal","adjective","Not normal; strange."),
("sizzling","adjective","Making a hissing sound as it cooks in heat."),
("clotted","adjective","Thick. 'Clotted cream' is very thick cream."),
("pantry","noun","A small room where food and dishes are kept."),
("mystic","adjective","Having a secret or holy meaning."),
("tinge","noun","A small amount of a colour."),
("wrestler","noun","A person who fights by holding and throwing the other person."),
("muscle","noun","A part of the body that lets you move and be strong."),
("revelation","noun","The telling of something that was hidden."),
("riot","noun","Wild and noisy action. Here, great excited joy."),
("tempt","verb","To make someone want something."),
("starvation","noun","Suffering or dying from having no food."),
("severe","adjective","Strict and serious."),
("repress","verb","To hold back a feeling or a sound."),
("glummest","adjective","The most gloomy and unhappy."),
("nourishment","noun","Food that keeps a body healthy and growing."),
("trifle","verb","To play with something, not taking it seriously."),
("satisfying","adjective","Giving you all that you want, so that you are pleased."),
("ceremony","noun","A set of acts done in a fixed way on a special occasion."),
("bounties","plural noun","Gifts given freely and in large amounts."),
("grandeur","noun","Great and proud style."),
("fowl","noun","A bird such as a chicken, used for food."),
]
paras = [
(25,2,"The secret garden was not the only one Dickon worked in",
 "Dickon also has a garden at the cottage with a low stone wall. He grows vegetables there for his mother and works with his creatures.",
 "The secret garden was not the only one Dickon worked in. Round the cottage on the moor there was a piece of ground closed in by a low wall of rough stones. Dickon worked there planting or tending potatoes and cabbages, turnips and carrots and herbs for his mother. He worked early in the morning, late in the fading twilight, and on all the days Colin and Mary did not see him. In the company of his creatures he did wonders there, and it seemed he was never tired of doing them. While he dug or weeded he whistled or sang bits of Yorkshire moor songs, or talked to Soot or Captain or the brothers and sisters he had taught to help him.",
 ["twilight","enclosed","tending"]),
(25,14,"He does it to keep them from guessin’ what’s happened",
 "Dickon explains that Colin still complains so that no one guesses what has happened. Colin wants to show his father that he is as straight as other boys.",
 "'He does it to keep them from guessing what has happened. If the doctor knew he had found out he could stand on his feet, he would likely write and tell Mr. Craven. Master Colin is saving the secret to tell himself. He is going to practise his Magic on his legs every day till his father comes back. Then he is going to march into his room and show him he is as straight as other boys. But he and Miss Mary think it is best to do a bit of groaning and fretting now and then to throw people off the scent.'",
 ["groanin","scent"]),
(25,67,"Look!” exclaimed Mrs. Medlock indignantly. “Eh! I’m moithered to death with them.",
 "Mrs Medlock complains about Mary and Colin. One day they eat a lot, and the next day they leave the best meals.",
 "'Look!' said Mrs. Medlock angrily. 'Eh! I am worn out with them. They are a pair of young devils. One day they are bursting their jackets, and the next they turn up their noses at the best meals Cook can tempt them with. Not a mouthful of that lovely young fowl and bread sauce did they put a fork into yesterday. The poor woman has made up a pudding for them, and back it is sent. She almost cried.'",
 ["moithered","fowl","tempt"]),
]
sents = [
("Anything’ll grow for him. His ’taters and cabbages is twice th’ size",
 "Anything will grow for him. His potatoes and cabbages are twice the size of other people's.",
 "'Anything'll' is 'Anything will'; 'is' for 'are' and ''taters' for 'potatoes' are Yorkshire speech."),
("He was given to using rather grownup phrases at times",
 "He often used rather grownup words.",
 "'was given to using' means 'often did'; 'to' here is followed by an '-ing' word."),
]
phrases = [
("take a fancy to","idiom","To start to like something or someone.",["taken a fancy to"],"had taken a fancy to going out into the grounds"),
("play acting","phrase","Acting as if something were true when it is not.",["play actin’"],"nothin’ children likes as much as play actin’"),
("fill out","phrasal verb","To become fatter.",["filled out","fillin’ out"],"since she’s filled out and lost her ugly little sour look"),
("take off the edge","idiom","To make a strong feeling less strong, such as hunger.",["take off th’ edge"],"take off th’ edge o’ their hunger"),
("send away","phrasal verb","To make something go away; to not use it.",["send away"],"We can send away some of the lunch"),
("throw off the scent","idiom","To make people lose the trail or guess wrongly.",["throw folk off th’ scent"],"to throw folk off th’ scent"),
]
