words = [
("abiding","adjective","Lasting for a long time."),
("incantations","plural noun","Words said or sung over and over, as if to make magic."),
("devouring","adjective","Looking hungrily, as if wanting to take in everything."),
("rapturous","adjective","Full of great joy."),
("doxology","noun","A short Christian song of praise to God, sung in church."),
("reverence","noun","Deep respect, especially for God or holy things."),
("dappling","present participle","Marking with spots of light and shade."),
("gloating","adjective","Looking with great pleasure."),
("bewildered","adjective","Confused and not sure what to think."),
("adoration","noun","Very great love and respect."),
("tremulously","adverb","In a shaking, unsteady way."),
("bandy","adjective","Bent outward at the knees."),
("worrit","verb","A Yorkshire way to say 'worry'."),
("ruddy","adjective","Red and healthy-looking."),
("lecture","noun","A talk given to teach people about something."),
("rasping","adjective","Rough and harsh in sound."),
("unaffected","adjective","Natural; not trying to seem different from what you are."),
("instinct","noun","A natural feeling that tells you what to do without being taught."),
("appreciative","adjective","Showing thanks or pleasure."),
("aught","pronoun","An old word meaning 'anything'."),
("wilt","verb","An old form of 'will' used with 'thou'. 'Wilt tha'' means 'will you'."),
("drumsticks","plural noun","Sticks used to beat a drum; here, thin legs."),
]
paras = [
(27,18,"Just this minute,” said Colin, “all at once I remembered it myself",
 "Colin suddenly feels sure he is well. He had stood up to see if it was real.",
 "'Just this minute,' said Colin, 'all at once I remembered it myself, when I looked at my hand digging with the trowel. I had to stand up on my feet to see if it was real. And it is real! I am well, I am well!'",
 ["trowel"]),
(27,38,"And they sang it again, and Mary and Colin lifted their voices",
 "They sing the Doxology again. Ben Weatherstaff joins in strongly and his face shows strong feeling, as when he learned Colin was not a cripple.",
 "And they sang it again. Mary and Colin lifted their voices as musically as they could, and Dickon's grew quite loud and beautiful. At the second line Ben Weatherstaff cleared his throat roughly. At the third line he joined in with so much force that it seemed almost wild. When the 'Amen' came to an end, Mary saw that the same thing had happened to him which had happened when he found out that Colin was not a cripple. His chin was twitching, and he was staring and winking, and his leathery old cheeks were wet.",
 ["raspingly","vigor","savage","cripple"]),
(27,66,"That I do, lad,” she answered",
 "Susan Sowerby tells Colin that she does believe in Magic, though she never knew it by that name. She says the same Good Thing that makes seeds swell and the sun shine made him well.",
 "'That I do, lad,' she answered. 'I never knew it by that name, but what does the name matter? I am sure they call it a different name in France and a different one in Germany. The same thing that made the seeds swell and the sun shine made you a well lad, and it is the Good Thing. It is not like us poor fools who think it matters if we are called out of our names. The Big Good Thing does not stop to worry, bless you. It goes on making worlds by the million, worlds like us. Never you stop believing in the Big Good Thing and knowing the world is full of it. Call it what you like. You were singing to it when I came into the garden.'",
 ["warrant","worrit"]),
]
sents = [
("is that a chap can get up an’ say aught he pleases",
 "The best thing about giving talks is that a man can get up and say anything he likes.",
 "'is that' starts a clause that tells what the best thing is; 'aught' is an old word for 'anything'; 'a chap' is a man."),
("a pretty woman could be th’ mother o’ such a fou’ little lass",
 "A pretty woman could be the mother of such an ugly little girl, she said, is not sensible.",
 "The words before this say 'It doesn't stand to reason that', which means 'it is not sensible to think that'; 'fou'' is Martha's word for 'foul' or ugly."),
]
phrases = [
("hold forth","phrasal verb","To talk for a long time in front of people.",["held forth"],"when Colin held forth under his tree"),
("fall to","phrasal verb","To begin eagerly to work.",["fell to work"],"they fell to work"),
("pull off","phrasal verb","To take off something.",["pulled off"],"He pulled off his cap"),
("take off","phrasal verb","To remove clothes or a hat.",["take off","took off"],"Colin took off his cap"),
("join in","phrasal verb","To start to do something with other people.",["joined in"],"he joined in with such vigor"),
("stand to reason","idiom","To be sensible; to be what clear thinking says is true.",["stand to reason"],"It doesn’t stand to reason that a pretty woman"),
]
