words = [
("irritably","adverb","In a way that shows you are annoyed."),
("insane","adjective","Not sane; out of one's mind."),
("spires","plural noun","Tall, thin points. Here, flowers that grow in long tall shapes."),
("unscrupulous","adjective","Willing to do wrong things to get what you want."),
("bromide","noun","A medicine that makes a person calm and sleepy."),
("soothing","adjective","Making someone feel calm."),
("volubly","adverb","In a way that uses many words, talking easily."),
("shrewd","adjective","Clever about people and money; having good sense."),
("luxuriously","adverb","In a way that feels very pleasant and comfortable."),
("concealing","present participle","Hiding."),
("recluse","noun","A person who lives alone and keeps away from other people."),
("austerely","adverb","In a strict, serious way."),
("ravenous","adjective","Very hungry. Here, it describes how the lamb drinks."),
("ecstasy","noun","A feeling of very great joy."),
("hoarse","adjective","Rough and low in sound, as a voice that is not clear."),
("bleat","noun","The thin cry of a lamb or sheep."),
("columbine","noun","A garden flower with petals shaped like small bells with tails."),
("snapdragon","noun","A garden flower whose blooms open and close like a mouth."),
("signet","noun","A ring with a small mark or seal on it. 'Signet rings' were worn by important people."),
("salaams","plural noun","Deep bows with the hand at the forehead, used as a greeting in India."),
("sulky","adjective","Quiet and bad-tempered because you are not pleased."),
("shrieked","past-tense verb","Cried out with a loud, high sound."),
("chilly","adjective","A little cold."),
("primrose","noun","A small pale yellow spring flower."),
]
paras = [
(20,4,"Well, sir,” answered Mrs. Medlock, “you’ll scarcely believe your eyes",
 "Mrs Medlock tells Dr Craven that Mary has changed Colin. Mary stood up to him last night and made him stop screaming.",
 "'Well, sir,' answered Mrs. Medlock, 'you will hardly believe your eyes when you see him. That plain sour-faced child, who is almost as bad as he is, has just put a spell on him. There is no telling how she did it. The Lord knows she is nothing to look at, and you hardly ever hear her speak. But she did what none of us dare to do. She flew at him like a little cat last night, and stamped her feet and ordered him to stop screaming. Somehow she startled him so much that he did stop. And this afternoon, well, just come up and see, sir. It is hard to believe.'",
 ["bewitched","crediting","stamped"]),
(20,37,"She’s got a way with her, has Susan,” she went on quite volubly",
 "Mrs Medlock tells Dr Craven what Susan Sowerby once told her children. The world is like an orange, and no one owns the whole orange.",
 "'She has a way with her, has Susan,' she went on, talking freely. 'I have been thinking all morning of one thing she said yesterday. She says, \"Once when I was giving the children a bit of a talking-to after they had been fighting, I said to them all, 'When I was at school my geography said that the world was shaped like an orange. I found out before I was ten that the whole orange does not belong to nobody. No one owns more than his bit of a quarter, and there are times when it seems there are not enough quarters to go round. But don't any of you think that you own the whole orange, or you will find out you are mistaken. You will not find it out without hard knocks. What children learn from children is that there is no sense in grabbing at the whole orange, peel and all. If you do, you will likely not get even the pips, and they are too bitter to eat.'\"'",
 ["volubly","preach","jography","pips"]),
(20,52,"And then she paused for breath",
 "Dickon found a newborn lamb on the moor three days ago. He fed it with warm milk, and Mary held it on her lap.",
 "And then she stopped for breath. Dickon had found the newborn lamb three days before, lying by its dead mother among the gorse bushes on the moor. It was not the first lamb without a mother that he had found, and he knew what to do with it. He had taken it to the cottage wrapped in his jacket, and had let it lie near the fire and had fed it with warm milk. It was a soft thing with a darling silly baby face and legs rather long for its body. Dickon had carried it over the moor in his arms, and its feeding bottle was in his pocket with a squirrel. When Mary had sat under a tree with its limp warmth in her lap, she had felt too full of strange joy to speak. A lamb, a lamb! A living lamb who lay on your lap like a baby!",
 ["limp","huddled","gorse"]),
]
sents = [
("It is not to be wondered at that his doctor felt somewhat startled",
 "It is no surprise that his doctor felt a little startled.",
 "'it is not to be wondered at that ...' is a formal way to say 'it is not strange that'; 'that' starts the reason."),
("If this tiresome hysterical boy should chance to get well",
 "If this tiresome, wild boy happened to get well, the doctor would lose all hope of getting the house.",
 "'should chance to get well' is a formal 'if' clause meaning 'if by chance he gets well'; 'would lose' shows the result."),
]
phrases = [
("send for","phrasal verb","To ask for someone to come.",["sent for"],"Dr. Craven had been sent for the morning after"),
("break into","phrasal verb","To suddenly start doing something such as crying.",["break into"],"ready to break into fresh sobbing"),
("speak up","phrasal verb","To say something suddenly and clearly.",["spoke up"],"Mary spoke up suddenly"),
("go round","phrasal verb","To be enough for everyone.",["go round"],"not enow quarters to go round"),
("curl up","phrasal verb","To lie with the body bent into a round shape.",["curled up"],"Captain curled up near Dickon"),
("pour in","phrasal verb","To come in a great flow.",["pouring in","pouring through"],"with the morning air pouring in upon them"),
]
