# sentence notes: (chapter, context, simple, grammar)
SN = [
# ch3
(3,"Even the tiger hides when little Tabaqui goes mad",
 "When Tabaqui goes mad, even the tiger hides.",
 "'Even' stresses a surprise: the tiger is the strongest animal, but he hides. 'When' starts a clause about time."),
(3,"The fool has had no more sense than to jump at a woodcutters’ campfire",
 "The fool had so little sense that he jumped at a woodcutters' campfire.",
 "'No more sense than to jump...' means 'only enough sense to jump', and says the tiger acted in a silly way."),
(3,"A wolf accustomed to moving his own cubs can, if necessary, mouth an egg",
 "A wolf who is used to carrying his own cubs can hold an egg in his mouth, if he has to.",
 "'Accustomed to moving' is a short form of 'who is accustomed to moving'; 'if necessary' is a short form of 'if it is necessary'."),
(3,"was there ever a wolf that could boast of a man’s cub",
 "Has any wolf ever been able to say proudly that she has a man's cub among her children?",
 "This is a question that expects the answer 'no'. 'Was there ever...?' means 'there never was...'."),
(3,"Shere Khan might have faced Father Wolf, but he could not stand up",
 "Shere Khan could perhaps have fought Father Wolf, but he could not fight Mother Wolf.",
 "'Might have + past participle' (might have faced) talks about something that was possible in the past, but did not happen."),
(3,"it is the man-cub who has lived too long",
 "It is the man-cub who has lived too long.",
 "This is a cleft sentence: 'It is ... who ...' puts stress on the man-cub as the one who should not have lived this long."),
(3,"Shere Khan would flatter them and wonder that such fine young hunters",
 "Shere Khan used to say nice things to them that were not true, and he would say it was strange that such fine young hunters were happy to be led by a dying wolf and a man's cub.",
 "'Would + verb' tells what happened again and again in the past. 'Wonder that...' is followed by a that-clause."),
(3,"all but your brother in blood, I promise that when I am a man",
 "I was almost your brother by blood, so I promise that when I am a man among men, I will not betray you.",
 "'All but' means 'almost'. After 'when' we use the present tense (I am) for the future, as in 'when I am a man'."),
# ch4
(4,"The big, serious, old brown bear was delighted to have so quick a pupil",
 "The big, serious, old brown bear was very happy to have a pupil who learned so fast.",
 "'So quick a pupil' puts 'a' after the adjective: 'so + adjective + a + noun'. It means 'a pupil who is so quick'."),
(4,"Better he should be bruised from head to foot by me who love him",
 "It is better that he is hurt all over by me, who love him, than that he comes to harm through ignorance.",
 "'Better he should be...than that he should...' is a short form of 'It is better that he should be... than that he should...'."),
(4,"Had they been alone they could have gone twice as fast",
 "If they had been alone, they could have gone twice as fast.",
 "'Had they been...' means 'If they had been...'. It talks about something that did not happen."),
(4,"Unless and until they drop him from the branches in sport",
 "As long as they do not drop him from the branches for fun, or kill him because they have nothing to do, I have no fear for the man-cub.",
 "'Unless and until' means 'if they do not... and up to the time when they do'. The main clause 'I have no fear' comes after it."),
(4,"I am more likely to give help than to ask it",
 "I will help more often than I ask for help.",
 "'More ... than ...' compares two things: 'to give help' is compared with 'to ask it'. 'Likely to + verb' says that something will probably happen."),
(4,"Would that Baloo were here; but we must do what we can",
 "I wish that Baloo were here; but we must do what we can.",
 "'Would that + past' (were) is an old way to say 'I wish that...'. It talks about something that is not true now."),
(4,"Kaa was everything that the monkeys feared in the jungle",
 "Kaa was all the things that the monkeys were afraid of in the jungle.",
 "'Everything that the monkeys feared' has a relative clause ('that the monkeys feared') that tells which things."),
(4,"In a little time, had I stayed, I should have walked down his throat",
 "In a short time, if I had stayed, I would have walked down his throat.",
 "'Had I stayed' means 'If I had stayed'. 'Should have walked' (here the same as 'would have') says what would have happened, but did not."),
# ch5
(5,"Mowgli had not the faintest idea of the difference that caste makes",
 "Mowgli did not have the smallest idea of the difference that caste makes between one man and another.",
 "'Had not' is an old way to make a negative: it means 'did not have'. The relative clause 'that caste makes' tells which difference."),
(5,"If thou art so wise, better bring his hide to Khanhiwara",
 "If you are so wise, you had better bring his hide to Khanhiwara.",
 "'If thou art' is an old way of saying 'if you are'. 'Better bring' is a short form of 'You had better bring', which gives advice."),
(5,"I might have known that thou wouldst not forget me",
 "I should have known that you would not forget me.",
 "'Might have + past participle' here means 'could have known'. It says that Mowgli did not think about it, but should have."),
(5,"slipped off Rama’s neck, laying about him right and left",
 "Mowgli waited for the right time, then slid off Rama's neck and hit out on both sides with his stick.",
 "'Laying about him right and left' uses a present participle to say what he did at the same time as he slipped off."),
(5,"if he had been ten years younger he would have taken his chance",
 "To be fair to Buldeo, if he had been ten years younger, he would have faced Akela.",
 "This is a third conditional: 'if + had been..., would have + past participle'. It talks about something that did not happen."),
(5,"Not for nothing are ye called the Free People",
 "You are called the Free People for a good reason.",
 "'Not for nothing' puts the negative first, so the verb comes before the subject: 'are ye called'. It means 'for a good reason'."),
# ch6
(6,"Sea Catch had just finished his forty-fifth fight one spring when Matkah",
 "One spring, Sea Catch had just finished his forty-fifth fight when Matkah came up out of the sea.",
 "'Had just finished' is the past perfect: it shows that one action was finished before another action (Matkah came) in the past."),
(6,"Little seals can no more swim than little children",
 "Little seals cannot swim, just as little children cannot swim.",
 "'No more ... than ...' means 'also not'. It says that two things are both not true."),
(6,"if you seals will come here year after year, of course the men",
 "If you seals come here every year, the men will of course learn about it.",
 "Here 'if you will come' means 'if you keep coming'. 'Get to know' means 'begin to know'."),
(6,"the only seal, black or white, who ever thought of looking for new islands",
 "the only seal, black or white, who ever thought of looking for new islands.",
 "The relative clause 'who ever thought of...' tells which seal. 'Thought of + -ing' (looking) is a verb with 'of' and a verb in the -ing form."),
(6,"Kotick had never fasted for four months as the big seals did every year",
 "Kotick had never gone without food for four months, as the big seals did each year.",
 "'Had never fasted' is the past perfect with 'never': it says that this had not happened before that time. 'As' compares with the big seals."),
(6,"I’ve done my best for you these five seasons past",
 "I have done my best for you for the last five seasons.",
 "'These five seasons past' shows a time up to now. The present perfect 'I've done' goes with it."),
# ch7
(7,"Rikki-tikki knew better than to waste time in staring",
 "Rikki-tikki was wise enough not to waste time looking.",
 "'Knew better than to + verb' means 'was wise enough not to do it'."),
(7,"If Teddy doesn’t pick him up by the tail, or try to put him",
 "If Teddy does not pick him up by the tail or try to put him in a cage, he will run in and out of the house all day.",
 "This is a first conditional: 'if + present (doesn't pick up), will + verb (he'll run)'. It talks about what is likely."),
(7,"If I could get up to your nest, I’d roll all your babies out",
 "If I could get up to your nest, I would roll all your babies out.",
 "This is a second conditional: 'if + past (could), would + verb'. It talks about something that is not likely."),
(7,"Not eat exactly; no. Darzee, if you have a grain of sense",
 "No, I do not exactly eat them.",
 "This answer leaves out the subject and the helper verb: 'Not eat exactly' means 'I will not exactly eat them'."),
(7,"Rikki-tikki had a right to be proud of himself",
 "Rikki-tikki had good reason to be proud of himself.",
 "'Had a right to + verb' means 'had a good reason to do it'."),
(7,"he knew that the minute they were hatched they could each kill a man",
 "He knew that, as soon as they came out of the eggs, each of them could kill a man or a mongoose.",
 "'The minute + clause' works like 'as soon as'. 'Were hatched' is the passive form."),
# ch8
(8,"Kala Nag would no more have dreamed of disobeying his shrill little orders",
 "Kala Nag would never have thought of not obeying his sharp, high little orders.",
 "'Would no more have dreamed of ... than ...' means 'would never have thought of'. It compares with the other thing that is not true."),
(8,"that thou must needs go elephant-catching on thy own account",
 "Are good brick elephant-lines and a little tent-carrying not enough for you? Must you go catching elephants too?",
 "This is a question with 'not' put in front of the subject ('Are not ... enough'). 'Must needs' is an old way of saying 'must'. 'Thou' means 'you'."),
(8,"Anyone but a mudhead who never saw the jungle would know",
 "Everyone except a fool who has never seen the jungle would know that.",
 "'Anyone but a mudhead' means 'everyone except a fool'. The relative clause 'who never saw the jungle' tells more about the mudhead."),
(8,"a private soldier would feel if he had been called out of the ranks",
 "He felt as an ordinary soldier would feel if his chief had called him out of the line and praised him.",
 "'As ... would feel if he had been called' compares his feeling to an imagined case. 'If he had been called' is the passive past perfect."),
(8,"so far away that it sounded no more than a pinhole of noise",
 "It was so far away that it sounded like only a very small hole of sound in the quiet.",
 "'So far away that ...' shows result: 'so + adjective/adverb + that + clause'. 'No more than' means 'only'."),
(8,"What never man has seen he has seen through the long night",
 "He has seen, through the long night, what no man has ever seen.",
 "The object 'What never man has seen' is put first, and 'never' comes before 'man'. This is not usual order; it adds force."),
# ch9
(9,"Imagine the feelings of Sunol if a car-horse called her a “skate,”",
 "Think how Sunol would feel if a horse that pulls a street car called her a 'skate'.",
 "'Imagine' starts a command, and 'if + past (called)' makes an imagined case. The writer asks the reader to compare the two feelings."),
(9,"Before I’d lie down, not to speak of sitting down",
 "I would never lie down, and much less sit down, and let a man fire over me.",
 "'Before I'd + verb' means 'I would never...'. 'Not to speak of' adds a stronger case: if lying down is bad, sitting is worse."),
(9,"if I was like him I could pull the guns",
 "If I were like my captain, I could pull the guns.",
 "'If I was like him' is a second conditional that talks about something that is not true. Many speakers use 'was' for 'were'."),
(9,"I know just enough to be uncomfortable, and not enough to go on",
 "I know only enough to feel bad, and not enough to go on in spite of it.",
 "'Enough to + verb' tells how much is needed. The two parts are joined by 'and not' to show a difference."),
(9,"Unless you have been there you cannot imagine what a frightening effect",
 "If you have not been there, you cannot imagine how frightening this is.",
 "'Unless' means 'if not'. 'What a ... effect' is an exclamation inside the clause that follows 'imagine'."),
(9,"Would it were so in Afghanistan",
 "I wish it were like this in Afghanistan.",
 "'Would it were...' is an old way to say 'I wish it were...'. It talks about something that is not true."),
]
