# paragraph notes: (chapter, context, mainIdea, simple, hardWords)
PN = [
(3, "The bushes rustled a little in the thicket, and Father Wolf dropped",
 "Father Wolf jumps at something in the bushes. He sees a man's cub just in time and stops in the air.",
 "The bushes made a little noise in the thicket. Father Wolf got low, with his back legs under him, ready to jump. Then, if you had been watching, you would have seen the most wonderful thing in the world: the wolf stopped in the middle of his jump. He had jumped before he saw what was there, and then he tried to stop. So he went straight up into the air, four or five feet, and came down almost in the same place where he had left the ground.",
 ["rustled","thicket","haunches","checked","bound"]),
(3, "accustomed to moving his own cubs can, if necessary, mouth an egg",
 "Father Wolf picks up the child with his mouth. He does not hurt the child at all.",
 "A wolf who is used to carrying his own cubs can hold an egg in his mouth, if he must, and not break it. So when Father Wolf's jaws closed right on the child's back, not one tooth even scratched the skin. He put the child down among the cubs.",
 ["accustomed","cubs","mouth"]),
(3, "Shere Khan had jumped at a woodcutter’s campfire, as Father Wolf had said",
 "Shere Khan is angry and hurt, but he cannot get into the cave. The mouth of the cave is too narrow for a tiger.",
 "Shere Khan had jumped at a woodcutter's campfire, as Father Wolf had said, and he was very angry because his feet hurt from the burns. But Father Wolf knew that the mouth of the cave was too narrow for a tiger to come in. Even where he was, Shere Khan's shoulders and front paws had too little room, as a man's would have if he tried to fight in a barrel.",
 ["furious","narrow","cramped","fore paws"]),
(3, "The Law of the Jungle lays down very clearly that any wolf may",
 "The Law of the Jungle says that wolf cubs must be shown to the Pack Council. After that, the Pack must not kill them.",
 "The Law of the Jungle says very clearly that a wolf may leave his Pack when he marries. But when his cubs are old enough to stand on their feet, he must bring them to the Pack Council. The Council is usually held once a month, when the moon is full, so that the other wolves can know who the cubs are. After that look, the cubs are free to run where they like. Until they have killed their first buck, no excuse is accepted if a grown wolf of the Pack kills one of them. The punishment is death, if the one who killed them can be found. If you think about it for a minute, you will see that this must be so.",
 ["withdraw","identify","inspection","buck","murderer"]),
(3, "A black shadow dropped down into the circle. It was Bagheera",
 "Bagheera the Black Panther comes into the circle. He is feared by everybody, but his voice is very soft.",
 "A black shadow came down into the circle. It was Bagheera, the Black Panther. He was black as ink all over, but in some lights the panther marks showed, like the pattern on watered silk. Everybody knew Bagheera, and nobody wanted to get in his way, because he was as sly as Tabaqui, as brave as the wild buffalo, and as careless of danger as the wounded elephant. But his voice was as soft as wild honey dripping from a tree, and his skin was softer than the softest feathers.",
 ["inky","cunning","reckless","down","watered silk"]),
(3, "By Red Flower Bagheera meant fire, only no creature in the jungle",
 "Bagheera means fire when he says Red Flower. The animals are afraid of fire and never use its real name.",
 "When Bagheera said Red Flower, he meant fire. But no animal in the jungle will call fire by its real name. Every animal is in great fear of it, and finds a hundred ways to talk about it.",
 ["proper name","deadly","invents"]),
(4, "All this will show you how much Mowgli had to learn by heart",
 "Mowgli is tired of learning. Baloo says that a man's cub must learn all the Law of the Jungle.",
 "All this shows how much Mowgli had to learn by heart. He became very tired of saying the same thing a hundred times. But one day Mowgli had been hit and had run away angry. Then Baloo said to Bagheera, “A man's cub is a man's cub, and he must learn all the Law of the Jungle.”",
 ["by heart","cuffed","in a temper"]),
(4, "They were always just going to have a leader and laws and customs",
 "The monkeys always say they will have a leader and laws, but they never do. They forget everything by the next day.",
 "The monkeys were always just about to have a leader and laws and ways of their own, but they never did. Their memories could not last from one day to the next. So they settled things by making up a saying: “What the Bandar-log think now the Jungle will think later.” That made them feel much better. No animal could reach them, but also no animal would notice them. That was why they were so pleased when Mowgli came to play with them, and when they heard how angry Baloo was.",
 ["customs","making up","comforted","notice"]),
(4, "They found him stretched out on a warm ledge in the afternoon sun",
 "Baloo and Bagheera find Kaa the python. He has a new skin and looks very fine.",
 "They found him lying on a warm ledge in the afternoon sun. He was looking with pleasure at his beautiful new coat. For the last ten days he had stayed away from others while he changed his skin, and now he looked very fine. He moved his big head with its blunt nose quickly along the ground. He twisted his thirty feet of body into strange knots and curves, and he licked his lips as he thought of the dinner to come.",
 ["ledge","retirement","splendid","blunt","fantastic"]),
(4, "In the Cold Lairs the Monkey People were not thinking of Mowgli’s friends",
 "The monkeys take Mowgli to an old, broken city. It is very old, and trees and plants grow in the walls.",
 "In the Cold Lairs the Monkey People were not thinking about Mowgli's friends at all. They had brought the boy to the Lost City, and for a while they were very pleased with themselves. Mowgli had never seen a city in India before. It was almost a heap of ruins, but it seemed very wonderful and fine to him. Some king had built it long ago on a little hill. You could still follow the stone roads that went up to the broken gates, where the last bits of wood hung on old, rusty hinges. Trees had grown into and out of the walls. The tops of the walls had fallen down and fallen apart, and wild climbing plants hung from the windows of the towers on the walls in thick bunches.",
 ["causeways","hinges","battlements","decayed","creepers"]),
(4, "Bagheera gave him half a dozen love-taps",
 "Bagheera punishes Mowgli, but the hits are light for a panther. Mowgli takes it without a word.",
 "Bagheera gave him six soft hits. For a panther they were so light that they would hardly have woken one of his own cubs. But for a seven-year-old boy they were as hard a beating as anyone would want to avoid. When it was over, Mowgli sneezed and got up without a word.",
 ["love-taps","severe"]),
(5, "the cubs had often nipped Mowgli harder than they intended",
 "The white marks on Mowgli's arms and legs come from the wolf cubs' play. He does not call them bites.",
 "Of course, when the cubs played with Mowgli, they had often bitten him harder than they meant to, and he had white marks all over his arms and legs. But he would never have called these bites, because he knew what real biting was.",
 ["nipped","scars"]),
(5, "The priest was a clever man, and he knew that Messua was wife",
 "The priest knows that Messua's husband is rich. So he says that the jungle has given her boy back.",
 "The priest was a clever man, and he knew that Messua was the wife of the richest man in the village. So he looked up at the sky for a minute and said in a serious voice: “What the jungle has taken the jungle has given back. Take the boy into your house, my sister, and do not forget to honor the priest, who can see so far into the lives of men.”",
 ["solemnly","restored","honor"]),
(5, "For three months after that night Mowgli hardly ever left the village gate",
 "Mowgli learns the ways of men. He is often angry, but he keeps his temper because of the Law of the Jungle.",
 "For three months after that night, Mowgli hardly ever left the village gate, because he was so busy learning the ways of men. First he had to wear a cloth around his body, and this annoyed him very much. Then he had to learn about money, which he did not understand at all, and about plowing, which seemed to him to have no use. Then the little children of the village made him very angry. Luckily, the Law of the Jungle had taught him to keep his temper, because in the jungle life and food depend on it. The children laughed at him because he would not play games or fly kites, or because he said some word wrongly. Only one thing stopped him from picking them up and breaking them in two: he knew that it was not fair to kill little naked cubs.",
 ["annoyed","plowing","keep his temper","mispronounced","unsportsmanlike"]),
(5, "The two wolves ran, ladies’-chain fashion, in and out of the herd",
 "Akela and Gray Brother split the buffalo herd into two groups. The cows and the bulls are in different groups.",
 "The two wolves ran in and out of the herd in a pattern like a dance. The herd snorted, threw up its head, and split into two groups. In one group stood the cow-buffaloes with their calves in the middle. They glared and pawed the ground, ready to charge and trample the life out of a wolf, if one would only stay still. In the other group the bulls and the young bulls snorted and stamped. They looked more grand, but they were much less dangerous, because they had no calves to protect. No six men could have split the herd so well.",
 ["ladies’-chain fashion","clumps","pawed","imposing"]),
(5, "To do Buldeo justice, if he had been ten years younger he would have",
 "Buldeo sees a wolf obey Mowgli. He thinks it is magic and is afraid.",
 "To be fair to Buldeo, if he had been ten years younger he would have faced Akela if he had met the wolf in the woods. But a wolf that obeyed the orders of this boy, who had private wars with man-eating tigers, was no common animal. Buldeo thought it was sorcery, magic of the worst kind. He wondered if the amulet round his neck would keep him safe. He lay as still as he could, and thought that at any minute he would see Mowgli turn into a tiger too.",
 ["sorcery","amulet","common"]),
(5, "Ever since Akela had been deposed, the Pack had been without a leader",
 "The Pack has no leader, and many wolves are hurt. They come to the Council Rock and see Shere Khan's hide. Mowgli sings a song.",
 "Since Akela had been taken from his place as leader, the Pack had had no leader, and they hunted and fought as they liked. But they answered the call from habit. Some of them were lame from the traps they had fallen into, some limped from shot wounds, some had bare patches of skin from eating bad food, and many were missing. But all that were left came to the Council Rock. They saw Shere Khan's striped hide on the rock, and the huge claws hanging at the end of the empty feet. Then Mowgli made up a song with no rhymes. It came up into his throat all by itself, and he shouted it out loud. He jumped up and down on the rattling skin and beat time with his heels until he had no breath left, while Gray Brother and Akela howled between the verses.",
 ["deposed","lame","mangy","dangling","verses"]),
(6, "It was not the fashion for Sea Catch to eat anything during",
 "Sea Catch eats nothing for four months, so he is bad-tempered. His wife Matkah knows not to answer back.",
 "Sea Catch did not eat anything during the four months that he stayed on the beaches. That was the custom, and so his temper was usually bad. Matkah knew that she should not answer him back. She looked around and said softly: “How thoughtful of you. You've taken the old place again.”",
 ["fashion","temper","cooed"]),
(6, "Little seals can no more swim than little children, but they are unhappy",
 "Kotick is carried out by a wave on his first time in the sea. He nearly drowns, but the next wave saves him.",
 "Little seals can no more swim than little children can, but they are unhappy until they learn. The first time Kotick went down to the sea, a wave carried him out to where the water was too deep for him. His big head went down and his little back flippers flew up, just as his mother had told him in the song. If the next wave had not thrown him back, he would have drowned.",
 ["beyond his depth","flippers"]),
(6, "Ten minutes later little Kotick did not recognize his friends any more",
 "Kotick sees the men skin the seals. He is shocked.",
 "Ten minutes later, little Kotick could not know his friends any more. Their skins had been pulled off, from the nose to the back flippers, and thrown on the ground in a pile.",
 ["recognize","ripped","hind flippers"]),
(6, "That was enough for Kotick. He turned and galloped",
 "Kotick runs back to the sea in fear. A sea-lion talks to him in a rough voice.",
 "That was enough for Kotick. He turned and ran back to the sea (a seal can run very fast for a short time), and his little new mustache stood up straight with fear. At Sea-Lion's Neck, where the big sea-lions sit at the edge of the waves, he threw himself into the cool water with his flippers over his head. He rocked there, breathing hard and feeling very sad. “What's here?” said a sea-lion in a rough voice, because as a rule the sea-lions keep to themselves.",
 ["galloped","bristling","surf","gruffly","flung"]),
(6, "They were like no walrus, sea-lion, seal, bear, whale, shark, fish, squid, or scallop",
 "Kotick sees strange big animals in the sea. They look foolish, and they are the sea cows.",
 "They were not like any walrus, sea-lion, seal, bear, whale, shark, fish, squid or scallop that Kotick had seen before. They were between twenty and thirty feet long. They had no back flippers, but a tail like a shovel, that looked as if it had been cut out of wet leather. Their heads were the most foolish-looking things you ever saw. When they were not feeding, they stood on the ends of their tails in deep water, bowing seriously to one another and waving their front flippers the way a fat man waves his arm.",
 ["whittled","grazing","solemnly","squid","scallop"]),
(6, "Then Kotick dropped his head between his shoulders and shut his eyes proudly",
 "Kotick has won the fight, and he is red with blood. He is too proud to look at his wounds.",
 "Then Kotick put his head down between his shoulders and shut his eyes proudly. He was not a white seal any more, but red from his head to his tail. Still, he would have thought it beneath him to look at or touch one of his wounds.",
 ["scorned","wounds"]),
(7, "It is the hardest thing in the world to frighten a mongoose",
 "A mongoose is never afraid for long, because he is very curious. Rikki-tikki looks around the room.",
 "It is the hardest thing in the world to frighten a mongoose, because he is full of curiosity from his nose to his tail. The saying of all the mongoose family is “Run and find out,” and Rikki-tikki was a true mongoose. He looked at the cotton-wool and decided that it was not good to eat. He ran all round the table, sat up and made his fur tidy, scratched himself, and jumped on the small boy's shoulder.",
 ["curiosity","motto","cotton-wool"]),
(7, "He spread out his hood more than ever, and Rikki-tikki saw the spectacle-mark",
 "Nag shows his hood, but Rikki-tikki is not afraid for long. A mongoose knows that its work is to fight snakes.",
 "Nag spread out his hood more than ever, and Rikki-tikki saw the spectacle mark on the back of it, which looks exactly like the eye part of a hook-and-eye fastening. For a minute he was afraid. But a mongoose cannot stay frightened for long. Rikki-tikki had never met a live cobra before, but his mother had fed him on dead ones, and he knew that all a grown mongoose has to do in life is fight and eat snakes. Nag knew that too, and deep in his cold heart he was afraid.",
 ["hood","spectacle-mark","fastening"]),
(7, "If you read the old books of natural history, you will find they say",
 "Old books say that a mongoose eats a herb when a snake bites it. The writer says that this is not true: a mongoose wins by being quick.",
 "If you read the old books about nature, you will find that they say a mongoose that is bitten in a fight with a snake runs off and eats a herb that cures him. That is not true. The win is only a matter of a quick eye and a quick foot: the snake's blow against the mongoose's jump. No eye can follow the move of a snake's head when it strikes, and that is much more wonderful than any magic herb. Rikki-tikki knew that he was a young mongoose, and he was even more pleased to think that he had escaped a blow from behind. It gave him trust in himself, and when Teddy came running down the path, Rikki-tikki was ready to be petted.",
 ["natural history","herb","victory","confidence"]),
(7, "very cunningly hidden, he found twenty-five eggs, about the size of a bantam’s eggs",
 "Rikki-tikki finds Nagaina's eggs in the melon-bed. There are twenty-five of them.",
 "Rikki-tikki heard them going up the path from the stables, and he ran fast to the end of the melon-patch near the wall. There, in the warm litter around the melons, very cleverly hidden, he found twenty-five eggs. They were about the size of a bantam's eggs, but they had whitish skin instead of shell.",
 ["litter","cunningly","bantam"]),
(7, "He had forgotten the egg. It still lay on the veranda",
 "Nagaina takes the last egg and runs for her hole. Rikki-tikki follows her.",
 "He had forgotten the egg. It was still on the veranda, and Nagaina came nearer and nearer to it. At last, while Rikki-tikki was taking a breath, she took it in her mouth, turned to the veranda steps, and went down the path as fast as an arrow, with Rikki-tikki behind her. When a cobra runs for her life, she moves like a whip that is flicked across a horse's neck.",
 ["veranda","whiplash","flicked"]),
(8, "Kala Nag stood ten fair feet at the shoulders, and his tusks",
 "Kala Nag is a very big elephant. His tusks are short, but he is strong in a fight.",
 "Kala Nag was a good ten feet high at the shoulders. His tusks had been cut off short, at five feet, and the ends had been wrapped with bands of copper so that they would not split. But he could do more with those short ends than any untrained elephant could do with real sharp tusks.",
 ["fair","tusks","stumps"]),
(8, "“Not green corn, Protector of the Poor —melons,” said Little Toomai",
 "Little Toomai says that he took melons, not corn. The men laugh, and he wishes he could hide.",
 "“Not green corn, Protector of the Poor — melons,” said Little Toomai. All the men sitting around burst out in loud laughter. Most of them had taught their elephants that trick when they were boys. Little Toomai was hanging eight feet up in the air, and he wished very much that he were eight feet under the ground.",
 ["Protector of the Poor","roar of laughter"]),
(8, "There was another roar of laughter, for that is an old joke among elephant-catchers",
 "The hunters laugh because seeing elephants dance means never. No one has ever seen it.",
 "There was another roar of laughter, because that is an old joke among elephant-catchers, and it means just “never.” There are big flat cleared places hidden in the forests that are called elephants' ballrooms. But even these are found only by chance, and no man has ever seen the elephants dance. When a driver talks proudly about his skill and courage, the other drivers say, “And when did you see the elephants dance?”",
 ["ballrooms","boasts","accident","didst"]),
(8, "At last Kala Nag stood still between two tree-trunks at the very top",
 "Kala Nag takes Little Toomai to the top of a hill. There is an open space where the ground is hard from many feet.",
 "At last Kala Nag stood still between two tree-trunks at the very top. They were part of a circle of trees that grew around an open space of uneven shape, three or four acres big. In all of that space, as Little Toomai could see, the ground had been trampled as hard as a brick floor. Some trees stood in the middle of the open space, but their bark was rubbed off, and the white wood under it looked shiny and smooth in the patches of moonlight. Climbing plants hung from the high branches, and their flowers, big white waxy things like bells, hung down asleep. But in the open space there was not one blade of green, only trampled earth.",
 ["irregular","trampled","creepers","convolvuluses"]),
(8, "The morning broke in one sheet of pale yellow behind the green hills",
 "Morning comes and the elephants go away. Only three elephants are left.",
 "Morning came as one sheet of pale yellow light behind the green hills, and the booming stopped at the first ray, as if the light had been an order. Before Little Toomai had got the ringing out of his head, and before he had even moved, there was no elephant in sight except Kala Nag, Pudmini, and the elephant with the rope-galls. There was no sign, no rustle and no whisper down the hillsides to show where the others had gone.",
 ["booming","shifted","rope-galls"]),
(9, "The camel doubled up camel-fashion, like a two-foot rule, and sat down whimpering",
 "The camel sits down, and a big troop-horse arrives. He is angry about the camels.",
 "The camel folded up in the way camels do, like a two-foot ruler, and sat down, crying softly. In the dark there was a steady beat of hoofs, and a big troop-horse rode up at an easy run, as steadily as if he were on parade. He jumped over the tail of a gun and landed close to the mule.",
 ["doubled up","whimpering","cantered","parade"]),
(9, "They say that when a mule trips you can split a hen’s ear",
 "Billy tells how mules work on mountains. They must keep hidden from the enemy.",
 "“They say that when a mule trips, you can split a hen's ear,” said Billy. “Now and then a badly packed saddle may make a mule fall, but that is very seldom. I wish I could show you our work. It is beautiful. It took me three years to find out what the men were trying to do. The skill of it is never to show yourself against the skyline, because if you do, someone may shoot at you. Remember that, young one. Always keep hidden as much as you can, even if you must go a mile out of your way. I lead the battery when it comes to that kind of climbing.”",
 ["trips","science","skyline","battery"]),
(9, "That time or any other. Eating is always good",
 "The gun-bullocks say that there is only one way to fight. They pull the big gun and eat grass.",
 "“At that time or any other time. Eating is always good. We eat until we are yoked up again, and then we pull the gun back to where Two Tails is waiting for it. Sometimes the big guns in the city fire back, and some of us are killed, and then there is more grass for those who are left. This is Fate, nothing but Fate. Still, Two Tails is a great coward. That is the right way to fight. We are brothers from Hapur. Our father was a sacred bull of Shiva. We have spoken.”",
 ["yoked","tug","Fate","coward","sacred"]),
(9, "I never knew before what made Indian cattle so afraid of Englishmen",
 "The writer learns why Indian cattle fear Englishmen. They eat beef.",
 "Before this, I never knew why Indian cattle were so afraid of Englishmen. We eat beef, which no cattle-driver touches, and of course the cattle do not like that.",
 ["cattle-driver","beef"]),
(9, "The rain began to fall again, and for a while it was too misty",
 "The soldiers make a long line and move toward the Viceroy and the Amir. The ground shakes.",
 "The rain began to fall again, and for a while it was too misty what the soldiers were doing. They had made a big half-circle across the plain and were spreading out into a line. The line grew longer and longer until it was three-quarters of a mile from one end to the other, one solid wall of men, horses and guns. Then it came straight toward the Viceroy and the Amir, and as it got nearer, the ground began to shake, like the deck of a steamer when the engines are going fast.",
 ["Viceroy","Amir","solid","wing"]),
]
