# key: (meaning, pos, forms, example)
PH = {
"get rid of": ("To make something go away, or to stop having it.","phrasal verb",[],"to get rid of the sleepy feeling in the tips"),
"pick and choose": ("To choose only the things that you like best.","idiom",[],"to pick and choose"),
"run off": ("To go away fast.","phrasal verb",["ran off"],"Its parents have run off"),
"look to it": ("To make sure that something is done.","idiom",[],"look to it then that thou dost not kill the man-cub"),
"make up": ("To invent something, such as a song.","phrasal verb",["made up"],"Mowgli made up a song without any rhymes"),
"show off": ("To do something so that people will look at you and think well of you.","phrasal verb",[],"delighted to show off"),
"set out": ("To start to do something, or to start a journey.","phrasal verb",[],"They set out together across the Pacific"),
"come back": ("To return to a place.","phrasal verb",["come back"],"Not one small wolfling has come back to thank old Baloo"),
"wind up": ("To end by saying something.","phrasal verb",["wound up"],"Baloo wound up, patting his big furry stomach"),
"make fun of": ("To laugh at someone in an unkind way.","idiom",["made fun of"],"made fun of the drivers who were going away"),
"in the least": ("At all. It is used with a negative word.","idiom",[],"which he did not in the least understand"),
"pick up": ("To lift something from the place where it is.","phrasal verb",[],"pick up a wicker pot plastered inside with earth"),
"get away": ("To escape, or to go away from a place.","phrasal verb",[],"the other seal might get away if he could"),
"drive out": ("To make someone leave a place.","phrasal verb",[],"dogs whom I drive out"),
"take care": ("To be careful.","idiom",["taking care"],"taking care to crush the young cobras"),
"set off": ("To start a journey.","phrasal verb",["set off"],"before he set off on his last exploration"),
"tired of": ("No longer wanting to do something, because you have done it too much.","phrase",[],"being tired of carrying him"),
"in spite of": ("Even though something makes it hard.","idiom",[],"not enough to go on in spite of it"),
"on account of": ("Because of.","idiom",[],"on account of the new elephants"),
"lay out": ("To spread something out flat.","phrasal verb",[],"to lay out Shere Khan’s hide upon the Council Rock"),
"turn into": ("To change into something else.","phrasal verb",[],"Mowgli turn into a tiger, too"),
"cast out": ("To make someone leave a group, with force.","phrasal verb",[],"I have been cast out of the Pack"),
"run away": ("To leave a place fast, because of fear.","phrasal verb",["ran away"],"run away as soon as they can repeat the Hunting Verse"),
"for the sake of": ("To help someone, or for the good of someone.","idiom",[],"for the sake of the bull that bought thee"),
"in a hurry": ("Doing something fast, because you have little time.","idiom",[],"he was in a hurry to go back to Novastoshnah"),
"right and left": ("On both sides.","idiom",[],"Bagheera killed right and left as he felt hungry"),
"hand over": ("To give something to someone else.","phrasal verb",["handed over"],"had not been handed over to him"),
"head over heels": ("Turning over, with the feet going over the head.","idiom",[],"knocking the youngsters head over heels right and left"),
"by heart": ("From memory, so that you do not need to read it.","idiom",[],"much Mowgli had to learn by heart"),
"as a rule": ("Usually.","idiom",[],"for as a rule the sea-lions keep themselves to themselves"),
"out of reach": ("Too far for you to touch it.","phrase",[],"out of reach of snakes"),
"lose one's temper": ("To become very angry.","idiom",["lose his temper"],"Kotick began to lose his temper"),
"keep one's temper": ("To stay calm and not get angry.","idiom",["keep his temper"],"to keep his temper"),
"on the trail of": ("Following the marks that someone or something leaves.","idiom",[],"on the trail of the Bandar-log"),
"for fear of": ("Because you are afraid of something.","idiom",[],"for fear of those that love thee"),
"look out for": ("To be careful and watch for danger.","phrasal verb",[],"Look out for yourselves"),
"fly at": ("To attack someone suddenly.","phrasal verb",[],"very ready to fly at an intruder"),
"back out": ("To move backward and go out of a place.","phrasal verb",["backed out"],"he backed out of the cave-mouth growling"),
"give tongue": ("To cry out loud, as a hunting animal does.","idiom",["gave tongue"],"Akela gave tongue in the full hunting-yell"),
"turn out": ("To make someone leave a place.","phrasal verb",["turned out"],"Mowgli was turned out of the Seeonee wolf-pack"),
"all but": ("Almost.","phrase",[],"He is our brother in all but blood"),
"no more than": ("Only.","phrase",[],"I saw no more than a big snake"),
"take orders": ("To do what someone tells you to do.","idiom",[],"take orders from our Viceroy"),
"break loose": ("To get free.","phrasal verb",[],"the camels would break loose and run about"),
"find out": ("To learn a fact.","phrasal verb",[],"“Run and find out”"),
"go off": ("To fire, as a gun does, with a loud sound.","phrasal verb",["went off"],"The old Tower musket went off with a bang"),
"come across": ("To find something by chance.","phrasal verb",["come across"],"he had come across more than one such barricade"),
"carry off": ("To take someone away.","phrasal verb",["carried off"],"the tiger carried off a man at twilight"),
"hold on": ("To keep holding something tightly.","phrasal verb",["held on"],"he held on as the body cartwhipped over the floor"),
"make sure": ("To check that something is true or safe.","phrase",[],"gave the Call a second time to make sure"),
"work one's way": ("To move on slowly, with great effort.","idiom",["worked his way"],"worked his way desperately, inch by inch"),
"break down": ("To make something fall by hitting it.","phrasal verb",[],"I break down the wall"),
"go back": ("To return to a place.","phrasal verb",[],"thou must go back to men at last"),
"look up": ("To lift your eyes to see something above you.","phrasal verb",["looked up"],"Baloo looked up to see where the voice came from"),
"put on": ("To dress yourself in something.","phrasal verb",[],"I put on my boots and waterproof"),
"had better": ("Used to say what is the wise thing to do.","phrase",[],"Mowgli had better be set to work as soon as possible"),
"take orders": ("To do what someone tells you to do.","idiom",[],"take orders from our Viceroy"),
}
