from words1 import w, OLD
w("sambhur","noun","A big deer of India.")
w("sweeper","noun","In India, a servant whose job is to clean and take away rubbish.")
w("galls","plural noun","Sore places on the skin, made by a rope or strap that rubs.",["gall"])
w("bloodhound","noun","A big dog that is very good at following smells.")
w("scuttled","past-tense verb","Ran with quick, short steps.",["scuttled","scuttle"])
w("mahadeo","noun","A name for the Hindu god Shiv. It is used in the song.")
w("dunghill","noun","A pile of waste from animals.")
w("impotent","adjective","Without power; not able to do anything.")
w("dewanee","noun","In the book, the word that jungle animals use for the madness of a sick animal. The book says it means 'the madness'.")
w("lame","adjective","Not able to walk well, because a leg or foot is hurt.")
w("tank","noun","In India, a pool or small lake that holds water.",["tanks"])
w("scoochnie","adjective","A Russian word. The book gives its meaning as 'lonesome'.",["scoochnie"])
w("stareek","noun","A Russian word. The book gives its meaning as 'old man'.")
w("poltoos","noun","A Russian word. The book gives its meaning as 'the halibut', a kind of big flat fish.")
w("gidur","noun","A word from India. With a second word, it is the name that the book gives to the Jackal People.")
w("lungri","noun","In the book, a name for Shere Khan. The book says it means 'the Lame One'.")
w("raksha","noun","In the book, the name of Mother Wolf. The book says it means 'the Demon'.")
w("sag","noun","A word from India. The book says it means 'dogs'.")
w("hukm","noun","A word from India. The book says that 'Hukm hai' means 'It is an order'.")
w("maro","verb","A word from India. The book says that 'Maro! Mar!' means 'Hit him, hit him!'")
w("somalo","adjective","A word from India. The book says that 'Somalo' means 'Careful'.")
w("bandar","noun","A word from India. With a second word, it is the name that the book gives to the Monkey People.")
