from words1 import w, OLD
# ---------- chapter 8: Toomai of the Elephants ----------
w("picket","noun","A strong post in the ground. An animal is tied to it with a rope or chain.",["pickets"])
w("hauled","past-tense verb","Pulled with a lot of effort.",["hauled","haul"])
w("baulk","noun","A big, rough piece of cut wood.",["baulks"])
w("insubordinate","adjective","Not willing to obey orders.")
w("stockade","noun","A strong fence made of tall posts, to keep animals or people in.")
w("pandemonium","noun","A place of great noise and confusion.")
w("ankus","noun","A metal tool with a hook and a point that is used by the driver to guide an elephant.")
w("goad","noun","A pointed stick or tool that is used to make an animal move.")
w("mahout","noun","A man who rides an elephant and takes care of it.",["mahouts"])
w("howdah","noun","A seat for people to sit in on the back of an elephant.")
w("keddah","noun","In this story, the strong fenced place where wild elephants are caught.")
w("kine","noun","An old word for cows.",None,OLD)
w("lullaby","noun","A soft song that is sung to help a child sleep.")
w("fodder","noun","Food for farm animals.")
w("shackled","past-tense verb","Held with a chain on the leg.",["shackled","unshackled"])
w("saplings","plural noun","Young, thin trees.")
w("creepers","plural noun","Plants that grow along the ground or up trees and walls.")
w("salute","noun","A sign of respect, such as lifting a hand to the head. Here the elephants lift their trunks.")
w("tracker","noun","A person who follows the marks that animals leave on the ground.",["trackers"])
w("sahib","noun","A word used in India for a white man. It shows respect, like 'sir'.")
w("behooves","verb","Is right or needed for someone to do.",["behooves"])
w("grubbing","present participle","Digging in the ground to look for something.",["grubbing"])
w("lest","conjunction","In case; so that something bad does not happen.",["lest"],OLD)
w("hath","verb","Has.",["hath"],OLD)
w("shouldst","modal verb","Should. It is used after 'thou'.",["shouldst"],OLD)
w("didst","verb","Did. It is used after 'thou'.",["didst"],OLD)

# ---------- chapter 9: Her Majesty's Servants ----------
w("reviewed","past participle","Looked at and checked by an important person, as soldiers are in a big show.",["reviewed","review"])
w("bodyguard","noun","A group of people who protect an important person.")
w("slush","noun","Wet, half-melted snow, or soft mud.")
w("wigwam","noun","A small round tent. Some Native American people made it.")
w("battery","noun","A group of big guns, with the men and animals that work them.")
w("cannon","noun","A big gun that fires heavy metal balls.")
w("harness","noun","The leather straps that are put on a horse or mule so that it can pull or carry things.")
w("baggage","noun","The bags and boxes that people take on a journey.")
w("lancers","plural noun","Soldiers on horses who fight with long spears.")
w("recruit","noun","A new soldier or animal that has just joined the group.",["recruits"])
w("cavalry","noun","Soldiers who fight on horses.")
w("crupper","noun","A strap that goes under a horse's tail, to keep the saddle in place.")
w("breastplate","noun","A strap or plate across a horse's chest.")
w("hocks","plural noun","The joints in the middle of the back legs of a horse or mule.")
w("farrier","noun","A person who puts iron shoes on horses.")
w("yoke","noun","A wooden bar across the necks of two animals so that they can pull together.",["yokes"])
w("brumby","noun","In Australia, a wild horse.")
w("skate","noun","In this story, a rude word for a horse that is not good.")
w("jackass","noun","A male donkey.")
w("roughshod","adverb","In a hard way, with no care for others. 'Ridden over roughshod' means treated badly.")
w("pachydermatous","adjective","Having a thick skin, like an elephant.")
w("anachronism","noun","Something that belongs to an earlier time and does not fit now.")
w("betwixt","preposition","Between.",["betwixt"],OLD)
w("sergeant","noun","A soldier who is above a regular soldier and gives them orders.")
w("lieutenant","noun","An army officer who is below a captain.")
w("brigadier","noun","An army officer with a high rank, who leads several groups of soldiers.")
w("viceroy","noun","A man who rules a country for a king or queen.")
w("astrakhan","noun","The curly wool of young sheep, used to make hats.")
w("squadron","noun","A group of soldiers on horses.")
w("conceited","adjective","Too proud of yourself.")
w("formation","noun","The way soldiers or animals are arranged in lines or groups.")
w("campaigner","noun","An old soldier who has been in many wars.")
w("ammunition","noun","Bullets and shells that guns fire.")
w("hussars","plural noun","Soldiers on horses.")
