# (key, pos, meaning, forms)
OLD = "This is an old word that people do not use now."
W = []
def w(key, pos, meaning, forms=None, why=None):
    W.append(dict(key=key, pos=pos, meaning=meaning, forms=forms or [], why=why))

# ---------- chapter 3: Mowgli's Brothers ----------
w("cub","noun","A young wolf, tiger, bear or other wild animal. The book also calls a human child a 'man's cub'.")
w("jackal","noun","A wild animal like a thin dog. It eats what other animals leave.")
w("despise","verb","To hate someone and think that he is worth nothing.",["despise","despised"])
w("mischief","noun","Small bad acts that cause trouble for other people.")
w("scour","verb","To look for something in every part of a place, with great care.")
w("thicket","noun","A thick group of bushes or small trees.")
w("bullock","noun","A male cow that is kept for work or for meat.")
w("bewilder","verb","To make someone not know what to think or do.",["bewilders","bewildered"])
w("unsportsmanlike","adjective","Not fair or honest in the way you act.")
w("dimpled","adjective","Soft and round, with little round holes in the skin, like a baby.")
w("quarry","noun","An animal that someone is hunting.")
w("cower","verb","To make yourself small because you are afraid.",["cowering","cowered"])
w("singe","verb","To burn a little, at the ends or on the top.",["singed","singe"])
w("pledge","noun","A strong promise.")
w("fodder","noun","Food for farm animals.")
w("lair","noun","The home of a wild animal.")
w("thou","pronoun","You (one person). It is the form used as the subject of a verb.",["thou"],OLD)
w("thee","pronoun","You (one person). It is the form used after a verb or a word like 'to'.",["thee"],OLD)
w("thy","determiner","Your (of one person).",["thy"],OLD)
w("thine","pronoun","Yours (of one person).",["thine"],OLD)
w("ye","pronoun","You (more than one person).",["ye"],OLD)
w("art","verb","Are. It is used after 'thou'.",["art"],OLD)
w("hast","verb","Have. It is used after 'thou'.",["hast"],OLD)
w("wilt","verb","Will. It is used after 'thou'.",["wilt"],OLD)
w("wast","verb","Was. It is used after 'thou'.",["wast"],OLD)
w("canst","modal verb","Can. It is used after 'thou'.",["canst"],OLD)
w("mayest","modal verb","May. It is used after 'thou'.",["mayest"],OLD)
w("hence","adverb","Away from this place.",["hence"],OLD)
w("assuredly","adverb","Certainly; without any doubt.",["assuredly"],OLD)
w("ay","interjection","Yes.",["ay"],OLD)
