from words1 import w, OLD
# ---------- chapter 6: The White Seal ----------
w("comber","noun","A long, high wave that rolls onto the shore.",["combers"])
w("rigging","noun","The ropes and chains that hold up the sails and masts of a ship.")
w("tingle","verb","To have a feeling of little pricks on the skin.",["tingles","tingly","tingled"])
w("halibut","noun","A big flat fish.")
w("albatross","noun","A very big sea bird with long wings.")
w("phosphorescent","adjective","Giving a soft light in the dark, like the sea at night.")
w("holluschickie","plural noun","In this story, the young male seals who have no wives yet. They keep to their own places on the beach.")
w("walrus","noun","A big sea animal with two long teeth called tusks.")
w("blubber","noun","The thick fat of a sea animal such as a whale or seal.")
w("shoal","noun","A big group of fish that swim together.")
w("perpendicular","adjective","Going straight up, not at a slant.")
w("fathom","noun","A measure of the depth of the sea. One fathom is about six feet or two meters.",["fathoms"])

# ---------- chapter 7: Rikki-Tikki-Tavi ----------
w("mongoose","noun","A small furry animal that kills snakes.",["mongooses"])
w("cantonment","noun","A town or camp where soldiers live, in old India.")
w("bungalow","noun","A house with only one floor, as built in India.")
w("burrow","noun","A hole in the ground that an animal makes to live in.")
w("draggled","adjective","Wet and dirty.")
w("revived","past-tense verb","Came back to life or woke up again.",["revived"])
w("veranda","noun","A covered place with a floor, along the side of a house.")
w("cobra","noun","A poisonous snake that can spread out the skin of its neck like a hood.",["cobras"])
w("hood","noun","The wide flat skin round the neck of a cobra. It spreads out when the snake is angry.")
w("fledgling","noun","A young bird that has just learned to fly.",["fledglings"])
w("flinched","past-tense verb","Moved a little, because of fear or pain.",["flinched"])
w("lunged","past-tense verb","Moved forward very fast and hard to hit something.",["lunged"])
w("paralyzed","past-tense verb","Made unable to move.",["paralyzed"])
w("providence","noun","A force that looks after people and keeps them safe. Here it means a person who saved them.")
w("sluice","noun","A small hole or pipe that water flows out through.")
w("masonry","noun","Work that is made of stone or brick.")
w("purchase","noun","A firm hold. It helps you to pull or to push with strength.")
w("valiant","adjective","Very brave.")
w("featherbrained","adjective","Silly and not able to think well.")
w("consolation","noun","Something that makes you feel less sad.")
w("bantam","noun","A small kind of chicken.")
w("widow","noun","A woman whose husband is dead.")
w("brood","noun","All the young birds or animals that were born together.")
w("coppersmith","noun","In this story, the name of a bird. Its call sounds like a small hammer on copper.")
w("mournful","adjective","Very sad.")
