from words1 import w, OLD
# ---------- chapter 4: Kaa's Hunting ----------
w("gore","verb","To hurt with a horn or tusk, by pushing it into the body.",["gore"])
w("fubsy","adjective","Round and fat, and a little short.")
w("intruder","noun","A person or animal that comes in where he should not be.")
w("cuffed","past-tense verb","Hit with the open hand or paw.",["cuffed"])
w("indignant","adjective","Angry because something seems unfair.")
w("boughs","plural noun","The big branches of a tree.",["bough"])
w("fledgling","noun","A young bird that has just learned to fly.",["fledglings"])
w("presumptuous","adjective","Too bold; acting as if you are more important than you are.")
w("manling","noun","A small man. Here the snakes use it for a boy.")
w("drouth","noun","A long time with no rain. It is an old way to spell 'drought'.")
w("reservoir","noun","A big place where a lot of water is kept.",["reservoirs"])
w("idol","noun","A statue of a god that people pray to.",["idols"])
w("grievously","adverb","In a way that causes great pain.")
w("bruised","adjective","Having blue or purple marks on the skin after being hit.",["bruise","bruised"])

# ---------- chapter 5: Tiger! Tiger! ----------
w("ravine","noun","A deep, narrow place between two high sides of land, like a small valley.",["ravines"])
w("barricade","noun","Something put across a way to stop people from passing.")
w("caste","noun","In India, one of the groups that people are born into. Some groups are thought better than others.")
w("pariah","noun","In India, a kind of wild dog that lives near villages.")
w("lacquered","adjective","Covered with a hard, shiny paint.")
w("alcove","noun","A small space in a wall, set back from the room.")
w("thatch","noun","A roof made of dried grass or straw.")
w("headman","noun","The leader of a village.")
w("moneylender","noun","A person who gives money to others and takes back more later.")
w("huqa","noun","A big pipe that old men smoke. The book calls it a water-pipe.",["huqas"])
w("graybeards","plural noun","Old men.")
w("impertinence","noun","Talk that is not polite to people who are older or more important.")
w("trample","verb","To walk or run on something and crush it with the feet.",["trampled","trampling","trampling"])
w("wallow","verb","To lie and roll about in mud or water for pleasure.",["wallows","wallowing"])
w("tussocks","plural noun","Thick bunches of grass that grow higher than the grass around.")
w("lumber","verb","To move in a heavy, slow way.",["lumbered","lumber","lumbering"])
w("slink","verb","To move away quietly, so that no one sees you, because you feel shame or fear.")
w("sorcery","noun","Magic that is used to do bad things.")
w("amulet","noun","A small thing that people wear because they believe it keeps them safe from harm.")
w("sorcerer","noun","A man who uses magic to do bad things.")
w("conch","noun","A big shell. People blow into it to make a loud sound.",["conches"])
w("rupee","noun","A coin that people use as money in India.",["rupees"])
w("anna","noun","A small coin of old India.",["annas"])
w("rearguard","noun","The animals or men at the back of a group.")
w("hotfoot","adverb","Very fast, and straight away.")
w("deposed","past participle","Taken away from a place of power.",["deposed"])
w("brickbats","plural noun","Pieces of broken brick that are thrown at someone.")
w("tulsi","noun","A plant that the book calls sacred.")
w("forsooth","adverb","Truly. It is used as a joke or with scorn.",["forsooth"],OLD)
w("dost","verb","Do. It is used after 'thou'.",["dost"],OLD)
w("shalt","modal verb","Shall. It is used after 'thou'.",["shalt"],OLD)
w("nay","interjection","No.",["nay"],OLD)
