from words1 import w, OLD
w("trumpeting","noun","The loud sound that an elephant makes with its trunk. To trumpet is to make this sound.",["trumpeting","trumpeted","trumpet"])
w("veteran","noun","A person or animal that has done something for many years and has a lot of experience.",["veterans"])
w("boulder","noun","A very big rock.",["boulders"])
w("hydrophobia","noun","A very bad illness that people and animals get from the bite of a sick animal. It makes them mad.")
w("reckless","adjective","Not caring about danger.")
w("lame","adjective","Not able to walk well because a leg or foot is hurt or weak.")
w("spitefully","adverb","In a way that is meant to hurt someone.")
w("muskrat","noun","A small furry animal that lives near water and has a strong smell.")
w("tailorbird","noun","A small bird that sews leaves together with plant fibers to make its nest.")
w("kerosene","noun","A kind of oil that is burned in lamps.")
w("hatch","verb","To come out of an egg.",["hatched","hatch"])
w("litter","noun","Small bits of dry leaves and rubbish that cover the ground.")
w("gait","noun","The way that a person or animal walks or runs.")
w("wisp","noun","A thin little bunch of something, such as grass.")
w("snakeling","noun","A young or small snake.")
