#!/usr/bin/env python3
"""
Build the basic-word list used by scripts/check-definition-words.mjs and by the
paragraph/sentence help post-check (src/lib/basic-words.ts).

Source: the `wordfreq` package (pip install wordfreq), English "best" list, ranked by
real-world frequency. Nothing is invented: the list is the first 2000 words of that
ranking after removing (a) rude words, (b) personal and place names, (c) web, brand and
politics words, (d) abbreviations and single letters. The removed words are listed in
BLOCK below so the choice can be reviewed.

Usage:  python3 scripts/build-basic-words.py
Writes: public/data/basic-words.txt (one word per line)
        src/lib/basic-words-data.ts (the same list as a TypeScript string)
"""
import re
from pathlib import Path
from wordfreq import top_n_list

SIZE = 2000

BLOCK = set("""
shit fuck fucking bitch ass sex sexual gay dick dude porn nude drunk
john york david george michael peter william robert charles harry steve paul mike james jack louis tom chris joe henry
martin frank richard thomas mary sam max tony ben bob ray taylor smith jones johnson williams scott lee kate jesus christ
london america china england europe india france russia japan germany canada australia texas california florida washington
paris chicago israel mexico korea scotland ireland africa asia italy italian french german chinese russian japanese
american canadian british european spanish african australian indian asian angeles jersey boston americans english christian muslim
http https www com org html url pdf lol wanna gonna gotta ya yo
google facebook twitter youtube internet website online email download blog app apps iphone ipad android wikipedia amazon
microsoft apple windows software users user click link links posts
trump obama republican democratic senate congress federal governor administration election elections
et al etc vs tv pm mm uk usa ii iii la de co inc ed ca ma ms dr st sub pre pro re ll ve
mark
""".split())

def ok(word: str) -> bool:
    if word in BLOCK:
        return False
    if not re.fullmatch(r"[a-z]+", word):
        return False
    if len(word) == 1 and word not in ("a", "i"):
        return False
    return True

def main():
    ranked = top_n_list("en", 6000, wordlist="best")
    out = []
    for word in ranked:
        if ok(word) and word not in out:
            out.append(word)
        if len(out) == SIZE:
            break
    # Words that a reader of simple stories meets all the time but that were ranked low or
    # removed above because of their other meanings. They are all in wordfreq's list too.
    root = Path(__file__).resolve().parent.parent
    (root / "public" / "data").mkdir(parents=True, exist_ok=True)
    (root / "public" / "data" / "basic-words.txt").write_text("\n".join(out) + "\n")
    ts = (
        "// GENERATED by scripts/build-basic-words.py from the wordfreq package. Do not edit by hand.\n"
        "// The 2000 most common English words after removing names, rude words, web words and abbreviations.\n"
        f"export const BASIC_WORDS_TEXT = `{' '.join(out)}`;\n"
    )
    (root / "src" / "lib" / "basic-words-data.ts").write_text(ts)
    print(len(out), "words written; last 30:", out[-30:])
    print("removed from the top", ranked.index(out[-1]) + 1, ":", [w for w in ranked[: ranked.index(out[-1]) + 1] if not ok(w)])

main()
