from fixes import *
fp(2,1,simple="The first place I can remember well was a big, nice field of grass with a pond of clear water in it. Some shady trees leaned over the pond, and rushes and water-lilies grew at the deep end. On one side, over the hedge, we looked into a plowed field. On the other side, we looked over a gate at our master’s house, which stood by the road. At the top of the field there was a small group of fir trees. At the bottom there was a running brook with a steep bank hanging over it.")
fp(3,15,simple="People now rode off in every direction: to the doctor’s, to the farrier’s, and without doubt to Squire Gordon’s, to let him know about his son. Mr. Bond, the farrier, came to look at the black horse that lay groaning on the grass. He felt him all over and shook his head. One of the horse’s legs was broken. Then someone ran to our master’s house and came back with a gun. Soon there was a loud bang and a terrible cry, and then everything was still. The black horse moved no more.",
 main="Men ride off to tell people. The farrier finds that the black horse has a broken leg. A gun is brought, there is a loud bang, and the black horse moves no more.")
fp(4,4,main="Black Beauty explains what breaking in is. A horse must learn to wear a saddle, a bridle and a harness, to pull a cart, and to always do what his master wants.")
fp(5,3,simple=open('/dev/null').read() or "Squire Gordon’s park went along the edge of the village of Birtwick. You came in by a large iron gate, with the first lodge beside it. Then you went along at a trot on a smooth road between groups of large old trees. Then came another lodge and another gate, which brought you to the house and the gardens. Past this were the home paddock, the old orchard and the stables. There was room for many horses and carriages. But I only need to tell about the stable that I was taken into. It was very large, with four good stalls. A big window that swung open looked onto the yard, which made it nice and full of fresh air.")
fp(7,2,simple="I was quite happy in my new place. If there was one thing I missed, you must not think that I was not happy. Everyone who had to do with me was good, I had a light stable with plenty of fresh air, and I had the best food. What more could I want? Freedom! For three and a half years of my life I had all the freedom I could wish for. But now, week after week and month after month, and no doubt year after year, I must stand in a stable night and day, except when I am wanted. And then I must be as steady and quiet as any old horse who has worked for twenty years. There are straps here and straps there, a bit in my mouth, and blinkers over my eyes. I am not complaining, because I know it must be so. I only mean to say that it is hard for a young horse full of strength and spirit. He is used to a big field or open land, where he can throw up his head and his tail and gallop away at full speed, then turn and come back with a snort to his friends. I say it is hard never to have a little more freedom to do what you like. Sometimes, when I have had less exercise than usual, I feel so full of life and energy that I really cannot keep quiet when John takes me out to exercise. Whatever I do, it seems I must jump or dance or prance, and I know I must have given him many a good shake, especially at the start. But he was always good and patient.")
fp(8,6,main="Ginger says that old Mr. Ryder could have brought her round, but he left the hard work to his son Samson. Samson was hard, and wanted to take all the spirit out of her.")
fp(9,3,simple="Ginger said that after her breaking in she was bought by a dealer to make a pair with another chestnut horse. For some weeks he drove them together. Then they were sold to a gentleman who liked the newest styles, and they were sent up to London. The dealer had driven her with a checkrein, and she hated it more than anything else. But in this place they pulled the reins much tighter, because the coachman and his master thought they looked more stylish that way. They were often driven around in the park and other places where fashionable people went. Ginger says that Black Beauty, who never had a checkrein on, does not know what it is, but she can tell him that it is terrible.")
fp(16,2,simple="After this my master and mistress decided to pay a visit to some friends who lived about forty-six miles from our home, and James was to drive them. The first day we traveled thirty-two miles. There were some long, heavy hills, but James drove so carefully and thoughtfully that we were not troubled at all. He never forgot to put on the brake as we went downhill, or to take it off at the right place. He kept our feet on the smoothest part of the road. If the hill going up was very long, he put the wheels of the carriage a little across the road so that it would not run back, and he let us stop to get our breath. All these little things help a horse very much, especially if he gets kind words as well.")
fp(17,8,main="The horses are afraid, and there is nobody they know to trust. A red light shows on the wall. The old hostler comes in and gets a horse out, but the fire is near the trapdoor.",
 simple="No doubt we were very foolish, but danger seemed to be all around, and there was nobody we knew and could trust, and everything was strange and not clear. The fresh air that came in through the open door made it easier to breathe, but the rushing sound over our heads grew louder. As I looked up through the bars of my empty rack, I saw a red light moving up and down on the wall. Then I heard a cry of “Fire!” outside, and the old hostler came in quietly and quickly. He got one horse out and went to another, but the flames were playing round the trapdoor, and the roaring overhead was terrible.")
fp(18,14,main="John tells James how he lost his parents when he was young, and how the mistress and old Norman helped him and his sister Nelly. He says he would not look down on a little boy.",
 simple="John says he does not often speak about himself. But as James is going away from them out into the world to manage for himself, John will tell him how he looks at these things. He was just as old as Joseph is when his father and mother died of a fever, within ten days of each other. They left him and his sister Nelly, who could not walk well, alone in the world with no relation to help them. He was a farm boy and did not earn enough to keep himself, and much less both of them. She would have had to go to the workhouse if it were not for their mistress. Nelly calls her her angel, and she is right to. The mistress got a room for Nelly with old Widow Mallet. She gave her knitting and sewing work when she could do it. When Nelly was ill she sent her dinners and many nice, comfortable things, and she was like a mother to her. Then the master took John into the stable under old Norman, who was the coachman then. John had his food at the house, a bed in the loft, a suit of clothes and three shillings a week, so he could help Nelly. Norman could have said that at his age he could not be troubled with a raw boy from the plow, but he was like a father to John and took great trouble with him. When the old man died some years later, John took his place. Now he has the best pay and can save money for a rainy day or a sunny day, and Nelly is as happy as a bird. So John is not the man to look down on a little boy and upset a good, kind master. He will miss James very much, but they will get through. He says nothing is better than doing a kindness when it comes your way, and he is glad he can do it.")
fp(19,16,main="On the way back the doctor lets the horse breathe. At home Joe rubs him but does not put on the warm cloth, and gives him cold water. The horse shakes with cold and pain until John comes and helps him.",
 simple="I will not tell about our way back. The doctor was a heavier man than John and not so good a rider, but I did my very best. The man at the tollgate had it open. When we came to the hill, the doctor stopped me. “Now, my good fellow,” he said, “take some breath.” I was glad he did, because I was nearly worn out, but that rest helped me on, and soon we were in the park. Joe was at the lodge gate, and my master was at the hall door, because he had heard us coming. He did not say a word. The doctor went into the house with him, and Joe led me to the stable. I was glad to get home. My legs shook under me, and I could only stand and breathe hard. I did not have a dry hair on my body, the water ran down my legs, and I steamed all over, like a pot on the fire, as Joe used to say. Poor Joe was young and small, and as yet he knew very little, and his father, who would have helped him, had been sent to the next village. But I am sure he did the very best he knew. He rubbed my legs and my chest, but he did not put my warm cloth on me, because he thought I was so hot that I would not like it. Then he gave me a pail of water to drink. It was cold and very good, and I drank it all. Then he gave me some hay and some corn, and thinking he had done right, he went away. Soon I began to shake and tremble, and I turned very cold. My legs ached, my loins ached and my chest ached, and I felt sore all over. How I wished for my warm, thick cloth as I stood and trembled! I wished for John, but he had eight miles to walk. So I lay down in my straw and tried to go to sleep. After a long time I heard John at the door. I gave a low moan, because I was in great pain. He was at my side in a moment, bending down by me. I could not tell him how I felt, but he seemed to know it all. He covered me up with two or three warm cloths and then ran to the house for hot water. He made me some warm gruel, which I drank, and then I think I went to sleep.")
fp(20,9,simple="John says: “Only ignorance! Only ignorance! How can you talk about only ignorance? Don’t you know that it is the worst thing in the world, after wickedness? And only heaven knows which does the most harm. If people can say, ‘Oh! I did not know, I did not mean any harm,’ they think it is all right. I suppose Martha Mulwash did not mean to kill that baby when she gave it Dalby and soothing syrups. But she did kill it, and she was tried for killing someone without meaning to.”")
fp(21,3,simple="The note was delivered, and we were riding home quietly when we came to the brick-field. Here we saw a cart heavily loaded with bricks. The wheels had stuck fast in the thick mud of some deep ruts, and the carter was shouting and beating the two horses without any pity. Joe pulled up. It was a sad sight. The two horses were pulling and fighting with all their strength to drag the cart out, but they could not move it. Sweat ran down their legs and sides, their sides were going up and down, and every muscle was pulled tight. The man pulled hard and fiercely at the head of the front horse, swore, and beat the horses in a very cruel way.")

import h as _h
def sub(ch,para,a,b,field='simple'):
    for x in _h.P:
        if x['chapter']==ch and x['paragraph']==para:
            assert a in x[field],(ch,para,a)
            x[field]=x[field].replace(a,b); FIXCOUNT['P'].add((ch,para)); return
fp(22,14,main="At the station the mistress says goodbye to John, and John cannot answer. The train goes away and leaves sad hearts behind.")
sub(23,20,"were having","were having") if False else None
sub(24,4,"against the bit in a hurry, as she did now","against the bit without patience, as she did now")
sub(25,14,"singing a little song under her breath","softly singing a little song")
sub(25,14,"He looked about in fear and","He looked about with worry and")
sub(31,3,"his wife raised and fed up birds and rabbits for sale","his wife raised poultry and rabbits and made them fat for sale")
sub(32,3,"I would say that he was the laziest and most proud man I ever came near.","I would say that he was the laziest man I ever came near, and the one who thought most highly of himself.")
sub(33,3,"showing their paces in fine style","showing off their paces in fine style")
fp(37,6,main="Jerry explains why he does not want to work on Sundays. He once had a seven-day license, but it was too hard for him and his horses. He wants Sundays for rest, for his family, and for a place of worship.")
fp(38,13,main="Jerry says that Polly is as good as the minister. He will be ready for Dinah at ten, and asks Polly to go and ask the butcher for his light trap.")
sub(40,4,"as many of them must in the busy time","as many of them must in the season")
fp(40,4,main="Sam says that the masters charge too much and the fares are too low. He and the horses must work very long hours, and he has had no Sunday for weeks and has no warm coat.")
sub(41,3,"fine ankles","fine lower legs")
sub(42,5,"and broke its wind,","and broke its breathing,")
fp(47,5,main="The horse tries again and again to pull the load, and the carter whips him. The pain in his mind is as bad as the pain in his body. Then a lady steps up and asks the carter not to whip the horse any more.")
fp(48,17,main="On Ludgate Hill the horse falls from the heavy load and from tiredness. He thinks he will die. He hears a sad voice say it is all their fault. People loosen his harness and give him cordial.")
sub(49,3,"One weak old man liked me very much","One old man who walked in a shaky way liked me very much")
sub(49,3,"gave a sad look round at us","gave a look full of pity round at us")
