from fixes import *
fs(4,simple="Those who have never had a bit in their mouths cannot imagine how bad it feels.")
fs(6,simple="If it were not for bringing back the past.")
fs(8,simple="He had only just got up on my back on the training ground.")
fs(10,simple="I would not do such a thing for the very best oats that ever came into the stable.")
fs(11,simple="If the lamp on the left side had not gone out, John would have seen the great hole.")
fs(13,simple="It would be rather awkward if one of these branches came down on us.")
fs(17,simple="If she had not heard me outside, she would never have had the courage to come out.")
fs(20,simple="Do you not know that it is the worst thing in the world, after wickedness?")
fs(23,simple="If she were treated badly or unfairly, she would quite likely pay people back in the same way.")
fs(24,simple="There is no knowing what more harm she might have done if York had not quickly sat down flat on her head.")
fs(27,simple="If he had been thinking clearly, he would just as soon have tried to ride him over the moon.")
fs(28,simple="The mare will have a year in the field, and we will see what that will do for her.",grammar="'shall' with 'the mare' and 'we' shows the earl's decision, not just the future; 'twelvemonth’s run' is a year of free time in a field.")
fs(33,simple="If a horse can say what he thinks, as far as he understands.",grammar="'may speak his mind' uses 'may' to mean 'is allowed to'; 'speak his mind' means 'say what he thinks'; 'so far as' means 'as far as'.")
fs(34,simple="I think I do not have to find out about something wrong until it shows itself.")
fs(35,grammar="'so long as' means 'as long as'; it begins a clause that gives the condition under which none of the horses gave way to fear.")
fs(38,simple="We should do to other people what we would like them to do to us.")
fs(39,simple="Do you know the reason this world is as bad as it is?",grammar="'as bad as it is' means 'as bad as it now is'; 'why' starts an indirect question after 'know'.")
fs(43,simple="I could not, with a clear sense of what is right, send him up to make laws.",grammar="'in my conscience' means 'with my sense of right and wrong'; 'send him up' means to choose him for the job of making the laws.")
fs(45,simple="It was a bad wind that blew good to nobody.")
fs(30,1,simple="I think that if he had let me just look at things quietly and see that there was nothing to hurt me, it would have been all right, and I would have got used to them.")
KEEP="""think a great deal of|make out|break in|get rid of|get used to|loose box|turn out|pull up|keep step|bring round|give up|put out|by and by|make up one's mind|go to the bad|take thought for|by turns|take in good part|by way of|give a lesson|show off|depend upon|give way|done away with|look out for|tear up|serve him right|knock about|beat the bush|keep one's wits about one|look sharp|step into|stand in someone's light|rub down|into the bargain|take to|get into the habit of|make way|take care of number one|lay by|turn up one's nose at|pull through|hold with|a good turn|draw up|ride for one's life|to say nothing of|cut up|mind one's own business|lay on|in high spirits|take in hand|set up|tit for tat|bearing rein|make the best of|by degrees|part with|be a match for|wash one's hands of|catch sight of|on account of|hold in|break out|have a care|tell you what|make believe|in spite of|keep up with|job horse|let out|come to pass|prevail upon|all of a sudden|tell upon|feel over|take cold|run up|beat down|speak one's mind|give the benefit of the doubt|make much of|take pains|pass remarks|keep up one's spirits|take upon oneself|so long as|put on the steam|be set against|for a wonder|year in and year out|take it to heart|take someone's part|go to the bottom of|turn a shilling|for that matter|out of sorts|and welcome|hard lines|cast up|blow up|run foul of|a great mind to|while there's life there's hope|laugh off|take the heart out of|give him his head|I'll be bound|do him the justice|go to the dogs|hold one's tongue|out of hand|draw blood|trot out|run down|take a fancy to|handsome is that handsome does|on trial|on the spot|in no time|set down|go to one's heart|come round|take oversight of|have the tending of|look sharp""".split('|')
import h as _h
for k in list(_h.PH):
    if k not in KEEP: dph(k)
fph('so long as',meaning='As long as; if.')
DROP="""think a great deal of|loose box|keep step|bring round|by turns|take in good part|by way of|give a lesson|done away with|tear up|knock about|beat the bush|step into|stand in someone's light|rub down|into the bargain|take to|get into the habit of|lay by|pull through|hold with|a good turn|to say nothing of|cut up|lay on|set up|part with|be a match for|catch sight of|hold in|break out|have a care|tell you what|keep up with|job horse|let out|prevail upon|tell upon|feel over|take cold|run up|beat down|give the benefit of the doubt|pass remarks|take upon oneself|be set against|year in and year out|take someone's part|go to the bottom of|turn a shilling|for that matter|and welcome|cast up|blow up|run foul of|laugh off|give him his head|do him the justice|draw blood|trot out|run down|take oversight of|have the tending of|set down""".split('|')
for k in DROP:
    if k in _h.PH: dph(k)
