M2 = {
"vice":"A bad way of acting in a horse, such as biting or kicking.",
"crupper":"A band that goes under a horse's tail to keep the other bands from moving forward.",
"chaise":"A light vehicle with two big round parts that roll, pulled by a horse.",
"forge":"A place with a fire, where iron is heated and shaped, for example into shoes for horses.",
"pert":"Lively and full of fun, in a pleasant way.",
"slacken":"To become slower or less strong.",
"forelock":"The hair at the top of a horse's head that falls down in front, between the eyes.",
"flog":"To hit hard again and again, to make an animal or person go faster or to hurt them.",
"checkrein":"A band that holds a horse's head up high and back.",
"chafe":"To pull against something that holds you and feel angry and restless about it.",
"surly":"Rude and unfriendly; in a bad temper.",
"warranted":"Promised by the seller to be good. Here the seller says the horse has no bad ways.",
"rogue":"A person who is a little bad, but in a funny way; here said in a friendly way to an animal.",
"tassel":"A small group of hairs joined at one end, with the other end free.",
"distended":"Made wide and big, as when something presses from inside.",
"scheme":"A plan. Here it is a plan that a man loves more than all others.",
"trademark":"A sign that shows who made something. Here, cruelty is said to be the sign of the Devil.",
"hostler":"A man who looks after the horses at a hotel.",
"flicker":"To give light that goes bright and dim again and again.",
"needlework":"Work done by hand to make or fix clothes.",
"hoe":"To work the ground with a small tool to cut down plants that you do not want.",
"towering":"Very great and strong; here, a man who is full of great anger.",
"puff":"To send out smoke in short, quick pushes.",
"drab":"A yellow-brown colour that is not bright.",
"terret":"A metal ring on a horse's back, through which the long bands held by the driver pass.",
"winch":"A tool with a handle that you turn, used to move heavy things up or take metal pieces apart.",
"trace":"One of the bands that join the horse to the vehicle it pulls.",
"sponge":"To clean something with a soft thing that holds water.",
"curb":"A band under a horse's mouth that works with the bit to give the driver more control.",
"blunder":"To move in a heavy, careless way and hit things.",
"furze":"A wild plant with many sharp points and bright yellow colour when it is in flower.",
"blemish":"A bad spot on the skin that makes something look worse.",
"caustic":"A very strong thing that eats into the skin, once used by doctors on hurt places.",
"lime":"A tall tree with soft green leaves.",
"relax":"To let go; to stop pulling hard.",
"slovenly":"Careless in the way you work or dress.",
"jag":"To pull hard with a sudden pull that hurts.",
"shindy":"A loud noise and trouble made by people.",
"scrub":"A very hard cleaning, done with a lot of strong work.",
"thrush":"A painful illness of a horse's foot that comes when it stands in wet and bad places.",
"tow":"Rough pieces from a plant, pressed into a hole.",
"dumpling":"A small ball of soft, cooked food.",
"trim":"Looking clean and well kept.",
"palisades":"A line of tall iron or wood posts that stops people from going through.",
"trumpet":"A shiny metal thing that makes a loud, clear sound when air is sent through it with the mouth.",
"bombshell":"A metal ball shot from a big gun that bursts and breaks into pieces.",
"caparison":"To dress a horse in its full covering and fine things for a special day or a war.",
"fare":"A person who pays to be driven somewhere; also the money that he pays.",
"shafts":"The two long pieces of wood between which a horse stands to pull a vehicle.",
"license":"A paper from the government that says you may do something, such as drive a vehicle for money.",
"hawthorn":"A small tree with sharp points on it that is white in spring when it is in flower.",
"spray":"A small piece of a plant with leaves and a flower on it.",
"hymn":"A song for singing in church to God.",
"rough":"To fit a horse with shoes that have sharp parts, so that it can walk on ice without falling.",
"pickpocket":"A person who takes things out of the clothes of other people without asking.",
"belly":"The part of an animal's body that faces the ground.",
"mutton":"A kind of meat from a farm animal, often cooked for dinner.",
"ragamuffin":"A child in old clothes that are not clean.",
"puffy":"Round and a little fat, and breathing hard.",
"drayman":"A man who drives a big flat vehicle that carries heavy things.",
"chime":"To make a clear ringing sound at set times to tell the hour.",
"slush":"Wet, soft ice and water on the street.",
"hitch":"To fix something up in place with a band.",
"linseed":"The seed of a plant, given to animals as food.",
"tottering":"Walking in a way that looks as if you will fall, as an old or weak person does.",
"polish":"What you put on something to make it bright, or the bright look it gives.",
"blemished":"Having a bad spot that makes it look worse.",
"hobby":"Something you love to do or talk about. Here it is the master's strong idea about how horses are driven.",
}

M2.update({
"pert":"Lively and full of fun, in a nice way.",
"surly":"Rude and unfriendly in the way you speak.",
"trademark":"A sign that shows who made something. Here, hurting others is said to be the sign of the Devil.",
"flicker":"To give light that goes bright and weak again and again.",
"bombshell":"A metal ball shot from a big gun that breaks into pieces.",
"puffy":"Round and a little fat, and taking in air hard.",
})
