RW = "two big round parts that roll"
M = {
"hedge":"A line of small trees and plants that makes a wall around a field.",
"carthorse":"A big, strong horse used to pull heavy things on the road or in the fields.",
"temper":"The way a person or animal usually feels and acts, such as gentle or angry.",
"gig":"A light open vehicle with "+RW+", pulled by one horse.",
"plowboy":"A boy who works on a farm and helps to turn over the earth in the fields.",
"pluck":"To pick fruit from a plant with your fingers.",
"mist":"Very small drops of water in the air near the ground, which make it hard to see far.",
"hound":"A dog that people use to follow and chase wild animals.",
"hare":"A wild animal with long back legs that runs very fast and jumps; dogs chase it.",
"scent":"What an animal leaves in the air or on the ground, so that dogs can find it with their noses.",
"canter":"To run at an easy, smooth speed, not very fast and not slow, as a horse does.",
"huntsman":"A man who rides after the dogs when they chase wild animals.",
"stag":"The male of a large wild animal of the woods that men chase for sport.",
"churchyard":"The ground around a church where dead people are put into the earth.",
"vice":"A bad fault in a horse, such as biting or kicking.",
"bridle":"The set of bands and metal parts that go on a horse's head, used to control it.",
"collar":"A thick, hard ring round a horse's neck and shoulders, used to pull a vehicle.",
"crupper":"A band that goes under a horse's tail to stop its other gear from sliding forward.",
"breeching":"A wide band round the back legs of a horse that lets it hold back the vehicle it pulls.",
"chaise":"A light vehicle with "+RW+", pulled by a horse or pony.",
"harness":"All the bands and parts that a horse wears to pull a vehicle.",
"halter":"A rope or band round a horse's head, used to lead it.",
"girth":"A band under a horse's body that keeps the rider's seat in place.",
"forge":"A workshop with a fire, where iron is heated and shaped, for example into shoes for horses.",
"blinkers":"Two pieces at the sides of a horse's eyes that stop it from seeing to the side.",
"restive":"Not willing to stay still or be quiet; hard to control.",
"lodge":"A small house at the way into a big park or house.",
"paddock":"A small field near the house where horses can walk and eat grass.",
"stall":"A small space for one horse, in the building where horses are kept.",
"rack":"A holder fixed to the wall that keeps dry grass for a horse to eat.",
"manger":"A long open box that holds food for a horse.",
"pert":"Lively and not shy, in a pleasant way.",
"coachman":"A man whose job is to drive a vehicle pulled by horses for a rich family.",
"hunter":"A strong horse that people ride when they chase wild animals with dogs.",
"roan":"Having a coat in which white hairs are mixed with brown or black ones; used of horses.",
"slacken":"To become slower or less tight.",
"skittish":"Easily scared or excited; a skittish horse jumps and moves around a lot.",
"weaned":"Taken away from its mother's milk, so that it now eats other food.",
"forelock":"The hair at the top of a horse's head that hangs down in front, between the eyes.",
"flog":"To hit hard again and again, to make an animal or person go faster or as a punishment.",
"fret":"To be worried or unhappy and not able to be quiet or still.",
"persecutor":"A person who hurts or troubles someone again and again.",
"flank":"The side of an animal's body, behind the middle and above the back leg.",
"sieve":"A round holder with many small holes in it. Here it holds food for the horse.",
"mash":"A warm, soft food for horses made from the rough outside of grain and hot water.",
"mettled":"Full of life and very brave. 'High-mettled' means a lively, brave horse.",
"checkrein":"A band that holds a horse's head up high. It is also called a bearing-rein.",
"chafe":"To rub against something and feel angry and restless about it.",
"froth":"White bubbles that come out of a horse's mouth when it pulls hard.",
"turnout":"A vehicle and its horses, as they look to other people.",
"surly":"Rude and unfriendly, in a bad mood.",
"windpipe":"The long inside part of the neck that air goes through when you take it in.",
"buckle":"To hold something in place with a band and a metal piece that closes it.",
"warranted":"Promised by the seller to be good. Here the horse is said to have no bad faults.",
"defiant":"Showing that you will not do what you are told.",
"vicious":"Very rough and angry, and likely to hurt others.",
"vicar":"A man who leads the church in a village.",
"rogue":"A person who is a little bad, but in a funny way; here said in a friendly way to a pony.",
"preach":"To tell people in a long way what is right, when they do not want to hear it.",
"hazel":"A tree with thin sticks that bend easily; here a stick cut from it.",
"drover":"A man whose job is to take farm animals from one place to another on foot.",
"gypsy":"A person from a group of people who have no fixed home and move from place to place.",
"spree":"A short, lively time of fun, often with drinking.",
"tassel":"A small group of hairs tied together at one end, with the other end free.",
"indignity":"Something done to you that makes you feel you are less important.",
"torment":"Very great pain or trouble that goes on for a long time.",
"lash":"To hit hard and quickly, again and again.",
"distended":"Stretched wide and big, as when something presses from inside.",
"brute":"A rough, unkind person or animal.",
"hearse":"A long vehicle that carries a dead person to the place where he will be put in the earth.",
"oppressed":"Treated in a hard, unfair way by someone who has power over you.",
"laden":"Carrying a lot of heavy things.",
"bay":"Red-brown in colour, with black hair on the legs and tail; used of horses.",
"stern":"Serious and hard, and not smiling.",
"parade":"A show where soldiers walk together in lines to be looked at.",
"bayonet":"A long, sharp point of metal fixed to the end of a gun, used in a fight.",
"scheme":"A plan. A 'pet scheme' is a plan that someone loves most.",
"sensitive":"Quick to feel things, even a very light touch.",
"dogcart":"A light open vehicle with two high round rolling parts, pulled by one horse.",
"bait":"Food and rest given to a horse on the way during a trip.",
"twig":"A very thin stick from a tree.",
"tollgate":"A place on a road or bridge where people stop and pay money to go through.",
"lull":"To become quieter and softer.",
"prompt":"Quick; done at once.",
"bully":"To be rough and unkind to people who are weaker than you.",
"sprawl":"To lie with your arms and legs spread out wide.",
"sham":"Something that looks real but is not.",
"trademark":"A sign by which you know who a thing belongs to; here, a sign of the devil.",
"livery":"Special clothes of the same kind that the workers of a rich house wear.",
"droll":"Funny in a quiet, strange way.",
"omnibus":"A large vehicle pulled by horses that carries many people along a road for money.",
"cab":"A vehicle with a driver, pulled by a horse, that people pay to take them from place to place.",
"brake":"A part on a vehicle that is used to make it go slower.",
"downhill":"Going down a hill.",
"hostler":"A man who looks after the horses of visitors at a hotel.",
"archway":"A way through a building, with a curved top.",
"waistcoat":"A short piece of clothing with no arms, worn on the top half of the body under a coat.",
"unbuckle":"To open a band that is held closed by a metal piece.",
"turf":"Short grass; here it means the grass of the ground where horses race.",
"timid":"Easily scared.",
"lounge":"To walk or stand around slowly, with nothing to do.",
"loft":"A room high up under the top of a building, where dry grass for horses is kept.",
"trapdoor":"A small door in a floor, that opens up or down.",
"lantern":"A light with a handle that you can carry, with the fire inside glass.",
"flicker":"To give light in an unsteady way, going bright and dim again and again.",
"smother":"Thick smoke that makes it hard to take in air.",
"rafter":"One of the long pieces of wood that hold up the top of a building.",
"hasten":"To go quickly.",
"shift":"To look after yourself, with no one to help you.",
"needlework":"Work done by hand to make or mend clothes.",
"hoe":"To dig the ground with a small tool to cut down plants that you do not want.",
"turnip":"A round, white food plant that grows under the ground.",
"shilling":"An old piece of British money.",
"spur":"A small sharp metal point worn on a rider's foot, used to make a horse go faster.",
"nightcap":"A soft thing worn on the head in bed at night.",
"loins":"The lower part of the back, at the top of the back legs.",
"gruel":"A thin, warm food for a sick person or horse, made from grain and hot water.",
"pant":"To take in air very quickly and often, after running.",
"pailful":"As much as a large water container with a handle can hold.",
"bleed":"To lose blood. As an old treatment, doctors also took blood from a sick person or animal to make them better.",
"faint":"Weak, as if you might fall.",
"mischief":"Trouble or damage caused by what someone does.",
"rut":"A deep line in the road made by a vehicle going over it again and again.",
"carter":"A man whose job is to drive a heavy horse vehicle that carries things.",
"towering":"Very great and strong. Here it describes a man who is very, very angry.",
"oppression":"Hard, unfair treatment by someone with power.",
"establishment":"A big house with all the workers and animals that live and work there.",
"earl":"A British lord of high position.",
"faithful":"True to someone and always ready to help.",
"repay":"To give something back to someone who gave to you, such as money or kindness.",
"cushion":"A soft bag that you sit on or put behind your back.",
"guard":"On a train, the man who looks after it and tells it when to go.",
"puff":"To send out smoke in short, quick bursts.",
"vicarage":"The house where the church leader of a village lives.",
"peculiarity":"Something strange or special about a person or animal.",
"drab":"A plain yellow-brown colour that is not bright.",
"breeches":"Short clothes for the legs, close at the bottom, worn by men long ago.",
"rustle":"To make a soft sound, like dry leaves moving.",
"nuisance":"Something that causes trouble or makes you cross.",
"imperious":"Proud and used to telling others what to do.",
"terret":"A metal ring on a horse's back, through which the reins pass.",
"winch":"A tool with a handle that you turn to lift heavy things or to undo metal pieces.",
"trace":"One of the bands or chains that join the horse to the vehicle it pulls.",
"unhitch":"To set a horse free from the vehicle it pulls.",
"confound":"A word people say when they are very angry at something, a bit like 'bother it!'",
"lotion":"A liquid that you put on the skin to make it better.",
"sponge":"To wash or wipe something with a soft thing that holds water.",
"bruised":"Having a dark place on the skin from being hit.",
"thoroughbred":"Having a long line of fine racing horses as its family.",
"sidesaddle":"A seat for a horse made so that a woman can sit with both legs on one side.",
"amiable":"Friendly and kind.",
"curb":"A band or chain on a horse's bit that presses under its mouth when the reins are pulled.",
"evergreen":"A tree that keeps its green leaves all through the year.",
"alight":"To get down from a horse or a vehicle.",
"blunder":"To move in a heavy, careless way and knock into things.",
"heather":"A low plant that grows on open hills and covers the ground.",
"furze":"A plant with many sharp points and small yellow flowers.",
"dike":"A long, narrow hole cut in the ground, often with water in it.",
"clod":"A hard piece of earth.",
"ghastly":"Looking very white and ill, like a dead person.",
"veterinary":"To do with the care of sick animals. A veterinary doctor is a doctor for animals.",
"tandem":"A vehicle pulled by two horses, one in front of the other.",
"brougham":"A closed vehicle with four round rolling parts, pulled by one horse.",
"turnpike":"A place on a road where people stop and pay money to go through.",
"quick":"The soft part of a horse's foot under the hard outside, which feels pain easily.",
"poultice":"A soft, warm, wet mix put on a hurt place to make it better.",
"blemish":"A bad spot on the skin that spoils how something looks.",
"caustic":"A very strong thing that burns the skin, once used by doctors on hurt places.",
"blister":"To make the skin rise up with water under it.",
"hobble":"To walk with pain or trouble, with small, uneven steps.",
"steeplechase":"A horse race across open land, with walls and holes to jump over.",
"drunkard":"A person who drinks too much beer or wine and is often drunk.",
"lime":"A tall shady tree with soft green leaves.",
"slope":"A surface that goes up or down, not flat.",
"relax":"To let go; to become less tight.",
"slovenly":"Careless and not neat.",
"phaeton":"A light open vehicle with four big rolling parts, pulled by one or two horses.",
"flop":"To let something move up and down in a weak way, without care.",
"wedge":"To push something hard into a narrow space so that it cannot move.",
"frog":"The soft part under the middle of a horse's foot.",
"plied":"Used hard and many times; here the driver keeps hitting the horse.",
"jag":"To pull with a rough, sudden jerk that hurts.",
"shaft":"One of the two long pieces of wood between which a horse stands to pull a vehicle.",
"dun":"A brown-yellow colour; used of horses.",
"shuffling":"Moving with the feet low on the ground, in short, slow steps.",
"shindy":"A loud fuss.",
"vetch":"A small plant that is grown as food for animals.",
"humbug":"A person who says he is good or kind but is not.",
"rusty":"Covered with red-brown spots because of water on metal.",
"indolent":"Not wanting to work or move.",
"vapor":"A gas that comes up from something wet or bad.",
"inflame":"To make a part of the body red, hot and painful.",
"scrub":"A very hard wash to get all the dirt off.",
"drain":"A way under the ground that carries used water away from a building.",
"bricklayer":"A man whose job is to build walls from small hard blocks.",
"feverish":"Hot and ill, as when your body is too hot because of illness.",
"thrush":"A painful illness of a horse's foot that comes from wet and bad dirt.",
"liniment":"A liquid that you put on a painful place to make it better.",
"tow":"Rough pieces from a plant, pressed into a hole to fill it.",
"braid":"To join three parts of hair together by crossing them over and over.",
"knuckle":"To bend. 'Knuckling over' is when a horse's leg bends forward at the joint.",
"trickery":"Clever lies and plans used to take money from people.",
"flashy":"Very bright to look at, but not of good quality.",
"hayloft":"A room high up where dry grass for horses is kept.",
"sixpence":"An old piece of British money; a small amount.",
"dumpling":"A small ball of soft food made from flour and water, cooked and eaten hot.",
"plump":"Round and a little fat, in a nice way.",
"trim":"Clean and neat.",
"brick":"Here, a word for a very good person that you can trust.",
"palisades":"A line of tall iron or wooden posts that stops people from going through.",
"comforter":"A long, warm cloth worn round the neck.",
"dispute":"An angry talk between people who do not agree.",
"bucketful":"As much as a large water container with a handle can hold.",
"trumpet":"A shiny metal thing that you blow with your mouth to make a loud, clear sound.",
"hardship":"A thing that makes life hard, such as cold, pain or having no food.",
"bombshell":"A metal ball filled with something that blows up, shot from a big gun.",
"lance":"A long stick with a sharp metal point, used as a weapon by soldiers on horses.",
"saber":"A heavy sword that is curved.",
"caparison":"To dress a horse in fine, full gear and covering for a special day or a war.",
"champ":"To bite on something again and again with a loud sound.",
"musket":"An old kind of gun with a long, thin front part.",
"whiz":"To make a high sound as it flies very fast through the air.",
"quarrel":"An angry talk between people who do not agree.",
"cabby":"A man whose job is to drive a horse vehicle that people pay to use.",
"fare":"A person who pays to ride in a hired vehicle; also the money that he pays.",
"wagon":"A big vehicle with four rolling parts, pulled by horses, for carrying heavy things.",
"gammon":"A word used to say 'That is not true!'",
"shafts":"The two long pieces of wood between which a horse stands to pull a hired vehicle or a cart.",
"license":"A paper from the government that says you may do something, such as drive a hired vehicle for money.",
"worship":"The act of showing love and respect to God, for example in church.",
"sovereign":"An old British piece of gold money.",
"cabman":"A man whose job is to drive a horse vehicle that people pay to use.",
"trap":"A light open vehicle with "+RW+", pulled by one horse.",
"hawthorn":"A small tree with sharp points on it and white flowers in spring.",
"spray":"A small piece of a plant with leaves and flowers on it.",
"ivy":"A plant with green leaves that grows up walls and trees.",
"hymn":"A song sung in church to God.",
"cowshed":"A small building where farm animals that give milk are kept.",
"sheer":"Complete; nothing but.",
"sleet":"Cold rain with small bits of ice in it.",
"rough":"To make a horse's shoes sharp underneath, so that it does not slip on ice.",
"pudding":"A sweet, soft food, eaten after the main food.",
"basin":"A round, deep bowl for food or water.",
"brutal":"Very rough and unkind.",
"doctrine":"An idea or rule that a person holds to be true and teaches to others.",
"tattered":"Old and broken into pieces at the edges, with holes.",
"twopence":"An old piece of British money; a very small amount.",
"pickpocket":"A person who takes things from other people's pockets without asking.",
"dram":"A small drink of a strong drink that makes you drunk.",
"rave":"To talk in a wild way, as someone does when very ill and hot.",
"starve":"To be very hungry, or to die, because you have no food.",
"knuckled":"Bent forward at the joint of the leg, so that the leg cannot hold the body up well.",
"lock":"A small group of hairs or dry grass that stay together.",
"lank":"Thin and soft, not firm.",
"fetlock":"The part of a horse's leg just above its foot, where there is often long hair.",
"heave":"To move up and down with effort, as sides do when taking in air hard.",
"merciful":"Kind to those who are in pain.",
"sunken":"Low and pushed in, deeper than it should be.",
"belly":"The lower part of an animal's body, underneath.",
"sullen":"Angry and not wanting to speak.",
"mutton":"A kind of meat that comes from a grown farm animal that gives wool.",
"coster":"A man who sells fruit and green food from a small vehicle in the street.",
"vote":"A choice that a person makes to help decide who will lead or make the laws.",
"voter":"A person who has a vote.",
"spatter":"To cover with small drops of wet earth or water.",
"ragamuffin":"A child in old, dirty clothes.",
"puffy":"Round and a little fat, and out of breath.",
"nosebag":"A bag of food that is put over a horse's nose so it can eat.",
"munch":"To eat with your mouth working, often with a sound.",
"hurrah":"To shout 'Hurrah!', a happy shout of support.",
"bewildered":"Very surprised and not sure what to do.",
"dodge":"A clever plan to get out of something.",
"buttonhole":"A small hole in a coat, where a small flower or a coloured band can be put.",
"candidate":"A person who is trying to be chosen by votes.",
"dray":"A strong, flat vehicle pulled by horses, used to carry heavy things such as beer.",
"drayman":"A man who drives a dray.",
"damages":"Money that a court says must be paid for a wrong done to someone.",
"compensation":"Money paid to someone for a wrong or a loss.",
"canker":"To slowly eat away at something and make it bad.",
"martingale":"A band that goes from under a horse's body to its head, used to keep the horse's head down.",
"guinea":"An old piece of British money that was worth a lot; a 'hundred-guinea' horse was very costly.",
"monument":"A tall building or stone that people build so that they remember something.",
"harvest":"The time when farm plants are cut and brought in; here, a time when a lot of money is made.",
"punctual":"Coming at the right time and not late.",
"chime":"To make a clear ringing sound, as a clock does.",
"bronchitis":"A serious illness that makes it hard to take in air.",
"slush":"Wet, half-melted ice and water on the street.",
"pageboy":"A young boy who works for a rich family and wears special clothes.",
"henhouse":"A small building for birds that lay eggs.",
"rubdown":"Cleaning and drying the body by pushing a cloth over it hard.",
"overload":"To put too much weight on a horse or vehicle.",
"hitch":"To fix something up in place with a band or loop.",
"purblind":"Almost not able to see.",
"linseed":"A food for animals, made from the oily part of a plant.",
"gasping":"Taking in air in quick, loud pulls because of trouble or pain.",
"tottering":"Walking in a shaky way, as an old or weak person does.",
"grandpapa":"The father of a child's father or mother.",
"horsey":"Loving horses and knowing a lot about them.",
"speculation":"Buying something when you are not sure if it will bring you gain or loss.",
"polish":"The shine on something, or what you put on to make it shine.",
"shrubbery":"A group of small plants and trees growing close together in a garden.",
"blemished":"Having a bad spot that spoils the way it looks.",
"knot":"A hard small piece under the skin.",
"threepenny":"Worth three of the smallest pieces of old British money; 'threepenny bit' was a small old piece of money.",
"extraordinary":"Much more than is normal.",
"tarbrush":"A tool used to put something black and shiny on a horse's feet to make them look dark and bright.",
"rein":"A long band fixed to a horse's head, held by the rider or driver to control the horse.",
"slave":"To make someone work very hard, like a slave. 'Slaved about' means made to work hard and treated badly.",
"snap":"To bite at someone quickly. 'In a snap' means in a moment.",
"hobby":"Something you love to do or talk about. Here it is the master's idea about checkreins.",
"stout":"Strong and thick. For a person it also means rather fat.",
"slight":"Small in size or amount; not much.",
"toll":"To make slow, deep ringing sounds, for example when someone has died.",
}
