M = {
"disagreeable": "Not nice. Unkind and not good to be with.",
"sour": "Unhappy and cross. Here it describes the look on a face.",
"ayah": "In India, a woman whose job is to take care of a child.",
"sahib": "In India, a word of respect. 'Mem Sahib' is used for a European woman, and 'Missie Sahib' for a girl.",
"fretful": "Unhappy, and crying or saying what is wrong all the time.",
"stammered": "Spoke with many stops and the same sounds again and again, because of fear.",
"slunk": "Moved quietly and secretly, because of fear or feeling bad about something done.",
"hibiscus": "A plant with big, bright flowers that grows in hot countries.",
"imploringly": "In a way that asks very hard for help.",
"wrung": "Squeezed and turned hard. 'Wrung her hands' shows great worry or sadness.",
"bewilderment": "The state of not understanding and not knowing what to do.",
"drowsy": "Wanting to sleep; half asleep.",
"hastily": "Very quickly, because there is little time.",
"compound": "The land with a wall around a group of buildings.",
"clergyman": "A man whose job is to lead people in a church.",
"rockery": "A part of a garden made with big stones and small plants.",
"contrary": "Always going against what other people want.",
"hunchback": "A person with a bent back that has a bump on it.",
"housekeeper": "A person whose job is to run a big house and tell the other workers what to do.",
"mantle": "A loose coat with no part for the arms, worn over other clothes.",
"fringe": "An edge made of many small strings that hang down.",
"bonnet": "A woman's hat that is held on with a band under the chin.",
"sallow": "Of skin: a yellow colour that does not look healthy.",
"marred": "Spoiled. In this book a Yorkshire word for a child who has been spoiled and is cross.",
"dreary": "Sad and without anything nice to see or do.",
"lulled": "Made quiet and sleepy by a soft, even sound.",
"stationmaster": "The person in charge of a train station.",
"thee": "A Yorkshire way to say 'you' (after a word like 'to'), used to one person.",
"brougham": "A closed vehicle pulled by a horse, with four wheels, used by rich people long ago.",
"footman": "A man whose job is to open doors and help people get in and out of a vehicle.",
"coachman": "A man whose job is to drive the horses that pull a vehicle.",
"cushioned": "Made soft with something soft inside.",
"timid": "Easily scared; not brave.",
"whitewashed": "Made white by covering with a thin white liquid that is cheap.",
"vicarage": "The house where the man who leads a village church lives.",
"heather": "A low wild plant with tiny flowers of a red-blue colour, found on wild open hills.",
"gorse": "A wild plant with sharp points and yellow flowers.",
"broom": "A wild plant with long thin stems and yellow flowers. Here it is a plant, not a tool for cleaning floors.",
"bleak": "Cold, empty and unfriendly.",
"lodge": "A small house at the way in to a big house or park.",
"vault": "A curved top over a space. Here the trees make it look like the top of a long dark room.",
"ramble": "To spread in all directions without order, as a big house does.",
"tapestry": "A heavy cloth with a picture made in it, hung on a wall.",
"embroidered": "Having a picture or pattern sewn on cloth.",
"turret": "A small, thin, high part of a castle, built at a corner.",
"obsequious": "Too ready to please a person who has power over you.",
"servile": "Acting as if you have no wish of your own and doing all you are told.",
"salaam": "In India, a way to show respect: bending low with the hand at the head.",
"scullery": "A small room next to a kitchen where dishes and pans are washed.",
"vexed": "Made a little angry.",
"humiliation": "The feeling of being made to look silly in front of others.",
"subservient": "Too ready to do what other people say.",
"totter": "To walk with weak steps, as if you may fall.",
"homely": "Simple, like home. Here it means friendly and kind, not grand.",
"marmalade": "A sweet sticky food made from fruit, eaten at breakfast.",
"ivy": "A plant with dark green leaves that grows up walls.",
"surly": "Rude and in a bad mood.",
"crustily": "In a rude way, as if in a bad mood.",
"mester": "A Yorkshire way to say 'master'.",
"blunt": "Saying what you think in a direct way, without trying to be polite.",
"tapestried": "Having walls covered with heavy cloth that has pictures made in it.",
"preen": "When a bird preens, it cleans and straightens the soft covering of its body with its beak.",
"wutherin": "A Yorkshire word for the sound of strong wind, a loud low noise that goes on and on. The book writes it as wutherin'.",
"shuddering": "Moving the body in short quick movements because of fear or cold.",
"moithered": "A Yorkshire word for mixed up and upset by too much noise or work, not able to think clearly.",
"collie": "A kind of dog with long hair, used by farmers to watch farm animals.",
"perplexed": "Not understanding and not sure what to do or think.",
"pewter": "A soft metal used to make cups and dishes.",
"romping": "Playing in a loud, rough way.",
"gallery": "A long room or hall, here with pictures on the walls.",
"ruffs": "Wide, round, folded cloth worn around the neck long ago.",
"brocade": "A rich cloth with a raised design in it.",
"inlaid": "With small pieces of another material set into the surface to make a picture.",
"mantel": "The part above a fire in the wall of a room, where you can put things.",
"cabinet": "A tall box with doors, for keeping things.",
"ivory": "The hard white material from the long teeth of an elephant.",
"mahout": "A man in India whose job is to ride and look after a very large animal with a long nose.",
"palanquin": "A covered seat or bed carried by people on long sticks, or on an animal.",
"soart": "A Yorkshire way to say 'sort', meaning 'kind'.",
"vixon": "A Yorkshire way to say 'vixen': a sharp, angry girl or woman. Martha's mother uses it for a girl in a bad mood.",
"daffydowndilly": "An old, playful name for a yellow flower that comes in spring.",
"mole": "A small animal that makes long holes in the ground to live in.",
"baffling": "Very hard to understand.",
"glossy": "Smooth and shiny.",
"contrariness": "The habit of going against what other people want.",
"fumbling": "Using your hands in a poor, awkward way to find or hold something.",
"skip": "To jump over a rope that is turned under your feet and over your head.",
"tuppence": "Two pence, a small amount of old British money.",
"impudence": "Rude words or actions that show no respect.",
"clumsy": "Not smooth or careful in how you move; likely to drop things or hit them.",
"trill": "A quick, high song of a bird, with the same sound again and again, fast.",
"heathen": "A person who does not follow the religion of the speaker. Here it is said of people who do not follow his own faith.",
"pipin": "Very hot. The book writes it as pipin'.",
"tendril": "A thin, curly part of a plant that holds on to things.",
"hazy": "Not clear, as if seen through thin cloud.",
"alcove": "A small space set back in a wall or in a line of plants.",
"urn": "A tall container with a wide top and a base, used for plants.",
"narcissus": "A white or yellow flower that comes in spring and smells sweet.",
"jonquil": "A small yellow or white flower that comes in spring.",
"eyeteeth": "The two pointed teeth at the top of the mouth, on each side of the front teeth. 'Like pulling eyeteeth' means very hard to do.",
"dictated": "Spoke words for someone else to write down.",
"restlessly": "In a way that shows you cannot keep still.",
"flightiness": "Acting in a way that changes quickly and cannot be trusted.",
"hobnailed": "Of shoes: with thick pieces of metal in the bottom to make them strong.",
"bachelder": "A man who is not married, as a Yorkshire speaker says it.",
"rheumatics": "An old word for a sickness that makes the knees and other joints hurt.",
"pheasant": "A large wild bird with a long tail. People shoot it for food.",
"tremulous": "Not steady; moving a little in a way you cannot stop.",
"trowel": "A small garden tool with a short handle, used to dig small holes.",
"hoe": "A garden tool with a long handle and a flat end, used for cutting down unwanted plants.",
"larkspur": "A tall garden plant with blue or white flowers on a long stem.",
"mignonette": "A small garden plant with flowers that have a sweet smell.",
"sidled": "Moved to one side, in small quick steps, as a bird does.",
"defiantly": "In a way that shows you will not do as you are told.",
"creeper": "A plant that grows up walls or trees.",
"lichen": "A flat, greenish growth that covers trees and stones.",
"wick": "A Yorkshire word for alive and full of life. In the book Mary is told that it means alive or lively.",
"whitethorn": "A small tree with sharp points and white flowers.",
"knobstick": "A stick with a round end at the top.",
"spick": "'Spick and span' means very clean and tidy.",
"distended": "Made bigger and tight, because it is full of something.",
"lily": "A tall garden plant with large, showy flowers.",
"missel": "Part of the name of a big brown bird that sings.",
"crabbed": "Cross and hard to please.",
"brooch": "A small shiny thing worn on clothes for show.",
"quavered": "Spoke with a voice that was not steady.",
"tiresome": "Making you feel tired or cross.",
"rebellious": "Not willing to do what rules or people in charge say.",
"agate": "A hard stone with lines of colour. The book uses it for the colour of Colin's eyes.",
"wrapper": "A piece of clothing worn over night clothes.",
"clambered": "Went up in a rough way, using hands and feet.",
"bewitched": "Changed by what seems like magic.",
"sylum": "Short for an old word for a place where people who are very ill in the mind are kept.",
"brace": "A hard support worn on the body to hold the back straight.",
"rheumatic": "Having a sickness that makes the knees and other joints hurt.",
"typhoid": "A serious sickness that makes the body very hot.",
"brocaded": "Made of rich cloth with a raised design.",
"curtsy": "A way a girl or woman shows respect: bending the knees with one foot back.",
"charm": "To make animals or people do as you wish, as if by magic.",
"scrawny": "Very thin, with bones that show.",
"slamp": "A Yorkshire word meaning to lie down flat. It is said of hair that will not lie flat on the head.",
"waft": "A light movement of air carrying a smell.",
"fluting": "Making soft, high, sweet sounds, like a musical pipe.",
"scores": "Many; 20 or more. 'Scores of birds' means very many birds.",
"unbolt": "To open a door by pulling back the metal bar that holds it shut.",
"herbaceous": "Of plants whose parts above the ground die each winter and grow again. 'Herbaceous beds' are garden beds of such plants.",
"unfurling": "Opening out from a rolled-up shape.",
"plumaged": "Having a certain kind of soft covering on a bird's body. 'Glossy-plumaged' means with a shiny covering.",
"tousled": "With hair in a mess.",
"rook": "A big black bird that lives in groups in tall trees.",
"condescended": "Did something kind as if you were too good for the person.",
"nutcracker": "A tool with two arms, used to break open hard shells. In the book a face is said to look like one, sharp and pinched.",
"vixen": "A female wild animal like a small dog with a red coat. Used for a girl who is sharp and angry.",
"monogram": "Letters of a person's name put together in a design on something.",
"pampered": "Given too much care, and everything you want.",
"writhe": "To turn the body about, as if in pain.",
"hunch": "A bump on the back, as a hunchback has.",
"happen": "A Yorkshire word meaning 'perhaps'.",
"affectation": "Acting in a way that is not natural, to seem nicer or better than you are.",
"enraptured": "Filled with great happiness and wonder.",
"wands": "Thin sticks used in stories to do magic.",
"spires": "Tall, thin points. Here, tall thin shapes made by many blossoms on one stem.",
"bromide": "A medicine that makes a person quiet and sleepy.",
"austerely": "In a serious, cold way, with no softness.",
"ravenous": "Very hungry. Here it is said of how a very young animal drinks milk.",
"bleat": "The thin cry that a sheep makes.",
"columbine": "A garden flower with small curved parts that look like tails.",
"snapdragon": "A garden flower that opens and shuts like a mouth when you press it.",
"signet": "A ring with a small picture or letters cut into it, used by important people to press a mark in wax.",
"salaams": "Low bendings of the body with the hand at the head, used in India to show respect.",
"sulky": "Quiet and cross because you are not pleased.",
"primrose": "A small light yellow flower of spring.",
"uncanny": "Strange, in a way that is a little scary.",
"humped": "With a bump on the back.",
"servitor": "An old word for a person who does work for another and does what he is told.",
"morbid": "Having dark, sad thoughts, especially about sickness and death.",
"garlands": "Rings made of leaves and flowers.",
"tendrils": "Thin curly parts of a plant that hold on to things.",
"fanciful": "Made up in the mind, not real.",
"canopy": "A cover that spreads over a place high up.",
"flusters": "Makes someone feel worried and not able to think clearly.",
"rhododendron": "A big garden plant with large, bright flowers.",
"crumpets": "Small round soft food eaten hot with butter.",
"lances": "Long thin spears. Here it means long thin lines of light from the sun.",
"besom": "A Yorkshire word for an annoying, cross woman or girl. It is also the word for a tool for cleaning floors.",
"drat": "An old word used when you are cross.",
"impidint": "A Yorkshire way to say 'impudent'; rude and bold.",
"imperiously": "In a proud way that expects people to do as told.",
"gnarled": "Rough and bent out of shape, with hard bumps, like old wood.",
"lath": "A thin, narrow piece of wood.",
"reigned": "Ruled, as a king does. Here it means happiness was everywhere.",
"jackasses": "Male animals like small horses with long ears; used for silly people.",
"brayin": "Making the loud, rough cry of an animal like a small horse with long ears. The book writes it as brayin'.",
"pluck": "Being brave when things are hard.",
"exultation": "Very great happiness because you have won.",
"hobbled": "Walked slowly in an uneven way, with trouble.",
"slapping": "Hitting with the open hand. 'A slapping sort of man' means a man who hits people.",
"crevices": "Narrow gaps in a wall or rock.",
"satiny": "Smooth and shiny, like a soft cloth.",
"sundial": "A tool in a garden that shows the time by where the sun makes a dark line.",
"unsheath": "To take out of a cover. Here it means new growth opening out of its covers.",
"fakirs": "Holy men in India who live very simply and are said to do wonderful things.",
"sinetifik": "A Yorkshire way to say 'scientific'.",
"devotees": "People who give themselves fully to a religion or to something they love.",
"dervishes": "Holy men who move round and round as part of their prayers.",
"prizefighter": "A man who fights with bare hands for money.",
"fascination": "A strong power to hold your interest.",
"twilight": "The soft, low light after the sun has gone down.",
"haze": "Thin smoke or water in the air that makes things hard to see clearly.",
"pother": "A state of worry and noise about small things.",
"currants": "Small dried black fruit, used in sweet food that is baked.",
"bounteous": "Giving freely and a lot.",
"bloated": "Made too big and full, with air or water.",
"clotted": "Thick and in lumps. 'Clotted cream' is a very thick food made from milk.",
"pantry": "A small room where food is kept.",
"revelation": "The telling of something that was not known.",
"riot": "Wild and noisy action. Here, wild, happy excitement.",
"glummest": "The most sad and quiet.",
"secrete": "To hide something. Here, the robin hides himself among the leaves of a plant.",
"disconcerting": "Making you feel uneasy and not sure what to do.",
"fledged": "Grown up enough to fly (of a young bird).",
"brooded": "Sat over, as a bird sits over eggs to keep them warm. Here, 'brooded over by a great peace' means filled with peace.",
"inordinately": "Much more than is right or normal.",
"boudoir": "A woman's own private room.",
"pilgrimage": "A trip to a special place. Here, Mary's first walk through the empty rooms.",
"parrot": "A bird with bright colours that can copy words.",
"incantations": "Words said again and again, as if to make magic.",
"rapturous": "Full of great happiness.",
"doxology": "A short song that thanks God, sung in church.",
"dappling": "Making spots of light and dark.",
"gloating": "Looking with great happiness, in a proud or selfish way.",
"tremulously": "In a way that is not steady, with the voice or body moving a little.",
"bandy": "Bent out at the knees, with the legs wide apart.",
"rasping": "Rough and unpleasant in sound.",
"wilt": "An old form of 'will' used when speaking to one person as 'you'.",
"drumsticks": "Sticks used to make music by hitting; here, thin legs.",
"thistle": "A wild plant with sharp points on its leaves and a red-blue flower.",
"fjords": "Long, narrow arms of the sea between high hills of rock, in Norway.",
"gentians": "Deep blue flowers that grow on mountains.",
"stagnant": "Not moving or flowing, so that it goes bad. Said of water.",
"salver": "A flat plate of metal, used for carrying letters or food.",
"sovereign": "An old British piece of money made of gold.",
"embowered": "Shut in by branches of trees, like a room.",
"stepladder": "A short set of steps to climb on, which stands by itself.",
"laurels": "Plants with shiny dark leaves.",
}
