M2 = {
"sour": "Unhappy and cross. Here it shows in the look on a face.",
"sahib": "In India, a word of respect. It is used for a European woman ('Mem Sahib') and for a girl ('Missie Sahib').",
"hibiscus": "A plant with a big, bright flower that grows in hot countries.",
"wrung": "Pressed hard and turned. 'Wrung her hands' shows great worry or sadness.",
"drowsy": "Wanting to go to sleep.",
"hunchback": "A person whose back is bent out into a round shape.",
"mantle": "A coat that is not tight, with no part for the arms, worn over other clothes.",
"fringe": "An edge made of many small strings that fall from it.",
"bonnet": "A covering for a woman's head, held on by a band that goes under the bottom of the face.",
"marred": "Made worse. In this book a Yorkshire word for a child who has been given too much and is now cross.",
"lulled": "Made quiet and ready to sleep by a soft, even sound.",
"brougham": "A closed vehicle pulled by a horse, used by rich people long ago.",
"heather": "A low wild plant found on wild open hills. Each small branch has a tiny flower of a red-blue colour.",
"gorse": "A wild plant with sharp points. Its flower is bright yellow.",
"broom": "A wild plant with long thin branches. Its flower is yellow. Here it is a plant, not a tool for cleaning floors.",
"tapestry": "A heavy cloth with a picture made in it, put up on a wall.",
"embroidered": "Having a picture or design made on cloth with coloured string.",
"scullery": "A small room in a big house, used for cleaning the things used for cooking and eating.",
"marmalade": "A sweet sticky food made from fruit, put on food in the morning.",
"surly": "Rude and not friendly.",
"crustily": "In a rude and not friendly way.",
"preen": "When a bird preens, it cleans and puts in order the soft covering of its body with its beak.",
"collie": "A kind of dog with long hair, used on a farm to watch the animals.",
"pewter": "A soft metal used to make cups and bowls.",
"ruffs": "Wide, round neck-cloths with many bends in them, worn long ago.",
"ivory": "The hard white material from the long teeth of a very large animal with a long nose.",
"vixon": "A Yorkshire way to say 'vixen': a sharp, angry girl or woman. The mother of Martha uses it for a cross girl.",
"contrariness": "Going against what other people want, again and again.",
"fumbling": "Using your hands badly to find or hold something.",
"tuppence": "A small amount of old British money, worth two of the smallest pieces.",
"tendril": "A thin part of a plant that goes round things and holds on.",
"hazy": "Not clear, as if seen through thin smoke.",
"narcissus": "A white or yellow flower of spring, often grown in gardens.",
"tremulous": "Not firm; moving a little in a way you cannot stop.",
"trowel": "A small garden tool with a short handle, used to make small holes in the ground.",
"larkspur": "A tall garden plant. Its flower is blue or white.",
"mignonette": "A small garden plant with a flower that has a sweet perfume.",
"lichen": "A flat growth of light green colour that covers trees and stones.",
"whitethorn": "A small tree with sharp points. Its flower is white.",
"spick": "'Spick and span' means very clean and in good order.",
"distended": "Made bigger and full to the edge, because it has too much inside.",
"lily": "A tall garden plant with a large, beautiful flower.",
"quavered": "Spoke with a voice that was not strong and even.",
"scrawny": "Very thin, with the shape of the bone showing.",
"waft": "A light movement of air carrying something that your nose picks up.",
"fluting": "Making soft, high, sweet sounds, like a thin tube played by blowing.",
"plumaged": "Having a certain kind of soft covering on a bird's body. In the book it is shiny.",
"tousled": "With hair that is not in order.",
"nutcracker": "A tool with two arms, used to break open hard shells. In the book a face is said to look like one, sharp and thin.",
"hunch": "A round part of the back that sticks out, as a hunchback has.",
"spires": "Tall, thin points. Here, tall narrow shapes made by one kind of flower.",
"bromide": "A medicine that makes a person quiet and ready to sleep.",
"bleat": "A thin cry, as made by a farm animal with a thick white coat.",
"signet": "A ring with a small picture or letters cut into it, used by important people to make their sign on letters.",
"salaams": "Ways of showing respect in India: bending low with the hand at the head.",
"uncanny": "Strange, in a way that makes you a little afraid.",
"humped": "With a round part sticking out on the back.",
"garlands": "Rings of leaves and flower, worn or hung for show.",
"tendrils": "Thin parts of a plant that go round things and hold on.",
"rhododendron": "A big garden plant that is full of large, bright flower in spring.",
"besom": "A Yorkshire word for a cross woman or girl who makes trouble. It is also the word for a tool for cleaning floors.",
"impidint": "A Yorkshire way to say 'impudent'; rude and showing no respect.",
"gnarled": "Rough and bent out of shape, like very old wood.",
"jackasses": "Male animals like small horses; the name is used for silly people.",
"brayin": "Making the loud, rough cry of an animal like a small horse. The book writes it as brayin'.",
"crevices": "Narrow openings in a wall or rock.",
"dervishes": "Holy men who move round and round as part of their religion.",
"prizefighter": "A man who fights with his hands for money.",
"currants": "Small dried black fruit, used in sweet food.",
"clotted": "Thick and heavy. Here it is said of a very thick yellow food made from milk.",
"riot": "Wild and loud action. Here, wild, happy feeling.",
"secrete": "To hide something. Here, a small bird puts itself out of sight among a plant's leaves.",
"doxology": "A short song that thanks God, used in church.",
"gloating": "Looking with great happiness, often in a proud way.",
"tremulously": "In a way that is not firm, with the voice or body moving a little.",
"gentians": "Deep blue flower of the mountains.",
"salver": "A flat piece of metal for carrying letters or food on.",
"stepladder": "A short set of steps to stand on, which stands by itself.",
}
